export const measureData = [
    {
        locationId: 1,
        locationName: 'Corporate Plaza East',
        countryCodeISO2A: 'GBD',
        admin1Code: 'GB-ENG',
        occupancyCode: 'ATC 8',
        occupancyName: 'Business Services',
        occupancy: 'Manufacturing',
        entity: 'Corporate',
        totalValue: 3537400.0,
        unadaptedAAL: 6188,
        unadaptedAAL2055: 11250,
        implementationYear: '2025',
        elevateStructure: '50',
        siteLevelProtection: '100',
        floodProofing: false,
        windEngineeringRetrofit: '50',
        nonFlammableRoofMaterial: false,
        doublePaneWindows: false,
        emberResistantVents: false,
        installAirConditioning: '100%',
        coolRoof: false,
        adaptedAAL: 50000,
        delta: '50k',
        capex: '75k',
        npv: '20k',
        roi: '50k',
        breakevenYear: '2040',
    },
    {
        locationId: 2,
        locationName: 'Innovation Campus Building',
        countryCodeISO2A: 'GBD',
        admin1Code: 'GB-ENG',
        occupancyCode: 'ATC 8',
        occupancyName: 'Business Services',
        occupancy: 'Office Space',
        entity: 'Research',
        totalValue: 10612200.0,
        unadaptedAAL: 8250,
        unadaptedAAL2055: 15000,
        implementationYear: '2030',
        elevateStructure: '50',
        siteLevelProtection: '50',
        floodProofing: false,
        windEngineeringRetrofit: '100',
        nonFlammableRoofMaterial: false,
        doublePaneWindows: false,
        emberResistantVents: false,
        installAirConditioning: '50%',
        coolRoof: false,
        adaptedAAL: 150000,
        delta: '50k',
        capex: '100k',
        npv: '30k',
        roi: '50k',
        breakevenYear: '2045',
    },
    {
        locationId: 3,
        locationName: 'Metro Business Park Tower',
        countryCodeISO2A: 'GBD',
        admin1Code: 'GB-ENG',
        occupancyCode: 'ATC 8',
        occupancyName: 'Business Services',
        occupancy: 'Infrastructure Facility',
        entity: 'Corporate',
        totalValue: 1414960.0,
        unadaptedAAL: 2063,
        unadaptedAAL2055: 3750,
        implementationYear: '2030',
        elevateStructure: '50',
        siteLevelProtection: '50',
        floodProofing: false,
        windEngineeringRetrofit: '50',
        nonFlammableRoofMaterial: false,
        doublePaneWindows: false,
        emberResistantVents: false,
        installAirConditioning: '75%',
        coolRoof: false,
        adaptedAAL: 175000,
        delta: '50k',
        capex: '120k',
        npv: '40k',
        roi: '50k',
        breakevenYear: '2050',
    },
    {
        locationId: 4,
        locationName: 'Central Distribution Hub',
        countryCodeISO2A: 'CHN',
        admin1Code: 'CN-GD',
        occupancyCode: 'ATC 6',
        occupancyName: 'Wholesale Trade',
        occupancy: 'Residential',
        entity: 'Operations',
        totalValue: 10612200.0,
        unadaptedAAL: 47438,
        unadaptedAAL2055: 86250,
        implementationYear: '2030',
        elevateStructure: '100',
        siteLevelProtection: '200',
        floodProofing: true,
        windEngineeringRetrofit: '50',
        nonFlammableRoofMaterial: true,
        doublePaneWindows: true,
        emberResistantVents: true,
        installAirConditioning: '100%',
        coolRoof: true,
        adaptedAAL: 120000,
        delta: '60k',
        capex: '90k',
        npv: '35k',
        roi: '60k',
        breakevenYear: '2038',
    },
    {
        locationId: 5,
        locationName: 'Northwest Storage Complex',
        countryCodeISO2A: 'GBD',
        admin1Code: 'GB-ENG',
        occupancyCode: 'ATC 6',
        occupancyName: 'Wholesale Trade',
        occupancy: 'Medical Equipment',
        entity: 'Operations',
        totalValue: 3537400.0,
        unadaptedAAL: 18563,
        unadaptedAAL2055: 33750,
        implementationYear: '2030',
        elevateStructure: '50',
        siteLevelProtection: '50',
        floodProofing: false,
        windEngineeringRetrofit: '500',
        nonFlammableRoofMaterial: false,
        doublePaneWindows: false,
        emberResistantVents: false,
        installAirConditioning: '50%',
        coolRoof: false,
        adaptedAAL: 100000,
        delta: '60k',
        capex: '85k',
        npv: '25k',
        roi: '60k',
        breakevenYear: '2042',
    },
    {
        locationId: 6,
        locationName: 'Riverside Fulfillment Center',
        countryCodeISO2A: 'USA',
        admin1Code: 'US-CA',
        occupancyCode: 'ATC 6',
        occupancyName: 'Wholesale Trade',
        occupancy: 'High Rise',
        entity: 'Operations',
        totalValue: 4244880.0,
        unadaptedAAL: 22688,
        unadaptedAAL2055: 41250,
        implementationYear: '2030',
        elevateStructure: '200',
        siteLevelProtection: '100',
        floodProofing: true,
        windEngineeringRetrofit: '50',
        nonFlammableRoofMaterial: true,
        doublePaneWindows: true,
        emberResistantVents: true,
        installAirConditioning: '75%',
        coolRoof: false,
        adaptedAAL: 180000,
        delta: '120k',
        capex: '150k',
        npv: '80k',
        roi: '120k',
        breakevenYear: '2048',
    },
    {
        locationId: 7,
        locationName: 'Downtown Flagship Store',
        countryCodeISO2A: 'GBD',
        admin1Code: 'GB-ENG',
        occupancyCode: 'ATC 5',
        occupancyName: 'Retail Trade',
        occupancy: 'Apartment Complex',
        entity: 'Sales',
        totalValue: 2122440.0,
        unadaptedAAL: 6188,
        unadaptedAAL2055: 11250,
        implementationYear: '2030',
        elevateStructure: '50',
        siteLevelProtection: '50',
        floodProofing: false,
        windEngineeringRetrofit: '100',
        nonFlammableRoofMaterial: false,
        doublePaneWindows: true,
        emberResistantVents: false,
        installAirConditioning: '100%',
        coolRoof: false,
        adaptedAAL: 200000,
        delta: '75k',
        capex: '110k',
        npv: '45k',
        roi: '75k',
        breakevenYear: '2046',
    },
    {
        locationId: 8,
        locationName: 'Suburban Retail Outlet',
        countryCodeISO2A: 'USA',
        admin1Code: 'US-CA',
        occupancyCode: 'ATC 5',
        occupancyName: 'Retail Trade',
        occupancy: 'Hospital',
        entity: 'Sales',
        totalValue: 1414960.0,
        unadaptedAAL: 4125,
        unadaptedAAL2055: 7500,
        implementationYear: '2025',
        elevateStructure: '50',
        siteLevelProtection: '500',
        floodProofing: false,
        windEngineeringRetrofit: '50',
        nonFlammableRoofMaterial: false,
        doublePaneWindows: false,
        emberResistantVents: false,
        installAirConditioning: '75%',
        coolRoof: true,
        adaptedAAL: 240000,
        delta: '80k',
        capex: '140k',
        npv: '60k',
        roi: '80k',
        breakevenYear: '2044',
    },
    {
        locationId: 9,
        locationName: 'Crossroads Shopping Center',
        countryCodeISO2A: 'FRA',
        admin1Code: 'FR-IDF',
        occupancyCode: 'ATC 5',
        occupancyName: 'Retail Trade',
        occupancy: 'Retail',
        entity: 'Sales',
        totalValue: 2122440.0,
        unadaptedAAL: 6188,
        unadaptedAAL2055: 11250,
        implementationYear: '2030',
        elevateStructure: '500',
        siteLevelProtection: '50',
        floodProofing: true,
        windEngineeringRetrofit: '50',
        nonFlammableRoofMaterial: true,
        doublePaneWindows: false,
        emberResistantVents: true,
        installAirConditioning: '100%',
        coolRoof: false,
        adaptedAAL: 135000,
        delta: '60k',
        capex: '95k',
        npv: '38k',
        roi: '60k',
        breakevenYear: '2041',
    },
    {
        locationId: 10,
        locationName: 'Advanced Manufacturing Plant',
        countryCodeISO2A: 'CHN',
        admin1Code: 'CN-GD',
        occupancyCode: 'ATC 13',
        occupancyName: 'Light industrial',
        occupancy: 'Laboratory',
        entity: 'Operations',
        totalValue: 17687000.0,
        unadaptedAAL: 84563,
        unadaptedAAL2055: 153750,
        implementationYear: '2035',
        elevateStructure: '100',
        siteLevelProtection: '50',
        floodProofing: false,
        windEngineeringRetrofit: '200',
        nonFlammableRoofMaterial: false,
        doublePaneWindows: true,
        emberResistantVents: false,
        installAirConditioning: '100%',
        coolRoof: true,
        adaptedAAL: 170000,
        delta: '80k',
        capex: '125k',
        npv: '55k',
        roi: '80k',
        breakevenYear: '2047',
    },
];
