/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateExportInput,
  ErrorResponse,
  ExportOutput,
  ExportStatus,
  ExportType,
  HTTPValidationError,
  ListExportsResponse,
} from '../models/index';
import {
    CreateExportInputFromJSON,
    CreateExportInputToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExportOutputFromJSON,
    ExportOutputToJSON,
    ExportStatusFromJSON,
    ExportStatusToJSON,
    ExportTypeFromJSON,
    ExportTypeToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListExportsResponseFromJSON,
    ListExportsResponseToJSON,
} from '../models/index';

export interface CreateExportExportsPostRequest {
    createExportInput: CreateExportInput;
}

export interface DeleteExportExportsExportIdDeleteRequest {
    exportId: string;
}

export interface ListExportsExportsGetRequest {
    limit?: number;
    startingAfter?: string;
    objectId?: string;
    objectType?: ExportType;
    status?: ExportStatus;
}

export interface RetrieveExportExportsExportIdGetRequest {
    exportId: string;
}

/**
 * 
 */
export class ExportsApi extends runtime.BaseAPI {

    /**
     * Create Export
     */
    async createExportExportsPostRaw(requestParameters: CreateExportExportsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportOutput>> {
        if (requestParameters['createExportInput'] == null) {
            throw new runtime.RequiredError(
                'createExportInput',
                'Required parameter "createExportInput" was null or undefined when calling createExportExportsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/exports`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateExportInputToJSON(requestParameters['createExportInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExportOutputFromJSON(jsonValue));
    }

    /**
     * Create Export
     */
    async createExportExportsPost(requestParameters: CreateExportExportsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportOutput> {
        const response = await this.createExportExportsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Export
     */
    async deleteExportExportsExportIdDeleteRaw(requestParameters: DeleteExportExportsExportIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['exportId'] == null) {
            throw new runtime.RequiredError(
                'exportId',
                'Required parameter "exportId" was null or undefined when calling deleteExportExportsExportIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/exports/{export_id}`.replace(`{${"export_id"}}`, encodeURIComponent(String(requestParameters['exportId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Export
     */
    async deleteExportExportsExportIdDelete(requestParameters: DeleteExportExportsExportIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteExportExportsExportIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List Exports
     */
    async listExportsExportsGetRaw(requestParameters: ListExportsExportsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListExportsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['startingAfter'] != null) {
            queryParameters['starting_after'] = requestParameters['startingAfter'];
        }

        if (requestParameters['objectId'] != null) {
            queryParameters['object_id'] = requestParameters['objectId'];
        }

        if (requestParameters['objectType'] != null) {
            queryParameters['object_type'] = requestParameters['objectType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/exports`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListExportsResponseFromJSON(jsonValue));
    }

    /**
     * List Exports
     */
    async listExportsExportsGet(requestParameters: ListExportsExportsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListExportsResponse> {
        const response = await this.listExportsExportsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve Export
     */
    async retrieveExportExportsExportIdGetRaw(requestParameters: RetrieveExportExportsExportIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportOutput>> {
        if (requestParameters['exportId'] == null) {
            throw new runtime.RequiredError(
                'exportId',
                'Required parameter "exportId" was null or undefined when calling retrieveExportExportsExportIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/exports/{export_id}`.replace(`{${"export_id"}}`, encodeURIComponent(String(requestParameters['exportId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExportOutputFromJSON(jsonValue));
    }

    /**
     * Retrieve Export
     */
    async retrieveExportExportsExportIdGet(requestParameters: RetrieveExportExportsExportIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportOutput> {
        const response = await this.retrieveExportExportsExportIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
