/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateFileLinkInput,
  ErrorResponse,
  FileLinkResponse,
  FileResponse,
  HTTPValidationError,
  ListFilesResponse,
} from '../models/index';
import {
    CreateFileLinkInputFromJSON,
    CreateFileLinkInputToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    FileLinkResponseFromJSON,
    FileLinkResponseToJSON,
    FileResponseFromJSON,
    FileResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListFilesResponseFromJSON,
    ListFilesResponseToJSON,
} from '../models/index';

export interface CreateFileDownloadLinkFilesFileIdLinksPostRequest {
    fileId: string;
    createFileLinkInput: CreateFileLinkInput;
}

export interface CreateFileFilesPostRequest {
    file: Blob;
    purpose: CreateFileFilesPostPurposeEnum;
}

export interface DeleteFileFilesFileIdDeleteRequest {
    fileId: string;
}

export interface ListFilesFilesGetRequest {
    limit?: number;
    startingAfter?: string;
}

export interface RetrieveFileFilesFileIdGetRequest {
    fileId: string;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Create File Download Link
     */
    async createFileDownloadLinkFilesFileIdLinksPostRaw(requestParameters: CreateFileDownloadLinkFilesFileIdLinksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileLinkResponse>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling createFileDownloadLinkFilesFileIdLinksPost().'
            );
        }

        if (requestParameters['createFileLinkInput'] == null) {
            throw new runtime.RequiredError(
                'createFileLinkInput',
                'Required parameter "createFileLinkInput" was null or undefined when calling createFileDownloadLinkFilesFileIdLinksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/files/{file_id}/links`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFileLinkInputToJSON(requestParameters['createFileLinkInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileLinkResponseFromJSON(jsonValue));
    }

    /**
     * Create File Download Link
     */
    async createFileDownloadLinkFilesFileIdLinksPost(requestParameters: CreateFileDownloadLinkFilesFileIdLinksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileLinkResponse> {
        const response = await this.createFileDownloadLinkFilesFileIdLinksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create File
     */
    async createFileFilesPostRaw(requestParameters: CreateFileFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling createFileFilesPost().'
            );
        }

        if (requestParameters['purpose'] == null) {
            throw new runtime.RequiredError(
                'purpose',
                'Required parameter "purpose" was null or undefined when calling createFileFilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['purpose'] != null) {
            formParams.append('purpose', requestParameters['purpose'] as any);
        }

        const response = await this.request({
            path: `/files`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileResponseFromJSON(jsonValue));
    }

    /**
     * Create File
     */
    async createFileFilesPost(requestParameters: CreateFileFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileResponse> {
        const response = await this.createFileFilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete File
     */
    async deleteFileFilesFileIdDeleteRaw(requestParameters: DeleteFileFilesFileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling deleteFileFilesFileIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/files/{file_id}`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete File
     */
    async deleteFileFilesFileIdDelete(requestParameters: DeleteFileFilesFileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFileFilesFileIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List Files
     */
    async listFilesFilesGetRaw(requestParameters: ListFilesFilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFilesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['startingAfter'] != null) {
            queryParameters['starting_after'] = requestParameters['startingAfter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/files`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFilesResponseFromJSON(jsonValue));
    }

    /**
     * List Files
     */
    async listFilesFilesGet(requestParameters: ListFilesFilesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFilesResponse> {
        const response = await this.listFilesFilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve File
     */
    async retrieveFileFilesFileIdGetRaw(requestParameters: RetrieveFileFilesFileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileResponse>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling retrieveFileFilesFileIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/files/{file_id}`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve File
     */
    async retrieveFileFilesFileIdGet(requestParameters: RetrieveFileFilesFileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileResponse> {
        const response = await this.retrieveFileFilesFileIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateFileFilesPostPurposeEnum = {
    portfolioUpload: 'portfolio_upload',
    unknownDefaultOpenApi: '11184809'
} as const;
export type CreateFileFilesPostPurposeEnum = typeof CreateFileFilesPostPurposeEnum[keyof typeof CreateFileFilesPostPurposeEnum];
