/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  HTTPValidationError,
  PerilQueryInput,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PerilQueryInputFromJSON,
    PerilQueryInputToJSON,
} from '../models/index';

export interface QueryPerilsPerilsPostRequest {
    perilQueryInput: PerilQueryInput;
}

/**
 * 
 */
export class PerilsApi extends runtime.BaseAPI {

    /**
     * Query Perils
     */
    async queryPerilsPerilsPostRaw(requestParameters: QueryPerilsPerilsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['perilQueryInput'] == null) {
            throw new runtime.RequiredError(
                'perilQueryInput',
                'Required parameter "perilQueryInput" was null or undefined when calling queryPerilsPerilsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/perils`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PerilQueryInputToJSON(requestParameters['perilQueryInput']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Query Perils
     */
    async queryPerilsPerilsPost(requestParameters: QueryPerilsPerilsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.queryPerilsPerilsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
