/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePortfolioInput,
  ErrorResponse,
  HTTPValidationError,
  ListPortfoliosResponse,
  ListingMode,
  PortfolioResponse,
  PortfolioSharingInput,
  PortfolioSharingOutput,
  UpdatePortfolioInput,
} from '../models/index';
import {
    CreatePortfolioInputFromJSON,
    CreatePortfolioInputToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListPortfoliosResponseFromJSON,
    ListPortfoliosResponseToJSON,
    ListingModeFromJSON,
    ListingModeToJSON,
    PortfolioResponseFromJSON,
    PortfolioResponseToJSON,
    PortfolioSharingInputFromJSON,
    PortfolioSharingInputToJSON,
    PortfolioSharingOutputFromJSON,
    PortfolioSharingOutputToJSON,
    UpdatePortfolioInputFromJSON,
    UpdatePortfolioInputToJSON,
} from '../models/index';

export interface CreatePortfolioPortfoliosPostRequest {
    createPortfolioInput: CreatePortfolioInput;
}

export interface DeletePortfolioPortfoliosPortfolioIdDeleteRequest {
    portfolioId: string;
}

export interface GetSharedUsersPortfoliosPortfolioIdSharedUsersGetRequest {
    portfolioId: string;
}

export interface ListPortfoliosPortfoliosGetRequest {
    limit?: number;
    startingAfter?: string;
    listingMode?: ListingMode;
    zedtoken?: string;
}

export interface RetrievePortfolioPortfoliosPortfolioIdGetRequest {
    portfolioId: string;
}

export interface SharePortfolioPortfoliosPortfolioIdSharePostRequest {
    portfolioId: string;
    portfolioSharingInput: PortfolioSharingInput;
}

export interface UnsharePortfolioPortfoliosPortfolioIdUnsharePostRequest {
    portfolioId: string;
    portfolioSharingInput: PortfolioSharingInput;
}

export interface UnsharePortfolioSelfPortfoliosPortfolioIdUnshareSelfGetRequest {
    portfolioId: string;
}

export interface UpdatePortfolioPortfoliosPortfolioIdPutRequest {
    portfolioId: string;
    updatePortfolioInput: UpdatePortfolioInput;
}

/**
 * 
 */
export class PortfoliosApi extends runtime.BaseAPI {

    /**
     * Create Portfolio
     */
    async createPortfolioPortfoliosPostRaw(requestParameters: CreatePortfolioPortfoliosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioResponse>> {
        if (requestParameters['createPortfolioInput'] == null) {
            throw new runtime.RequiredError(
                'createPortfolioInput',
                'Required parameter "createPortfolioInput" was null or undefined when calling createPortfolioPortfoliosPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePortfolioInputToJSON(requestParameters['createPortfolioInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioResponseFromJSON(jsonValue));
    }

    /**
     * Create Portfolio
     */
    async createPortfolioPortfoliosPost(requestParameters: CreatePortfolioPortfoliosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioResponse> {
        const response = await this.createPortfolioPortfoliosPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Portfolio
     */
    async deletePortfolioPortfoliosPortfolioIdDeleteRaw(requestParameters: DeletePortfolioPortfoliosPortfolioIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling deletePortfolioPortfoliosPortfolioIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios/{portfolio_id}`.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Portfolio
     */
    async deletePortfolioPortfoliosPortfolioIdDelete(requestParameters: DeletePortfolioPortfoliosPortfolioIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePortfolioPortfoliosPortfolioIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Shared Users
     */
    async getSharedUsersPortfoliosPortfolioIdSharedUsersGetRaw(requestParameters: GetSharedUsersPortfoliosPortfolioIdSharedUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling getSharedUsersPortfoliosPortfolioIdSharedUsersGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios/{portfolio_id}/shared_users`.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Shared Users
     */
    async getSharedUsersPortfoliosPortfolioIdSharedUsersGet(requestParameters: GetSharedUsersPortfoliosPortfolioIdSharedUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getSharedUsersPortfoliosPortfolioIdSharedUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Portfolios
     */
    async listPortfoliosPortfoliosGetRaw(requestParameters: ListPortfoliosPortfoliosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPortfoliosResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['startingAfter'] != null) {
            queryParameters['starting_after'] = requestParameters['startingAfter'];
        }

        if (requestParameters['listingMode'] != null) {
            queryParameters['listing_mode'] = requestParameters['listingMode'];
        }

        if (requestParameters['zedtoken'] != null) {
            queryParameters['zedtoken'] = requestParameters['zedtoken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPortfoliosResponseFromJSON(jsonValue));
    }

    /**
     * List Portfolios
     */
    async listPortfoliosPortfoliosGet(requestParameters: ListPortfoliosPortfoliosGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPortfoliosResponse> {
        const response = await this.listPortfoliosPortfoliosGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve Portfolio
     */
    async retrievePortfolioPortfoliosPortfolioIdGetRaw(requestParameters: RetrievePortfolioPortfoliosPortfolioIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioResponse>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling retrievePortfolioPortfoliosPortfolioIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios/{portfolio_id}`.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve Portfolio
     */
    async retrievePortfolioPortfoliosPortfolioIdGet(requestParameters: RetrievePortfolioPortfoliosPortfolioIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioResponse> {
        const response = await this.retrievePortfolioPortfoliosPortfolioIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Share Portfolio
     */
    async sharePortfolioPortfoliosPortfolioIdSharePostRaw(requestParameters: SharePortfolioPortfoliosPortfolioIdSharePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioSharingOutput>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling sharePortfolioPortfoliosPortfolioIdSharePost().'
            );
        }

        if (requestParameters['portfolioSharingInput'] == null) {
            throw new runtime.RequiredError(
                'portfolioSharingInput',
                'Required parameter "portfolioSharingInput" was null or undefined when calling sharePortfolioPortfoliosPortfolioIdSharePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios/{portfolio_id}/share`.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioSharingInputToJSON(requestParameters['portfolioSharingInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioSharingOutputFromJSON(jsonValue));
    }

    /**
     * Share Portfolio
     */
    async sharePortfolioPortfoliosPortfolioIdSharePost(requestParameters: SharePortfolioPortfoliosPortfolioIdSharePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioSharingOutput> {
        const response = await this.sharePortfolioPortfoliosPortfolioIdSharePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unshare Portfolio
     */
    async unsharePortfolioPortfoliosPortfolioIdUnsharePostRaw(requestParameters: UnsharePortfolioPortfoliosPortfolioIdUnsharePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioSharingOutput>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling unsharePortfolioPortfoliosPortfolioIdUnsharePost().'
            );
        }

        if (requestParameters['portfolioSharingInput'] == null) {
            throw new runtime.RequiredError(
                'portfolioSharingInput',
                'Required parameter "portfolioSharingInput" was null or undefined when calling unsharePortfolioPortfoliosPortfolioIdUnsharePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios/{portfolio_id}/unshare`.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioSharingInputToJSON(requestParameters['portfolioSharingInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioSharingOutputFromJSON(jsonValue));
    }

    /**
     * Unshare Portfolio
     */
    async unsharePortfolioPortfoliosPortfolioIdUnsharePost(requestParameters: UnsharePortfolioPortfoliosPortfolioIdUnsharePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioSharingOutput> {
        const response = await this.unsharePortfolioPortfoliosPortfolioIdUnsharePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unshare Portfolio Self
     */
    async unsharePortfolioSelfPortfoliosPortfolioIdUnshareSelfGetRaw(requestParameters: UnsharePortfolioSelfPortfoliosPortfolioIdUnshareSelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling unsharePortfolioSelfPortfoliosPortfolioIdUnshareSelfGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios/{portfolio_id}/unshare_self`.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Unshare Portfolio Self
     */
    async unsharePortfolioSelfPortfoliosPortfolioIdUnshareSelfGet(requestParameters: UnsharePortfolioSelfPortfoliosPortfolioIdUnshareSelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.unsharePortfolioSelfPortfoliosPortfolioIdUnshareSelfGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Portfolio
     */
    async updatePortfolioPortfoliosPortfolioIdPutRaw(requestParameters: UpdatePortfolioPortfoliosPortfolioIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioResponse>> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling updatePortfolioPortfoliosPortfolioIdPut().'
            );
        }

        if (requestParameters['updatePortfolioInput'] == null) {
            throw new runtime.RequiredError(
                'updatePortfolioInput',
                'Required parameter "updatePortfolioInput" was null or undefined when calling updatePortfolioPortfoliosPortfolioIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/portfolios/{portfolio_id}`.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePortfolioInputToJSON(requestParameters['updatePortfolioInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioResponseFromJSON(jsonValue));
    }

    /**
     * Update Portfolio
     */
    async updatePortfolioPortfoliosPortfolioIdPut(requestParameters: UpdatePortfolioPortfoliosPortfolioIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioResponse> {
        const response = await this.updatePortfolioPortfoliosPortfolioIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
