/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResultSetInput,
  ErrorResponse,
  HTTPValidationError,
  ListResultSetsResponse,
  ResultSetDataQueryParams,
  ResultSetDataResponse,
  ResultSetMetadataResponse,
  ResultSetResponse,
  ResultSetSchemaResponse,
  ResultSetStatus,
  ResultSetType,
  UpdateResultSetInput,
} from '../models/index';
import {
    CreateResultSetInputFromJSON,
    CreateResultSetInputToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResultSetsResponseFromJSON,
    ListResultSetsResponseToJSON,
    ResultSetDataQueryParamsFromJSON,
    ResultSetDataQueryParamsToJSON,
    ResultSetDataResponseFromJSON,
    ResultSetDataResponseToJSON,
    ResultSetMetadataResponseFromJSON,
    ResultSetMetadataResponseToJSON,
    ResultSetResponseFromJSON,
    ResultSetResponseToJSON,
    ResultSetSchemaResponseFromJSON,
    ResultSetSchemaResponseToJSON,
    ResultSetStatusFromJSON,
    ResultSetStatusToJSON,
    ResultSetTypeFromJSON,
    ResultSetTypeToJSON,
    UpdateResultSetInputFromJSON,
    UpdateResultSetInputToJSON,
} from '../models/index';

export interface CreateResultSetResultSetsPostRequest {
    createResultSetInput: CreateResultSetInput;
}

export interface DeleteResultSetResultSetsResultSetIdDeleteRequest {
    resultSetId: string;
}

export interface ListResultSetsResultSetsGetRequest {
    limit?: number;
    startingAfter?: string;
    portfolio?: string;
    type?: ResultSetType;
    status?: ResultSetStatus;
}

export interface RetrieveResultDataResultSetsResultSetIdDataPostRequest {
    resultSetId: string;
    resultSetDataQueryParams?: ResultSetDataQueryParams;
}

export interface RetrieveResultSchemaResultSetsResultSetIdSchemaGetRequest {
    resultSetId: string;
}

export interface RetrieveResultSetMetadataResultSetsResultSetIdMetadataGetRequest {
    resultSetId: string;
}

export interface RetrieveResultSetResultSetsResultSetIdGetRequest {
    resultSetId: string;
}

export interface UpdateResultSetResultSetsResultSetIdPutRequest {
    resultSetId: string;
    updateResultSetInput: UpdateResultSetInput;
}

/**
 * 
 */
export class ResultSetsApi extends runtime.BaseAPI {

    /**
     * Create Result Set
     */
    async createResultSetResultSetsPostRaw(requestParameters: CreateResultSetResultSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSetResponse>> {
        if (requestParameters['createResultSetInput'] == null) {
            throw new runtime.RequiredError(
                'createResultSetInput',
                'Required parameter "createResultSetInput" was null or undefined when calling createResultSetResultSetsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResultSetInputToJSON(requestParameters['createResultSetInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSetResponseFromJSON(jsonValue));
    }

    /**
     * Create Result Set
     */
    async createResultSetResultSetsPost(requestParameters: CreateResultSetResultSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSetResponse> {
        const response = await this.createResultSetResultSetsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Result Set
     */
    async deleteResultSetResultSetsResultSetIdDeleteRaw(requestParameters: DeleteResultSetResultSetsResultSetIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['resultSetId'] == null) {
            throw new runtime.RequiredError(
                'resultSetId',
                'Required parameter "resultSetId" was null or undefined when calling deleteResultSetResultSetsResultSetIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets/{result_set_id}`.replace(`{${"result_set_id"}}`, encodeURIComponent(String(requestParameters['resultSetId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Result Set
     */
    async deleteResultSetResultSetsResultSetIdDelete(requestParameters: DeleteResultSetResultSetsResultSetIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteResultSetResultSetsResultSetIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List Result Sets
     */
    async listResultSetsResultSetsGetRaw(requestParameters: ListResultSetsResultSetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResultSetsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['startingAfter'] != null) {
            queryParameters['starting_after'] = requestParameters['startingAfter'];
        }

        if (requestParameters['portfolio'] != null) {
            queryParameters['portfolio'] = requestParameters['portfolio'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResultSetsResponseFromJSON(jsonValue));
    }

    /**
     * List Result Sets
     */
    async listResultSetsResultSetsGet(requestParameters: ListResultSetsResultSetsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResultSetsResponse> {
        const response = await this.listResultSetsResultSetsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve Result Data
     */
    async retrieveResultDataResultSetsResultSetIdDataPostRaw(requestParameters: RetrieveResultDataResultSetsResultSetIdDataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSetDataResponse>> {
        if (requestParameters['resultSetId'] == null) {
            throw new runtime.RequiredError(
                'resultSetId',
                'Required parameter "resultSetId" was null or undefined when calling retrieveResultDataResultSetsResultSetIdDataPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets/{result_set_id}/data`.replace(`{${"result_set_id"}}`, encodeURIComponent(String(requestParameters['resultSetId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResultSetDataQueryParamsToJSON(requestParameters['resultSetDataQueryParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSetDataResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve Result Data
     */
    async retrieveResultDataResultSetsResultSetIdDataPost(requestParameters: RetrieveResultDataResultSetsResultSetIdDataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSetDataResponse> {
        const response = await this.retrieveResultDataResultSetsResultSetIdDataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve Result Schema
     */
    async retrieveResultSchemaResultSetsResultSetIdSchemaGetRaw(requestParameters: RetrieveResultSchemaResultSetsResultSetIdSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSetSchemaResponse>> {
        if (requestParameters['resultSetId'] == null) {
            throw new runtime.RequiredError(
                'resultSetId',
                'Required parameter "resultSetId" was null or undefined when calling retrieveResultSchemaResultSetsResultSetIdSchemaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets/{result_set_id}/schema`.replace(`{${"result_set_id"}}`, encodeURIComponent(String(requestParameters['resultSetId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSetSchemaResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve Result Schema
     */
    async retrieveResultSchemaResultSetsResultSetIdSchemaGet(requestParameters: RetrieveResultSchemaResultSetsResultSetIdSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSetSchemaResponse> {
        const response = await this.retrieveResultSchemaResultSetsResultSetIdSchemaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve Result Set Metadata
     */
    async retrieveResultSetMetadataResultSetsResultSetIdMetadataGetRaw(requestParameters: RetrieveResultSetMetadataResultSetsResultSetIdMetadataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSetMetadataResponse>> {
        if (requestParameters['resultSetId'] == null) {
            throw new runtime.RequiredError(
                'resultSetId',
                'Required parameter "resultSetId" was null or undefined when calling retrieveResultSetMetadataResultSetsResultSetIdMetadataGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets/{result_set_id}/metadata`.replace(`{${"result_set_id"}}`, encodeURIComponent(String(requestParameters['resultSetId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSetMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve Result Set Metadata
     */
    async retrieveResultSetMetadataResultSetsResultSetIdMetadataGet(requestParameters: RetrieveResultSetMetadataResultSetsResultSetIdMetadataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSetMetadataResponse> {
        const response = await this.retrieveResultSetMetadataResultSetsResultSetIdMetadataGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve Result Set
     */
    async retrieveResultSetResultSetsResultSetIdGetRaw(requestParameters: RetrieveResultSetResultSetsResultSetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSetResponse>> {
        if (requestParameters['resultSetId'] == null) {
            throw new runtime.RequiredError(
                'resultSetId',
                'Required parameter "resultSetId" was null or undefined when calling retrieveResultSetResultSetsResultSetIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets/{result_set_id}`.replace(`{${"result_set_id"}}`, encodeURIComponent(String(requestParameters['resultSetId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSetResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve Result Set
     */
    async retrieveResultSetResultSetsResultSetIdGet(requestParameters: RetrieveResultSetResultSetsResultSetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSetResponse> {
        const response = await this.retrieveResultSetResultSetsResultSetIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Result Set
     */
    async updateResultSetResultSetsResultSetIdPutRaw(requestParameters: UpdateResultSetResultSetsResultSetIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSetResponse>> {
        if (requestParameters['resultSetId'] == null) {
            throw new runtime.RequiredError(
                'resultSetId',
                'Required parameter "resultSetId" was null or undefined when calling updateResultSetResultSetsResultSetIdPut().'
            );
        }

        if (requestParameters['updateResultSetInput'] == null) {
            throw new runtime.RequiredError(
                'updateResultSetInput',
                'Required parameter "updateResultSetInput" was null or undefined when calling updateResultSetResultSetsResultSetIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/result_sets/{result_set_id}`.replace(`{${"result_set_id"}}`, encodeURIComponent(String(requestParameters['resultSetId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResultSetInputToJSON(requestParameters['updateResultSetInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSetResponseFromJSON(jsonValue));
    }

    /**
     * Update Result Set
     */
    async updateResultSetResultSetsResultSetIdPut(requestParameters: UpdateResultSetResultSetsResultSetIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSetResponse> {
        const response = await this.updateResultSetResultSetsResultSetIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
