/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DamagesOptionsOutput } from './DamagesOptionsOutput';
import {
    DamagesOptionsOutputFromJSON,
    DamagesOptionsOutputFromJSONTyped,
    DamagesOptionsOutputToJSON,
} from './DamagesOptionsOutput';
import type { AdaptationStrategiesOutput } from './AdaptationStrategiesOutput';
import {
    AdaptationStrategiesOutputFromJSON,
    AdaptationStrategiesOutputFromJSONTyped,
    AdaptationStrategiesOutputToJSON,
} from './AdaptationStrategiesOutput';

/**
 * 
 * @export
 * @interface AdaptationResultSetOptionsOutput
 */
export interface AdaptationResultSetOptionsOutput {
    /**
     * 
     * @type {DamagesOptionsOutput}
     * @memberof AdaptationResultSetOptionsOutput
     */
    damagesOptions?: DamagesOptionsOutput;
    /**
     * 
     * @type {AdaptationStrategiesOutput}
     * @memberof AdaptationResultSetOptionsOutput
     */
    adaptationStrategies?: AdaptationStrategiesOutput;
    /**
     * 
     * @type {string}
     * @memberof AdaptationResultSetOptionsOutput
     */
    type?: string;
}

/**
 * Check if a given object implements the AdaptationResultSetOptionsOutput interface.
 */
export function instanceOfAdaptationResultSetOptionsOutput(value: object): value is AdaptationResultSetOptionsOutput {
    return true;
}

export function AdaptationResultSetOptionsOutputFromJSON(json: any): AdaptationResultSetOptionsOutput {
    return AdaptationResultSetOptionsOutputFromJSONTyped(json, false);
}

export function AdaptationResultSetOptionsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdaptationResultSetOptionsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'damagesOptions': json['damages_options'] == null ? undefined : DamagesOptionsOutputFromJSON(json['damages_options']),
        'adaptationStrategies': json['adaptation_strategies'] == null ? undefined : AdaptationStrategiesOutputFromJSON(json['adaptation_strategies']),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function AdaptationResultSetOptionsOutputToJSON(value?: AdaptationResultSetOptionsOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'damages_options': DamagesOptionsOutputToJSON(value['damagesOptions']),
        'adaptation_strategies': AdaptationStrategiesOutputToJSON(value['adaptationStrategies']),
        'type': value['type'],
    };
}

