/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AnalysisStatus = {
    pending: 'pending',
    ready: 'ready',
    rollback: 'rollback',
    unknownDefaultOpenApi: '11184809'
} as const;
export type AnalysisStatus = typeof AnalysisStatus[keyof typeof AnalysisStatus];


export function instanceOfAnalysisStatus(value: any): boolean {
    for (const key in AnalysisStatus) {
        if (Object.prototype.hasOwnProperty.call(AnalysisStatus, key)) {
            if ((AnalysisStatus as Record<string, AnalysisStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AnalysisStatusFromJSON(json: any): AnalysisStatus {
    return AnalysisStatusFromJSONTyped(json, false);
}

export function AnalysisStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalysisStatus {
    return json as AnalysisStatus;
}

export function AnalysisStatusToJSON(value?: AnalysisStatus | null): any {
    return value as any;
}

