/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalysisStatus } from './AnalysisStatus';
import {
    AnalysisStatusFromJSON,
    AnalysisStatusFromJSONTyped,
    AnalysisStatusToJSON,
} from './AnalysisStatus';
import type { AdaptationAnalysisSettings } from './AdaptationAnalysisSettings';
import {
    AdaptationAnalysisSettingsFromJSON,
    AdaptationAnalysisSettingsFromJSONTyped,
    AdaptationAnalysisSettingsToJSON,
} from './AdaptationAnalysisSettings';

/**
 * 
 * @export
 * @interface AnalysisUpdateSettingsRequest
 */
export interface AnalysisUpdateSettingsRequest {
    /**
     * 
     * @type {AdaptationAnalysisSettings}
     * @memberof AnalysisUpdateSettingsRequest
     */
    analysisSettings?: AdaptationAnalysisSettings | null;
    /**
     * 
     * @type {boolean}
     * @memberof AnalysisUpdateSettingsRequest
     */
    settingsConfirmed?: boolean | null;
    /**
     * 
     * @type {AnalysisStatus}
     * @memberof AnalysisUpdateSettingsRequest
     */
    status?: AnalysisStatus | null;
}

/**
 * Check if a given object implements the AnalysisUpdateSettingsRequest interface.
 */
export function instanceOfAnalysisUpdateSettingsRequest(value: object): value is AnalysisUpdateSettingsRequest {
    return true;
}

export function AnalysisUpdateSettingsRequestFromJSON(json: any): AnalysisUpdateSettingsRequest {
    return AnalysisUpdateSettingsRequestFromJSONTyped(json, false);
}

export function AnalysisUpdateSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalysisUpdateSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'analysisSettings': json['analysis_settings'] == null ? undefined : AdaptationAnalysisSettingsFromJSON(json['analysis_settings']),
        'settingsConfirmed': json['settings_confirmed'] == null ? undefined : json['settings_confirmed'],
        'status': json['status'] == null ? undefined : AnalysisStatusFromJSON(json['status']),
    };
}

export function AnalysisUpdateSettingsRequestToJSON(value?: AnalysisUpdateSettingsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'analysis_settings': AdaptationAnalysisSettingsToJSON(value['analysisSettings']),
        'settings_confirmed': value['settingsConfirmed'],
        'status': AnalysisStatusToJSON(value['status']),
    };
}

