/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFileLinkInput
 */
export interface CreateFileLinkInput {
    /**
     * 
     * @type {number}
     * @memberof CreateFileLinkInput
     */
    expiresIn?: number;
}

/**
 * Check if a given object implements the CreateFileLinkInput interface.
 */
export function instanceOfCreateFileLinkInput(value: object): value is CreateFileLinkInput {
    return true;
}

export function CreateFileLinkInputFromJSON(json: any): CreateFileLinkInput {
    return CreateFileLinkInputFromJSONTyped(json, false);
}

export function CreateFileLinkInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileLinkInput {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
    };
}

export function CreateFileLinkInputToJSON(value?: CreateFileLinkInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'expires_in': value['expiresIn'],
    };
}

