/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CSGCoordinates
 */
export interface CSGCoordinates {
    /**
     * 
     * @type {number}
     * @memberof CSGCoordinates
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof CSGCoordinates
     */
    latitude: number;
}

/**
 * Check if a given object implements the CSGCoordinates interface.
 */
export function instanceOfCSGCoordinates(value: object): value is CSGCoordinates {
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    return true;
}

export function CSGCoordinatesFromJSON(json: any): CSGCoordinates {
    return CSGCoordinatesFromJSONTyped(json, false);
}

export function CSGCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CSGCoordinates {
    if (json == null) {
        return json;
    }
    return {
        
        'longitude': json['longitude'],
        'latitude': json['latitude'],
    };
}

export function CSGCoordinatesToJSON(value?: CSGCoordinates | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'longitude': value['longitude'],
        'latitude': value['latitude'],
    };
}

