/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Identifiers for currency.
 * @export
 */
export const CurrencyCode = {
    aed: 'AED',
    afn: 'AFN',
    all: 'ALL',
    amd: 'AMD',
    ang: 'ANG',
    aoa: 'AOA',
    ars: 'ARS',
    aud: 'AUD',
    awg: 'AWG',
    azn: 'AZN',
    bam: 'BAM',
    bbd: 'BBD',
    bdt: 'BDT',
    bgn: 'BGN',
    bhd: 'BHD',
    bif: 'BIF',
    bmd: 'BMD',
    bnd: 'BND',
    bob: 'BOB',
    brl: 'BRL',
    bsd: 'BSD',
    btn: 'BTN',
    bwp: 'BWP',
    byn: 'BYN',
    bzd: 'BZD',
    cad: 'CAD',
    cdf: 'CDF',
    chf: 'CHF',
    clf: 'CLF',
    clp: 'CLP',
    cny: 'CNY',
    cop: 'COP',
    crc: 'CRC',
    cup: 'CUP',
    cve: 'CVE',
    czk: 'CZK',
    djf: 'DJF',
    dkk: 'DKK',
    dop: 'DOP',
    dzd: 'DZD',
    egp: 'EGP',
    ern: 'ERN',
    etb: 'ETB',
    eur: 'EUR',
    fjd: 'FJD',
    fkp: 'FKP',
    gbp: 'GBP',
    gel: 'GEL',
    ghs: 'GHS',
    gip: 'GIP',
    gmd: 'GMD',
    gnf: 'GNF',
    gtq: 'GTQ',
    gyd: 'GYD',
    hkd: 'HKD',
    hnl: 'HNL',
    htg: 'HTG',
    huf: 'HUF',
    idr: 'IDR',
    ils: 'ILS',
    inr: 'INR',
    iqd: 'IQD',
    irr: 'IRR',
    isk: 'ISK',
    jmd: 'JMD',
    jod: 'JOD',
    jpy: 'JPY',
    kes: 'KES',
    kgs: 'KGS',
    khr: 'KHR',
    kmf: 'KMF',
    kpw: 'KPW',
    krw: 'KRW',
    kwd: 'KWD',
    kyd: 'KYD',
    kzt: 'KZT',
    lak: 'LAK',
    lbp: 'LBP',
    lkr: 'LKR',
    lrd: 'LRD',
    lsl: 'LSL',
    lyd: 'LYD',
    mad: 'MAD',
    mdl: 'MDL',
    mga: 'MGA',
    mkd: 'MKD',
    mmk: 'MMK',
    mnt: 'MNT',
    mop: 'MOP',
    mru: 'MRU',
    mur: 'MUR',
    mvr: 'MVR',
    mwk: 'MWK',
    mxn: 'MXN',
    myr: 'MYR',
    mzn: 'MZN',
    nad: 'NAD',
    ngn: 'NGN',
    nio: 'NIO',
    nok: 'NOK',
    npr: 'NPR',
    nzd: 'NZD',
    omr: 'OMR',
    pab: 'PAB',
    pen: 'PEN',
    pgk: 'PGK',
    php: 'PHP',
    pkr: 'PKR',
    pln: 'PLN',
    pyg: 'PYG',
    qar: 'QAR',
    ron: 'RON',
    rsd: 'RSD',
    rub: 'RUB',
    rwf: 'RWF',
    sar: 'SAR',
    sbd: 'SBD',
    scr: 'SCR',
    sdg: 'SDG',
    sek: 'SEK',
    sgd: 'SGD',
    shp: 'SHP',
    sle: 'SLE',
    sll: 'SLL',
    sos: 'SOS',
    srd: 'SRD',
    ssp: 'SSP',
    stn: 'STN',
    svc: 'SVC',
    syp: 'SYP',
    szl: 'SZL',
    thb: 'THB',
    tjs: 'TJS',
    tmt: 'TMT',
    tnd: 'TND',
    top: 'TOP',
    try: 'TRY',
    ttd: 'TTD',
    twd: 'TWD',
    tzs: 'TZS',
    uah: 'UAH',
    ugx: 'UGX',
    usd: 'USD',
    uyu: 'UYU',
    uzs: 'UZS',
    ved: 'VED',
    ves: 'VES',
    vnd: 'VND',
    vuv: 'VUV',
    wst: 'WST',
    xaf: 'XAF',
    xcd: 'XCD',
    xof: 'XOF',
    xpf: 'XPF',
    yer: 'YER',
    zar: 'ZAR',
    zmw: 'ZMW',
    zwl: 'ZWL',
    unknownDefaultOpenApi: '11184809'
} as const;
export type CurrencyCode = typeof CurrencyCode[keyof typeof CurrencyCode];


export function instanceOfCurrencyCode(value: any): boolean {
    for (const key in CurrencyCode) {
        if (Object.prototype.hasOwnProperty.call(CurrencyCode, key)) {
            if ((CurrencyCode as Record<string, CurrencyCode>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CurrencyCodeFromJSON(json: any): CurrencyCode {
    return CurrencyCodeFromJSONTyped(json, false);
}

export function CurrencyCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyCode {
    return json as CurrencyCode;
}

export function CurrencyCodeToJSON(value?: CurrencyCode | null): any {
    return value as any;
}

