/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerilsOptionsOutput } from './PerilsOptionsOutput';
import {
    PerilsOptionsOutputFromJSON,
    PerilsOptionsOutputFromJSONTyped,
    PerilsOptionsOutputToJSON,
} from './PerilsOptionsOutput';
import type { APIEIModule } from './APIEIModule';
import {
    APIEIModuleFromJSON,
    APIEIModuleFromJSONTyped,
    APIEIModuleToJSON,
} from './APIEIModule';

/**
 * 
 * @export
 * @interface DamagesOptionsOutput
 */
export interface DamagesOptionsOutput {
    /**
     * 
     * @type {string}
     * @memberof DamagesOptionsOutput
     */
    eiVersion?: DamagesOptionsOutputEiVersionEnum | null;
    /**
     * 
     * @type {PerilsOptionsOutput}
     * @memberof DamagesOptionsOutput
     */
    perilsOptions?: PerilsOptionsOutput | null;
    /**
     * 
     * @type {Array<APIEIModule>}
     * @memberof DamagesOptionsOutput
     */
    eiModules?: Array<APIEIModule> | null;
    /**
     * 
     * @type {boolean}
     * @memberof DamagesOptionsOutput
     */
    windPeakGustAdjustment?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DamagesOptionsOutput
     */
    includePeakGustFactor?: boolean;
}


/**
 * @export
 */
export const DamagesOptionsOutputEiVersionEnum = {
    _262: '2.6.2',
    _300: '3.0.0',
    _310: '3.1.0',
    _311: '3.1.1',
    _312: '3.1.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type DamagesOptionsOutputEiVersionEnum = typeof DamagesOptionsOutputEiVersionEnum[keyof typeof DamagesOptionsOutputEiVersionEnum];


/**
 * Check if a given object implements the DamagesOptionsOutput interface.
 */
export function instanceOfDamagesOptionsOutput(value: object): value is DamagesOptionsOutput {
    return true;
}

export function DamagesOptionsOutputFromJSON(json: any): DamagesOptionsOutput {
    return DamagesOptionsOutputFromJSONTyped(json, false);
}

export function DamagesOptionsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DamagesOptionsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'eiVersion': json['ei_version'] == null ? undefined : json['ei_version'],
        'perilsOptions': json['perils_options'] == null ? undefined : PerilsOptionsOutputFromJSON(json['perils_options']),
        'eiModules': json['ei_modules'] == null ? undefined : ((json['ei_modules'] as Array<any>).map(APIEIModuleFromJSON)),
        'windPeakGustAdjustment': json['wind_peak_gust_adjustment'] == null ? undefined : json['wind_peak_gust_adjustment'],
        'includePeakGustFactor': json['include_peak_gust_factor'] == null ? undefined : json['include_peak_gust_factor'],
    };
}

export function DamagesOptionsOutputToJSON(value?: DamagesOptionsOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ei_version': value['eiVersion'],
        'perils_options': PerilsOptionsOutputToJSON(value['perilsOptions']),
        'ei_modules': value['eiModules'] == null ? undefined : ((value['eiModules'] as Array<any>).map(APIEIModuleToJSON)),
        'wind_peak_gust_adjustment': value['windPeakGustAdjustment'],
        'include_peak_gust_factor': value['includePeakGustFactor'],
    };
}

