/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LossAssetAttributes } from './LossAssetAttributes';
import {
    LossAssetAttributesFromJSON,
    LossAssetAttributesFromJSONTyped,
    LossAssetAttributesToJSON,
} from './LossAssetAttributes';
import type { APIEIModule } from './APIEIModule';
import {
    APIEIModuleFromJSON,
    APIEIModuleFromJSONTyped,
    APIEIModuleToJSON,
} from './APIEIModule';
import type { PerilsOptions } from './PerilsOptions';
import {
    PerilsOptionsFromJSON,
    PerilsOptionsFromJSONTyped,
    PerilsOptionsToJSON,
} from './PerilsOptions';

/**
 * 
 * @export
 * @interface DamagesResultSetOptionsBase
 */
export interface DamagesResultSetOptionsBase {
    /**
     * 
     * @type {string}
     * @memberof DamagesResultSetOptionsBase
     */
    eiVersion?: DamagesResultSetOptionsBaseEiVersionEnum;
    /**
     * 
     * @type {PerilsOptions}
     * @memberof DamagesResultSetOptionsBase
     */
    perilsOptions?: PerilsOptions;
    /**
     * 
     * @type {Array<APIEIModule>}
     * @memberof DamagesResultSetOptionsBase
     */
    eiModules?: Array<APIEIModule>;
    /**
     * 
     * @type {boolean}
     * @memberof DamagesResultSetOptionsBase
     */
    windPeakGustAdjustment?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DamagesResultSetOptionsBase
     */
    includePeakGustFactor?: boolean;
    /**
     * 
     * @type {LossAssetAttributes}
     * @memberof DamagesResultSetOptionsBase
     */
    defaults?: LossAssetAttributes;
}


/**
 * @export
 */
export const DamagesResultSetOptionsBaseEiVersionEnum = {
    _262: '2.6.2',
    _300: '3.0.0',
    _310: '3.1.0',
    _311: '3.1.1',
    _312: '3.1.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type DamagesResultSetOptionsBaseEiVersionEnum = typeof DamagesResultSetOptionsBaseEiVersionEnum[keyof typeof DamagesResultSetOptionsBaseEiVersionEnum];


/**
 * Check if a given object implements the DamagesResultSetOptionsBase interface.
 */
export function instanceOfDamagesResultSetOptionsBase(value: object): value is DamagesResultSetOptionsBase {
    return true;
}

export function DamagesResultSetOptionsBaseFromJSON(json: any): DamagesResultSetOptionsBase {
    return DamagesResultSetOptionsBaseFromJSONTyped(json, false);
}

export function DamagesResultSetOptionsBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DamagesResultSetOptionsBase {
    if (json == null) {
        return json;
    }
    return {
        
        'eiVersion': json['ei_version'] == null ? undefined : json['ei_version'],
        'perilsOptions': json['perils_options'] == null ? undefined : PerilsOptionsFromJSON(json['perils_options']),
        'eiModules': json['ei_modules'] == null ? undefined : ((json['ei_modules'] as Array<any>).map(APIEIModuleFromJSON)),
        'windPeakGustAdjustment': json['wind_peak_gust_adjustment'] == null ? undefined : json['wind_peak_gust_adjustment'],
        'includePeakGustFactor': json['include_peak_gust_factor'] == null ? undefined : json['include_peak_gust_factor'],
        'defaults': json['defaults'] == null ? undefined : LossAssetAttributesFromJSON(json['defaults']),
    };
}

export function DamagesResultSetOptionsBaseToJSON(value?: DamagesResultSetOptionsBase | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ei_version': value['eiVersion'],
        'perils_options': PerilsOptionsToJSON(value['perilsOptions']),
        'ei_modules': value['eiModules'] == null ? undefined : ((value['eiModules'] as Array<any>).map(APIEIModuleToJSON)),
        'wind_peak_gust_adjustment': value['windPeakGustAdjustment'],
        'include_peak_gust_factor': value['includePeakGustFactor'],
        'defaults': LossAssetAttributesToJSON(value['defaults']),
    };
}

