/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocsAIChatFeedbackInput
 */
export interface DocsAIChatFeedbackInput {
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatFeedbackInput
     */
    feedback?: string;
    /**
     * 
     * @type {number}
     * @memberof DocsAIChatFeedbackInput
     */
    thumbAction?: DocsAIChatFeedbackInputThumbActionEnum;
}


/**
 * @export
 */
export const DocsAIChatFeedbackInputThumbActionEnum = {
    NUMBER_MINUS_1: -1,
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type DocsAIChatFeedbackInputThumbActionEnum = typeof DocsAIChatFeedbackInputThumbActionEnum[keyof typeof DocsAIChatFeedbackInputThumbActionEnum];


/**
 * Check if a given object implements the DocsAIChatFeedbackInput interface.
 */
export function instanceOfDocsAIChatFeedbackInput(value: object): value is DocsAIChatFeedbackInput {
    return true;
}

export function DocsAIChatFeedbackInputFromJSON(json: any): DocsAIChatFeedbackInput {
    return DocsAIChatFeedbackInputFromJSONTyped(json, false);
}

export function DocsAIChatFeedbackInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocsAIChatFeedbackInput {
    if (json == null) {
        return json;
    }
    return {
        
        'feedback': json['feedback'] == null ? undefined : json['feedback'],
        'thumbAction': json['thumb_action'] == null ? undefined : json['thumb_action'],
    };
}

export function DocsAIChatFeedbackInputToJSON(value?: DocsAIChatFeedbackInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'feedback': value['feedback'],
        'thumb_action': value['thumbAction'],
    };
}

