/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocsAIChatAskChatRequest
 */
export interface DocsAIChatAskChatRequest {
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatAskChatRequest
     */
    question: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocsAIChatAskChatRequest
     */
    useHistory?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatAskChatRequest
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatAskChatRequest
     */
    modelName?: DocsAIChatAskChatRequestModelNameEnum;
}


/**
 * @export
 */
export const DocsAIChatAskChatRequestModelNameEnum = {
    mixtral8x7: 'mixtral-8x7',
    snowflakeArctic: 'snowflake-arctic',
    mistralLarge: 'mistral-large',
    llama38b: 'llama3-8b',
    llama370b: 'llama3-70b',
    rekaFlash: 'reka-flash',
    mistral7b: 'mistral-7b',
    llama270bChat: 'llama2-70b-chat',
    gemma7b: 'gemma-7b',
    unknownDefaultOpenApi: '11184809'
} as const;
export type DocsAIChatAskChatRequestModelNameEnum = typeof DocsAIChatAskChatRequestModelNameEnum[keyof typeof DocsAIChatAskChatRequestModelNameEnum];


/**
 * Check if a given object implements the DocsAIChatAskChatRequest interface.
 */
export function instanceOfDocsAIChatAskChatRequest(value: object): value is DocsAIChatAskChatRequest {
    if (!('question' in value) || value['question'] === undefined) return false;
    return true;
}

export function DocsAIChatAskChatRequestFromJSON(json: any): DocsAIChatAskChatRequest {
    return DocsAIChatAskChatRequestFromJSONTyped(json, false);
}

export function DocsAIChatAskChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocsAIChatAskChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'question': json['question'],
        'useHistory': json['use_history'] == null ? undefined : json['use_history'],
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
    };
}

export function DocsAIChatAskChatRequestToJSON(value?: DocsAIChatAskChatRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'question': value['question'],
        'use_history': value['useHistory'],
        'session_id': value['sessionId'],
        'model_name': value['modelName'],
    };
}

