/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocsAIChatOptionsSetModel } from './DocsAIChatOptionsSetModel';
import {
    DocsAIChatOptionsSetModelFromJSON,
    DocsAIChatOptionsSetModelFromJSONTyped,
    DocsAIChatOptionsSetModelToJSON,
} from './DocsAIChatOptionsSetModel';
import type { DocsAIChatFeedbackModel } from './DocsAIChatFeedbackModel';
import {
    DocsAIChatFeedbackModelFromJSON,
    DocsAIChatFeedbackModelFromJSONTyped,
    DocsAIChatFeedbackModelToJSON,
} from './DocsAIChatFeedbackModel';

/**
 * 
 * @export
 * @interface DocsAIChatConversationModel
 */
export interface DocsAIChatConversationModel {
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    questionId: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    question: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    answer: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    prompt?: string;
    /**
     * 
     * @type {Date}
     * @memberof DocsAIChatConversationModel
     */
    askedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocsAIChatConversationModel
     */
    respondedAt: Date;
    /**
     * 
     * @type {DocsAIChatFeedbackModel}
     * @memberof DocsAIChatConversationModel
     */
    feedback?: DocsAIChatFeedbackModel;
    /**
     * 
     * @type {DocsAIChatOptionsSetModel}
     * @memberof DocsAIChatConversationModel
     */
    optionsSet?: DocsAIChatOptionsSetModel;
    /**
     * 
     * @type {Date}
     * @memberof DocsAIChatConversationModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocsAIChatConversationModel
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof DocsAIChatConversationModel
     */
    updatedBy: string;
}

/**
 * Check if a given object implements the DocsAIChatConversationModel interface.
 */
export function instanceOfDocsAIChatConversationModel(value: object): value is DocsAIChatConversationModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('askedAt' in value) || value['askedAt'] === undefined) return false;
    if (!('respondedAt' in value) || value['respondedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    return true;
}

export function DocsAIChatConversationModelFromJSON(json: any): DocsAIChatConversationModel {
    return DocsAIChatConversationModelFromJSONTyped(json, false);
}

export function DocsAIChatConversationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocsAIChatConversationModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'customerId': json['customer_id'],
        'userId': json['user_id'],
        'sessionId': json['session_id'],
        'questionId': json['question_id'],
        'question': json['question'],
        'answer': json['answer'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'askedAt': (new Date(json['asked_at'])),
        'respondedAt': (new Date(json['responded_at'])),
        'feedback': json['feedback'] == null ? undefined : DocsAIChatFeedbackModelFromJSON(json['feedback']),
        'optionsSet': json['options_set'] == null ? undefined : DocsAIChatOptionsSetModelFromJSON(json['options_set']),
        'createdAt': (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
        'updatedAt': (isNaN(json['updated_at']) ? (new Date(json['updated_at'])) : (new Date(1000 * json['updated_at']))),
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
    };
}

export function DocsAIChatConversationModelToJSON(value?: DocsAIChatConversationModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'customer_id': value['customerId'],
        'user_id': value['userId'],
        'session_id': value['sessionId'],
        'question_id': value['questionId'],
        'question': value['question'],
        'answer': value['answer'],
        'prompt': value['prompt'],
        'asked_at': ((value['askedAt']).toISOString()),
        'responded_at': ((value['respondedAt']).toISOString()),
        'feedback': DocsAIChatFeedbackModelToJSON(value['feedback']),
        'options_set': DocsAIChatOptionsSetModelToJSON(value['optionsSet']),
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
    };
}

