/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EUHazardCode = {
    changingTemperatureAir: 'changing_temperature_air',
    changingTemperatureFreshwater: 'changing_temperature_freshwater',
    changingTemperatureMarine: 'changing_temperature_marine',
    heatStress: 'heat_stress',
    temperatureVariability: 'temperature_variability',
    permafrostThawing: 'permafrost_thawing',
    heatWave: 'heat_wave',
    coldWaveFrost: 'cold_wave_frost',
    wildfire: 'wildfire',
    changingWindPatterns: 'changing_wind_patterns',
    cyclonesHurricanesTyphoons: 'cyclones_hurricanes_typhoons',
    stormsBlizzards: 'storms_blizzards',
    stormsDustSandstorms: 'storms_dust_sandstorms',
    tornado: 'tornado',
    changingPrecipPatternsTypes: 'changing_precip_patterns_types',
    precipHydroVariability: 'precip_hydro_variability',
    oceanAcidification: 'ocean_acidification',
    salineIntrusion: 'saline_intrusion',
    seaLevelRise: 'sea_level_rise',
    waterStress: 'water_stress',
    drought: 'drought',
    heavyPrecip: 'heavy_precip',
    flood: 'flood',
    floodGroundwater: 'flood_groundwater',
    glacialLakeOutburst: 'glacial_lake_outburst',
    coastalErosion: 'coastal_erosion',
    soilDegradation: 'soil_degradation',
    soilErosion: 'soil_erosion',
    solifluction: 'solifluction',
    avalanche: 'avalanche',
    landslide: 'landslide',
    subsidence: 'subsidence',
    unknownDefaultOpenApi: '11184809'
} as const;
export type EUHazardCode = typeof EUHazardCode[keyof typeof EUHazardCode];


export function instanceOfEUHazardCode(value: any): boolean {
    for (const key in EUHazardCode) {
        if (Object.prototype.hasOwnProperty.call(EUHazardCode, key)) {
            if ((EUHazardCode as Record<string, EUHazardCode>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EUHazardCodeFromJSON(json: any): EUHazardCode {
    return EUHazardCodeFromJSONTyped(json, false);
}

export function EUHazardCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EUHazardCode {
    return json as EUHazardCode;
}

export function EUHazardCodeToJSON(value?: EUHazardCode | null): any {
    return value as any;
}

