/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const ExportStatus = {
    pending: 'pending',
    completed: 'completed',
    failed: 'failed',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ExportStatus = typeof ExportStatus[keyof typeof ExportStatus];


export function instanceOfExportStatus(value: any): boolean {
    for (const key in ExportStatus) {
        if (Object.prototype.hasOwnProperty.call(ExportStatus, key)) {
            if ((ExportStatus as Record<string, ExportStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExportStatusFromJSON(json: any): ExportStatus {
    return ExportStatusFromJSONTyped(json, false);
}

export function ExportStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportStatus {
    return json as ExportStatus;
}

export function ExportStatusToJSON(value?: ExportStatus | null): any {
    return value as any;
}

