/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Options2 } from './Options2';
import {
    Options2FromJSON,
    Options2FromJSONTyped,
    Options2ToJSON,
} from './Options2';
import type { Compression } from './Compression';
import {
    CompressionFromJSON,
    CompressionFromJSONTyped,
    CompressionToJSON,
} from './Compression';
import type { FileType } from './FileType';
import {
    FileTypeFromJSON,
    FileTypeFromJSONTyped,
    FileTypeToJSON,
} from './FileType';
import type { OutputStyle } from './OutputStyle';
import {
    OutputStyleFromJSON,
    OutputStyleFromJSONTyped,
    OutputStyleToJSON,
} from './OutputStyle';

/**
 * 
 * @export
 * @interface ExportOptionsMixin
 */
export interface ExportOptionsMixin {
    /**
     * 
     * @type {Options2}
     * @memberof ExportOptionsMixin
     */
    options: Options2;
    /**
     * 
     * @type {OutputStyle}
     * @memberof ExportOptionsMixin
     */
    outputStyle?: OutputStyle;
    /**
     * 
     * @type {FileType}
     * @memberof ExportOptionsMixin
     */
    fileType?: FileType;
    /**
     * 
     * @type {Compression}
     * @memberof ExportOptionsMixin
     */
    compression?: Compression;
}

/**
 * Check if a given object implements the ExportOptionsMixin interface.
 */
export function instanceOfExportOptionsMixin(value: object): value is ExportOptionsMixin {
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function ExportOptionsMixinFromJSON(json: any): ExportOptionsMixin {
    return ExportOptionsMixinFromJSONTyped(json, false);
}

export function ExportOptionsMixinFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportOptionsMixin {
    if (json == null) {
        return json;
    }
    return {
        
        'options': Options2FromJSON(json['options']),
        'outputStyle': json['output_style'] == null ? undefined : OutputStyleFromJSON(json['output_style']),
        'fileType': json['file_type'] == null ? undefined : FileTypeFromJSON(json['file_type']),
        'compression': json['compression'] == null ? undefined : CompressionFromJSON(json['compression']),
    };
}

export function ExportOptionsMixinToJSON(value?: ExportOptionsMixin | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'options': Options2ToJSON(value['options']),
        'output_style': OutputStyleToJSON(value['outputStyle']),
        'file_type': FileTypeToJSON(value['fileType']),
        'compression': CompressionToJSON(value['compression']),
    };
}

