/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilePurpose } from './FilePurpose';
import {
    FilePurposeFromJSON,
    FilePurposeFromJSONTyped,
    FilePurposeToJSON,
} from './FilePurpose';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
} from './Metadata';
import type { JupiterApiFileSchemasFileType } from './JupiterApiFileSchemasFileType';
import {
    JupiterApiFileSchemasFileTypeFromJSON,
    JupiterApiFileSchemasFileTypeFromJSONTyped,
    JupiterApiFileSchemasFileTypeToJSON,
} from './JupiterApiFileSchemasFileType';

/**
 * 
 * @export
 * @interface FileResponse
 */
export interface FileResponse {
    /**
     * 
     * @type {string}
     * @memberof FileResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FileResponse
     */
    filename: string;
    /**
     * 
     * @type {FilePurpose}
     * @memberof FileResponse
     */
    purpose: FilePurpose;
    /**
     * 
     * @type {JupiterApiFileSchemasFileType}
     * @memberof FileResponse
     */
    type: JupiterApiFileSchemasFileType;
    /**
     * 
     * @type {number}
     * @memberof FileResponse
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof FileResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileResponse
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof FileResponse
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof FileResponse
     */
    updatedBy: string;
    /**
     * 
     * @type {Metadata}
     * @memberof FileResponse
     */
    metadata?: Metadata;
}

/**
 * Check if a given object implements the FileResponse interface.
 */
export function instanceOfFileResponse(value: object): value is FileResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    return true;
}

export function FileResponseFromJSON(json: any): FileResponse {
    return FileResponseFromJSONTyped(json, false);
}

export function FileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'filename': json['filename'],
        'purpose': FilePurposeFromJSON(json['purpose']),
        'type': JupiterApiFileSchemasFileTypeFromJSON(json['type']),
        'size': json['size'],
        'createdAt': (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
        'updatedAt': (isNaN(json['updated_at']) ? (new Date(json['updated_at'])) : (new Date(1000 * json['updated_at']))),
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'metadata': json['metadata_'] == null ? undefined : MetadataFromJSON(json['metadata_']),
    };
}

export function FileResponseToJSON(value?: FileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'filename': value['filename'],
        'purpose': FilePurposeToJSON(value['purpose']),
        'type': JupiterApiFileSchemasFileTypeToJSON(value['type']),
        'size': value['size'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
        'metadata_': MetadataToJSON(value['metadata']),
    };
}

