/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileValidationMessageStatus } from './FileValidationMessageStatus';
import {
    FileValidationMessageStatusFromJSON,
    FileValidationMessageStatusFromJSONTyped,
    FileValidationMessageStatusToJSON,
} from './FileValidationMessageStatus';
import type { ValidationMessageResponse } from './ValidationMessageResponse';
import {
    ValidationMessageResponseFromJSON,
    ValidationMessageResponseFromJSONTyped,
    ValidationMessageResponseToJSON,
} from './ValidationMessageResponse';

/**
 * 
 * @export
 * @interface FileValidationLocationMessageResponse
 */
export interface FileValidationLocationMessageResponse {
    /**
     * 
     * @type {Array<ValidationMessageResponse>}
     * @memberof FileValidationLocationMessageResponse
     */
    messages?: Array<ValidationMessageResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof FileValidationLocationMessageResponse
     */
    customerLocationId: number;
    /**
     * 
     * @type {FileValidationMessageStatus}
     * @memberof FileValidationLocationMessageResponse
     */
    validationStatus: FileValidationMessageStatus | null;
}

/**
 * Check if a given object implements the FileValidationLocationMessageResponse interface.
 */
export function instanceOfFileValidationLocationMessageResponse(value: object): value is FileValidationLocationMessageResponse {
    if (!('customerLocationId' in value) || value['customerLocationId'] === undefined) return false;
    if (!('validationStatus' in value) || value['validationStatus'] === undefined) return false;
    return true;
}

export function FileValidationLocationMessageResponseFromJSON(json: any): FileValidationLocationMessageResponse {
    return FileValidationLocationMessageResponseFromJSONTyped(json, false);
}

export function FileValidationLocationMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileValidationLocationMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(ValidationMessageResponseFromJSON)),
        'customerLocationId': json['customer_location_id'],
        'validationStatus': FileValidationMessageStatusFromJSON(json['validation_status']),
    };
}

export function FileValidationLocationMessageResponseToJSON(value?: FileValidationLocationMessageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(ValidationMessageResponseToJSON)),
        'customer_location_id': value['customerLocationId'],
        'validation_status': FileValidationMessageStatusToJSON(value['validationStatus']),
    };
}

