/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JupiterApiExportSchemasFileType } from './JupiterApiExportSchemasFileType';
import {
    JupiterApiExportSchemasFileTypeFromJSON,
    JupiterApiExportSchemasFileTypeFromJSONTyped,
    JupiterApiExportSchemasFileTypeToJSON,
} from './JupiterApiExportSchemasFileType';
import type { DocumentFileType } from './DocumentFileType';
import {
    DocumentFileTypeFromJSON,
    DocumentFileTypeFromJSONTyped,
    DocumentFileTypeToJSON,
} from './DocumentFileType';

/**
 * 
 * @export
 * @interface FileType
 */
export interface FileType {
}

/**
 * Check if a given object implements the FileType interface.
 */
export function instanceOfFileType(value: object): value is FileType {
    return true;
}

export function FileTypeFromJSON(json: any): FileType {
    return FileTypeFromJSONTyped(json, false);
}

export function FileTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileType {
    return json;
}

export function FileTypeToJSON(value?: FileType | null): any {
    return value;
}

