/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Filters
 */
export interface Filters {
}

/**
 * Check if a given object implements the Filters interface.
 */
export function instanceOfFilters(value: object): value is Filters {
    return true;
}

export function FiltersFromJSON(json: any): Filters {
    return FiltersFromJSONTyped(json, false);
}

export function FiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Filters {
    return json;
}

export function FiltersToJSON(value?: Filters | null): any {
    return value;
}

