/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FloodDefenseOutput
 */
export interface FloodDefenseOutput {
    /**
     * 
     * @type {boolean}
     * @memberof FloodDefenseOutput
     */
    isDefended?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FloodDefenseOutput
     */
    maxDefendedReturnPeriod?: number;
}

/**
 * Check if a given object implements the FloodDefenseOutput interface.
 */
export function instanceOfFloodDefenseOutput(value: object): value is FloodDefenseOutput {
    return true;
}

export function FloodDefenseOutputFromJSON(json: any): FloodDefenseOutput {
    return FloodDefenseOutputFromJSONTyped(json, false);
}

export function FloodDefenseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FloodDefenseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'isDefended': json['is_defended'] == null ? undefined : json['is_defended'],
        'maxDefendedReturnPeriod': json['max_defended_return_period'] == null ? undefined : json['max_defended_return_period'],
    };
}

export function FloodDefenseOutputToJSON(value?: FloodDefenseOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'is_defended': value['isDefended'],
        'max_defended_return_period': value['maxDefendedReturnPeriod'],
    };
}

