/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Options } from './Options';
import {
    OptionsFromJSON,
    OptionsFromJSONTyped,
    OptionsToJSON,
} from './Options';

/**
 * 
 * @export
 * @interface FloodDefenseParameterOptions
 */
export interface FloodDefenseParameterOptions {
    /**
     * 
     * @type {Options}
     * @memberof FloodDefenseParameterOptions
     */
    enabled: Options;
    /**
     * 
     * @type {Options}
     * @memberof FloodDefenseParameterOptions
     */
    zeroOutDefendedLocations: Options;
}

/**
 * Check if a given object implements the FloodDefenseParameterOptions interface.
 */
export function instanceOfFloodDefenseParameterOptions(value: object): value is FloodDefenseParameterOptions {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('zeroOutDefendedLocations' in value) || value['zeroOutDefendedLocations'] === undefined) return false;
    return true;
}

export function FloodDefenseParameterOptionsFromJSON(json: any): FloodDefenseParameterOptions {
    return FloodDefenseParameterOptionsFromJSONTyped(json, false);
}

export function FloodDefenseParameterOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FloodDefenseParameterOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': OptionsFromJSON(json['enabled']),
        'zeroOutDefendedLocations': OptionsFromJSON(json['zero_out_defended_locations']),
    };
}

export function FloodDefenseParameterOptionsToJSON(value?: FloodDefenseParameterOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enabled': OptionsToJSON(value['enabled']),
        'zero_out_defended_locations': OptionsToJSON(value['zeroOutDefendedLocations']),
    };
}

