/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Categorize geocode API responses and match with appropriate log messages
 * @export
 */
export const GeocodeStatus = {
    _40anApiErrorOrUnexpectedResultOccurred: '[40, An API error or unexpected result occurred]',
    _30noMatchWasFound: '[30, No match was found]',
    _30singlePartialMatchFound: '[30, Single partial match found]',
    _30multiplePartialMatchesFoundUsingFirst: '[30, Multiple partial matches found; using first]',
    _10fullMatchWasFound: '[10, Full match was found]',
    _10rowNotCheckedDueToExistingLatLon: '[10, Row not checked due to existing lat/lon]',
    unknownDefaultOpenApi: '11184809'
} as const;
export type GeocodeStatus = typeof GeocodeStatus[keyof typeof GeocodeStatus];


export function instanceOfGeocodeStatus(value: any): boolean {
    for (const key in GeocodeStatus) {
        if (Object.prototype.hasOwnProperty.call(GeocodeStatus, key)) {
            if ((GeocodeStatus as Record<string, GeocodeStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GeocodeStatusFromJSON(json: any): GeocodeStatus {
    return GeocodeStatusFromJSONTyped(json, false);
}

export function GeocodeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeocodeStatus {
    return json as GeocodeStatus;
}

export function GeocodeStatusToJSON(value?: GeocodeStatus | null): any {
    return value as any;
}

