/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MinimizedMessageInner } from './MinimizedMessageInner';
import {
    MinimizedMessageInnerFromJSON,
    MinimizedMessageInnerFromJSONTyped,
    MinimizedMessageInnerToJSON,
} from './MinimizedMessageInner';
import type { GeocodeLocationMessageStatus } from './GeocodeLocationMessageStatus';
import {
    GeocodeLocationMessageStatusFromJSON,
    GeocodeLocationMessageStatusFromJSONTyped,
    GeocodeLocationMessageStatusToJSON,
} from './GeocodeLocationMessageStatus';

/**
 * 
 * @export
 * @interface GeocodeLocationStatus
 */
export interface GeocodeLocationStatus {
    /**
     * 
     * @type {GeocodeLocationMessageStatus}
     * @memberof GeocodeLocationStatus
     */
    validationStatus: GeocodeLocationMessageStatus | null;
    /**
     * 
     * @type {Array<Array<MinimizedMessageInner>>}
     * @memberof GeocodeLocationStatus
     */
    minimizedMessages: Array<Array<MinimizedMessageInner>>;
}

/**
 * Check if a given object implements the GeocodeLocationStatus interface.
 */
export function instanceOfGeocodeLocationStatus(value: object): value is GeocodeLocationStatus {
    if (!('validationStatus' in value) || value['validationStatus'] === undefined) return false;
    if (!('minimizedMessages' in value) || value['minimizedMessages'] === undefined) return false;
    return true;
}

export function GeocodeLocationStatusFromJSON(json: any): GeocodeLocationStatus {
    return GeocodeLocationStatusFromJSONTyped(json, false);
}

export function GeocodeLocationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeocodeLocationStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'validationStatus': GeocodeLocationMessageStatusFromJSON(json['validation_status']),
        'minimizedMessages': json['minimized_messages'],
    };
}

export function GeocodeLocationStatusToJSON(value?: GeocodeLocationStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'validation_status': GeocodeLocationMessageStatusToJSON(value['validationStatus']),
        'minimized_messages': value['minimizedMessages'],
    };
}

