/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIEIModule } from './APIEIModule';
import {
    APIEIModuleFromJSON,
    APIEIModuleFromJSONTyped,
    APIEIModuleToJSON,
} from './APIEIModule';

/**
 * 
 * @export
 * @interface ImpactsQueryOptionsInput
 */
export interface ImpactsQueryOptionsInput {
    /**
     * 
     * @type {string}
     * @memberof ImpactsQueryOptionsInput
     */
    eiVersion?: ImpactsQueryOptionsInputEiVersionEnum | null;
    /**
     * 
     * @type {}
     * @memberof ImpactsQueryOptionsInput
     */
    perilsOptions?:  | null;
    /**
     * 
     * @type {Array<APIEIModule>}
     * @memberof ImpactsQueryOptionsInput
     */
    eiModules?: Array<APIEIModule> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ImpactsQueryOptionsInput
     */
    windPeakGustAdjustment?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ImpactsQueryOptionsInput
     */
    includePeakGustFactor?: boolean;
    /**
     * 
     * @type {}
     * @memberof ImpactsQueryOptionsInput
     */
    assetAttributes?:  | null;
}


/**
 * @export
 */
export const ImpactsQueryOptionsInputEiVersionEnum = {
    _262: '2.6.2',
    _300: '3.0.0',
    _310: '3.1.0',
    _311: '3.1.1',
    _312: '3.1.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ImpactsQueryOptionsInputEiVersionEnum = typeof ImpactsQueryOptionsInputEiVersionEnum[keyof typeof ImpactsQueryOptionsInputEiVersionEnum];


/**
 * Check if a given object implements the ImpactsQueryOptionsInput interface.
 */
export function instanceOfImpactsQueryOptionsInput(value: object): value is ImpactsQueryOptionsInput {
    return true;
}

export function ImpactsQueryOptionsInputFromJSON(json: any): ImpactsQueryOptionsInput {
    return ImpactsQueryOptionsInputFromJSONTyped(json, false);
}

export function ImpactsQueryOptionsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactsQueryOptionsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'eiVersion': json['ei_version'] == null ? undefined : json['ei_version'],
        'perilsOptions': json['perils_options'] == null ? undefined : FromJSON(json['perils_options']),
        'eiModules': json['ei_modules'] == null ? undefined : ((json['ei_modules'] as Array<any>).map(APIEIModuleFromJSON)),
        'windPeakGustAdjustment': json['wind_peak_gust_adjustment'] == null ? undefined : json['wind_peak_gust_adjustment'],
        'includePeakGustFactor': json['include_peak_gust_factor'] == null ? undefined : json['include_peak_gust_factor'],
        'assetAttributes': json['asset_attributes'] == null ? undefined : FromJSON(json['asset_attributes']),
    };
}

export function ImpactsQueryOptionsInputToJSON(value?: ImpactsQueryOptionsInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ei_version': value['eiVersion'],
        'perils_options': ToJSON(value['perilsOptions']),
        'ei_modules': value['eiModules'] == null ? undefined : ((value['eiModules'] as Array<any>).map(APIEIModuleToJSON)),
        'wind_peak_gust_adjustment': value['windPeakGustAdjustment'],
        'include_peak_gust_factor': value['includePeakGustFactor'],
        'asset_attributes': ToJSON(value['assetAttributes']),
    };
}

