/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImpactsQueryOptions } from './ImpactsQueryOptions';
import {
    ImpactsQueryOptionsFromJSON,
    ImpactsQueryOptionsFromJSONTyped,
    ImpactsQueryOptionsToJSON,
} from './ImpactsQueryOptions';
import type { GeocodingInput } from './GeocodingInput';
import {
    GeocodingInputFromJSON,
    GeocodingInputFromJSONTyped,
    GeocodingInputToJSON,
} from './GeocodingInput';
import type { CSGCoordinates } from './CSGCoordinates';
import {
    CSGCoordinatesFromJSON,
    CSGCoordinatesFromJSONTyped,
    CSGCoordinatesToJSON,
} from './CSGCoordinates';

/**
 * 
 * @export
 * @interface ImpactsQueryInput
 */
export interface ImpactsQueryInput {
    /**
     * 
     * @type {CSGCoordinates}
     * @memberof ImpactsQueryInput
     */
    location?: CSGCoordinates;
    /**
     * 
     * @type {GeocodingInput}
     * @memberof ImpactsQueryInput
     */
    geocodingInput?: GeocodingInput;
    /**
     * 
     * @type {ImpactsQueryOptions}
     * @memberof ImpactsQueryInput
     */
    options?: ImpactsQueryOptions;
}

/**
 * Check if a given object implements the ImpactsQueryInput interface.
 */
export function instanceOfImpactsQueryInput(value: object): value is ImpactsQueryInput {
    return true;
}

export function ImpactsQueryInputFromJSON(json: any): ImpactsQueryInput {
    return ImpactsQueryInputFromJSONTyped(json, false);
}

export function ImpactsQueryInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactsQueryInput {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['location'] == null ? undefined : CSGCoordinatesFromJSON(json['location']),
        'geocodingInput': json['geocoding_input'] == null ? undefined : GeocodingInputFromJSON(json['geocoding_input']),
        'options': json['options'] == null ? undefined : ImpactsQueryOptionsFromJSON(json['options']),
    };
}

export function ImpactsQueryInputToJSON(value?: ImpactsQueryInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'location': CSGCoordinatesToJSON(value['location']),
        'geocoding_input': GeocodingInputToJSON(value['geocodingInput']),
        'options': ImpactsQueryOptionsToJSON(value['options']),
    };
}

