/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const JupiterApiFileSchemasFileType = {
    csv: 'csv',
    parquet: 'parquet',
    unknownDefaultOpenApi: '11184809'
} as const;
export type JupiterApiFileSchemasFileType = typeof JupiterApiFileSchemasFileType[keyof typeof JupiterApiFileSchemasFileType];


export function instanceOfJupiterApiFileSchemasFileType(value: any): boolean {
    for (const key in JupiterApiFileSchemasFileType) {
        if (Object.prototype.hasOwnProperty.call(JupiterApiFileSchemasFileType, key)) {
            if ((JupiterApiFileSchemasFileType as Record<string, JupiterApiFileSchemasFileType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JupiterApiFileSchemasFileTypeFromJSON(json: any): JupiterApiFileSchemasFileType {
    return JupiterApiFileSchemasFileTypeFromJSONTyped(json, false);
}

export function JupiterApiFileSchemasFileTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JupiterApiFileSchemasFileType {
    return json as JupiterApiFileSchemasFileType;
}

export function JupiterApiFileSchemasFileTypeToJSON(value?: JupiterApiFileSchemasFileType | null): any {
    return value as any;
}

