/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JupiterTemplateColorCoding } from './JupiterTemplateColorCoding';
import {
    JupiterTemplateColorCodingFromJSON,
    JupiterTemplateColorCodingFromJSONTyped,
    JupiterTemplateColorCodingToJSON,
} from './JupiterTemplateColorCoding';
import type { JupiterTemplateType } from './JupiterTemplateType';
import {
    JupiterTemplateTypeFromJSON,
    JupiterTemplateTypeFromJSONTyped,
    JupiterTemplateTypeToJSON,
} from './JupiterTemplateType';
import type { JupiterTemplateScenario } from './JupiterTemplateScenario';
import {
    JupiterTemplateScenarioFromJSON,
    JupiterTemplateScenarioFromJSONTyped,
    JupiterTemplateScenarioToJSON,
} from './JupiterTemplateScenario';

/**
 * 
 * @export
 * @interface JupiterTemplateModel
 */
export interface JupiterTemplateModel {
    /**
     * 
     * @type {JupiterTemplateType}
     * @memberof JupiterTemplateModel
     */
    type: JupiterTemplateType;
    /**
     * 
     * @type {JupiterTemplateScenario}
     * @memberof JupiterTemplateModel
     */
    scenario: JupiterTemplateScenario;
    /**
     * 
     * @type {JupiterTemplateColorCoding}
     * @memberof JupiterTemplateModel
     */
    colorCoding: JupiterTemplateColorCoding;
    /**
     * 
     * @type {string}
     * @memberof JupiterTemplateModel
     */
    csgVersion: JupiterTemplateModelCsgVersionEnum;
}


/**
 * @export
 */
export const JupiterTemplateModelCsgVersionEnum = {
    _1: '3.1',
    _0: '3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type JupiterTemplateModelCsgVersionEnum = typeof JupiterTemplateModelCsgVersionEnum[keyof typeof JupiterTemplateModelCsgVersionEnum];


/**
 * Check if a given object implements the JupiterTemplateModel interface.
 */
export function instanceOfJupiterTemplateModel(value: object): value is JupiterTemplateModel {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('scenario' in value) || value['scenario'] === undefined) return false;
    if (!('colorCoding' in value) || value['colorCoding'] === undefined) return false;
    if (!('csgVersion' in value) || value['csgVersion'] === undefined) return false;
    return true;
}

export function JupiterTemplateModelFromJSON(json: any): JupiterTemplateModel {
    return JupiterTemplateModelFromJSONTyped(json, false);
}

export function JupiterTemplateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JupiterTemplateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': JupiterTemplateTypeFromJSON(json['type']),
        'scenario': JupiterTemplateScenarioFromJSON(json['scenario']),
        'colorCoding': JupiterTemplateColorCodingFromJSON(json['color_coding']),
        'csgVersion': json['csg_version'],
    };
}

export function JupiterTemplateModelToJSON(value?: JupiterTemplateModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': JupiterTemplateTypeToJSON(value['type']),
        'scenario': JupiterTemplateScenarioToJSON(value['scenario']),
        'color_coding': JupiterTemplateColorCodingToJSON(value['colorCoding']),
        'csg_version': value['csgVersion'],
    };
}

