/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JupiterTemplateColorCoding } from './JupiterTemplateColorCoding';
import {
    JupiterTemplateColorCodingFromJSON,
    JupiterTemplateColorCodingFromJSONTyped,
    JupiterTemplateColorCodingToJSON,
} from './JupiterTemplateColorCoding';
import type { JupiterTemplateType } from './JupiterTemplateType';
import {
    JupiterTemplateTypeFromJSON,
    JupiterTemplateTypeFromJSONTyped,
    JupiterTemplateTypeToJSON,
} from './JupiterTemplateType';
import type { JupiterTemplateScenario } from './JupiterTemplateScenario';
import {
    JupiterTemplateScenarioFromJSON,
    JupiterTemplateScenarioFromJSONTyped,
    JupiterTemplateScenarioToJSON,
} from './JupiterTemplateScenario';

/**
 * The input does not contain the CSG version as we don't want the user to be able to specify a version mismatch.
 * Version is derived from the result set.
 * @export
 * @interface JupiterTemplateInput
 */
export interface JupiterTemplateInput {
    /**
     * 
     * @type {JupiterTemplateType}
     * @memberof JupiterTemplateInput
     */
    type: JupiterTemplateType;
    /**
     * 
     * @type {JupiterTemplateScenario}
     * @memberof JupiterTemplateInput
     */
    scenario?: JupiterTemplateScenario;
    /**
     * 
     * @type {JupiterTemplateColorCoding}
     * @memberof JupiterTemplateInput
     */
    colorCoding?: JupiterTemplateColorCoding;
}

/**
 * Check if a given object implements the JupiterTemplateInput interface.
 */
export function instanceOfJupiterTemplateInput(value: object): value is JupiterTemplateInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function JupiterTemplateInputFromJSON(json: any): JupiterTemplateInput {
    return JupiterTemplateInputFromJSONTyped(json, false);
}

export function JupiterTemplateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): JupiterTemplateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': JupiterTemplateTypeFromJSON(json['type']),
        'scenario': json['scenario'] == null ? undefined : JupiterTemplateScenarioFromJSON(json['scenario']),
        'colorCoding': json['color_coding'] == null ? undefined : JupiterTemplateColorCodingFromJSON(json['color_coding']),
    };
}

export function JupiterTemplateInputToJSON(value?: JupiterTemplateInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': JupiterTemplateTypeToJSON(value['type']),
        'scenario': JupiterTemplateScenarioToJSON(value['scenario']),
        'color_coding': JupiterTemplateColorCodingToJSON(value['colorCoding']),
    };
}

