/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocsAIChatConversationModel } from './DocsAIChatConversationModel';
import {
    DocsAIChatConversationModelFromJSON,
    DocsAIChatConversationModelFromJSONTyped,
    DocsAIChatConversationModelToJSON,
} from './DocsAIChatConversationModel';

/**
 * 
 * @export
 * @interface ListDocsAIChatConversationResponse
 */
export interface ListDocsAIChatConversationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListDocsAIChatConversationResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<DocsAIChatConversationModel>}
     * @memberof ListDocsAIChatConversationResponse
     */
    data: Array<DocsAIChatConversationModel>;
}

/**
 * Check if a given object implements the ListDocsAIChatConversationResponse interface.
 */
export function instanceOfListDocsAIChatConversationResponse(value: object): value is ListDocsAIChatConversationResponse {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListDocsAIChatConversationResponseFromJSON(json: any): ListDocsAIChatConversationResponse {
    return ListDocsAIChatConversationResponseFromJSONTyped(json, false);
}

export function ListDocsAIChatConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDocsAIChatConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'data': ((json['data'] as Array<any>).map(DocsAIChatConversationModelFromJSON)),
    };
}

export function ListDocsAIChatConversationResponseToJSON(value?: ListDocsAIChatConversationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_more': value['hasMore'],
        'data': ((value['data'] as Array<any>).map(DocsAIChatConversationModelToJSON)),
    };
}

