/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExportOutput } from './ExportOutput';
import {
    ExportOutputFromJSON,
    ExportOutputFromJSONTyped,
    ExportOutputToJSON,
} from './ExportOutput';

/**
 * 
 * @export
 * @interface ListExportsResponse
 */
export interface ListExportsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListExportsResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<ExportOutput>}
     * @memberof ListExportsResponse
     */
    data: Array<ExportOutput>;
}

/**
 * Check if a given object implements the ListExportsResponse interface.
 */
export function instanceOfListExportsResponse(value: object): value is ListExportsResponse {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListExportsResponseFromJSON(json: any): ListExportsResponse {
    return ListExportsResponseFromJSONTyped(json, false);
}

export function ListExportsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListExportsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'data': ((json['data'] as Array<any>).map(ExportOutputFromJSON)),
    };
}

export function ListExportsResponseToJSON(value?: ListExportsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_more': value['hasMore'],
        'data': ((value['data'] as Array<any>).map(ExportOutputToJSON)),
    };
}

