/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ListingMode = {
    owner: 'owner',
    shared: 'shared',
    tenant: 'tenant',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListingMode = typeof ListingMode[keyof typeof ListingMode];


export function instanceOfListingMode(value: any): boolean {
    for (const key in ListingMode) {
        if (Object.prototype.hasOwnProperty.call(ListingMode, key)) {
            if ((ListingMode as Record<string, ListingMode>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ListingModeFromJSON(json: any): ListingMode {
    return ListingModeFromJSONTyped(json, false);
}

export function ListingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingMode {
    return json as ListingMode;
}

export function ListingModeToJSON(value?: ListingMode | null): any {
    return value as any;
}

