/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultSetResponse } from './ResultSetResponse';
import {
    ResultSetResponseFromJSON,
    ResultSetResponseFromJSONTyped,
    ResultSetResponseToJSON,
} from './ResultSetResponse';

/**
 * 
 * @export
 * @interface ListResultSetsResponse
 */
export interface ListResultSetsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListResultSetsResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<ResultSetResponse>}
     * @memberof ListResultSetsResponse
     */
    data: Array<ResultSetResponse>;
}

/**
 * Check if a given object implements the ListResultSetsResponse interface.
 */
export function instanceOfListResultSetsResponse(value: object): value is ListResultSetsResponse {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListResultSetsResponseFromJSON(json: any): ListResultSetsResponse {
    return ListResultSetsResponseFromJSONTyped(json, false);
}

export function ListResultSetsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultSetsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'data': ((json['data'] as Array<any>).map(ResultSetResponseFromJSON)),
    };
}

export function ListResultSetsResponseToJSON(value?: ListResultSetsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_more': value['hasMore'],
        'data': ((value['data'] as Array<any>).map(ResultSetResponseToJSON)),
    };
}

