/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortfolioResponse } from './PortfolioResponse';
import {
    PortfolioResponseFromJSON,
    PortfolioResponseFromJSONTyped,
    PortfolioResponseToJSON,
} from './PortfolioResponse';

/**
 * 
 * @export
 * @interface ListPortfoliosResponse
 */
export interface ListPortfoliosResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListPortfoliosResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<PortfolioResponse>}
     * @memberof ListPortfoliosResponse
     */
    data: Array<PortfolioResponse>;
}

/**
 * Check if a given object implements the ListPortfoliosResponse interface.
 */
export function instanceOfListPortfoliosResponse(value: object): value is ListPortfoliosResponse {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListPortfoliosResponseFromJSON(json: any): ListPortfoliosResponse {
    return ListPortfoliosResponseFromJSONTyped(json, false);
}

export function ListPortfoliosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPortfoliosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'data': ((json['data'] as Array<any>).map(PortfolioResponseFromJSON)),
    };
}

export function ListPortfoliosResponseToJSON(value?: ListPortfoliosResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_more': value['hasMore'],
        'data': ((value['data'] as Array<any>).map(PortfolioResponseToJSON)),
    };
}

