/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SingleLocationReportModel } from './SingleLocationReportModel';
import {
    SingleLocationReportModelFromJSON,
    SingleLocationReportModelFromJSONTyped,
    SingleLocationReportModelToJSON,
} from './SingleLocationReportModel';

/**
 * 
 * @export
 * @interface ListSingleLocationReportsResponse
 */
export interface ListSingleLocationReportsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListSingleLocationReportsResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<SingleLocationReportModel>}
     * @memberof ListSingleLocationReportsResponse
     */
    data: Array<SingleLocationReportModel>;
}

/**
 * Check if a given object implements the ListSingleLocationReportsResponse interface.
 */
export function instanceOfListSingleLocationReportsResponse(value: object): value is ListSingleLocationReportsResponse {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListSingleLocationReportsResponseFromJSON(json: any): ListSingleLocationReportsResponse {
    return ListSingleLocationReportsResponseFromJSONTyped(json, false);
}

export function ListSingleLocationReportsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSingleLocationReportsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'data': ((json['data'] as Array<any>).map(SingleLocationReportModelFromJSON)),
    };
}

export function ListSingleLocationReportsResponseToJSON(value?: ListSingleLocationReportsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_more': value['hasMore'],
        'data': ((value['data'] as Array<any>).map(SingleLocationReportModelToJSON)),
    };
}

