/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationIdsBody
 */
export interface LocationIdsBody {
    /**
     * List of location IDs. If omitted or null, the request applies to all locations.
     * @type {Array<number>}
     * @memberof LocationIdsBody
     */
    customerLocationIds?: Array<number>;
}

/**
 * Check if a given object implements the LocationIdsBody interface.
 */
export function instanceOfLocationIdsBody(value: object): value is LocationIdsBody {
    return true;
}

export function LocationIdsBodyFromJSON(json: any): LocationIdsBody {
    return LocationIdsBodyFromJSONTyped(json, false);
}

export function LocationIdsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationIdsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'customerLocationIds': json['customer_location_ids'] == null ? undefined : json['customer_location_ids'],
    };
}

export function LocationIdsBodyToJSON(value?: LocationIdsBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customer_location_ids': value['customerLocationIds'],
    };
}

