/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FloodType } from './FloodType';
import {
    FloodTypeFromJSON,
    FloodTypeFromJSONTyped,
    FloodTypeToJSON,
} from './FloodType';

/**
 * 
 * @export
 * @interface MeshOptionsOutput
 */
export interface MeshOptionsOutput {
    /**
     * 
     * @type {string}
     * @memberof MeshOptionsOutput
     */
    dataVersion?: MeshOptionsOutputDataVersionEnum | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeshOptionsOutput
     */
    scenarios?: Array<MeshOptionsOutputScenariosEnum> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof MeshOptionsOutput
     */
    years?: Array<MeshOptionsOutputYearsEnum> | null;
    /**
     * 
     * @type {Array<FloodType>}
     * @memberof MeshOptionsOutput
     */
    perils?: Array<FloodType> | null;
    /**
     * 
     * @type {}
     * @memberof MeshOptionsOutput
     */
    floodDefense?:  | null;
    /**
     * 
     * @type {}
     * @memberof MeshOptionsOutput
     */
    mesh?:  | null;
}


/**
 * @export
 */
export const MeshOptionsOutputDataVersionEnum = {
    _2: '2',
    _26: '2.6',
    _262: '2.6.2',
    _3: '3',
    _30: '3.0',
    _300: '3.0.0',
    _31: '3.1',
    _310: '3.1.0',
    _32: '3.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type MeshOptionsOutputDataVersionEnum = typeof MeshOptionsOutputDataVersionEnum[keyof typeof MeshOptionsOutputDataVersionEnum];

/**
 * @export
 */
export const MeshOptionsOutputScenariosEnum = {
    baseline: 'baseline',
    ssp126: 'ssp126',
    ssp245: 'ssp245',
    ssp585: 'ssp585',
    unknownDefaultOpenApi: '11184809'
} as const;
export type MeshOptionsOutputScenariosEnum = typeof MeshOptionsOutputScenariosEnum[keyof typeof MeshOptionsOutputScenariosEnum];

/**
 * @export
 */
export const MeshOptionsOutputYearsEnum = {
    NUMBER_1995: 1995,
    NUMBER_2020: 2020,
    NUMBER_2025: 2025,
    NUMBER_2030: 2030,
    NUMBER_2035: 2035,
    NUMBER_2040: 2040,
    NUMBER_2045: 2045,
    NUMBER_2050: 2050,
    NUMBER_2055: 2055,
    NUMBER_2060: 2060,
    NUMBER_2065: 2065,
    NUMBER_2070: 2070,
    NUMBER_2075: 2075,
    NUMBER_2080: 2080,
    NUMBER_2085: 2085,
    NUMBER_2090: 2090,
    NUMBER_2095: 2095,
    NUMBER_2100: 2100,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type MeshOptionsOutputYearsEnum = typeof MeshOptionsOutputYearsEnum[keyof typeof MeshOptionsOutputYearsEnum];


/**
 * Check if a given object implements the MeshOptionsOutput interface.
 */
export function instanceOfMeshOptionsOutput(value: object): value is MeshOptionsOutput {
    return true;
}

export function MeshOptionsOutputFromJSON(json: any): MeshOptionsOutput {
    return MeshOptionsOutputFromJSONTyped(json, false);
}

export function MeshOptionsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeshOptionsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'scenarios': json['scenarios'] == null ? undefined : json['scenarios'],
        'years': json['years'] == null ? undefined : json['years'],
        'perils': json['perils'] == null ? undefined : ((json['perils'] as Array<any>).map(FloodTypeFromJSON)),
        'floodDefense': json['flood_defense'] == null ? undefined : FromJSON(json['flood_defense']),
        'mesh': json['mesh'] == null ? undefined : FromJSON(json['mesh']),
    };
}

export function MeshOptionsOutputToJSON(value?: MeshOptionsOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data_version': value['dataVersion'],
        'scenarios': value['scenarios'],
        'years': value['years'],
        'perils': value['perils'] == null ? undefined : ((value['perils'] as Array<any>).map(FloodTypeToJSON)),
        'flood_defense': ToJSON(value['floodDefense']),
        'mesh': ToJSON(value['mesh']),
    };
}

