/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Options } from './Options';
import {
    OptionsFromJSON,
    OptionsFromJSONTyped,
    OptionsToJSON,
} from './Options';

/**
 * 
 * @export
 * @interface MeshParameterOptions
 */
export interface MeshParameterOptions {
    /**
     * 
     * @type {Options}
     * @memberof MeshParameterOptions
     */
    gridSize: Options;
    /**
     * 
     * @type {Options}
     * @memberof MeshParameterOptions
     */
    enabled?: Options;
    /**
     * 
     * @type {Options}
     * @memberof MeshParameterOptions
     */
    gridType?: Options;
    /**
     * 
     * @type {Options}
     * @memberof MeshParameterOptions
     */
    x?: Options;
    /**
     * 
     * @type {Options}
     * @memberof MeshParameterOptions
     */
    y?: Options;
}

/**
 * Check if a given object implements the MeshParameterOptions interface.
 */
export function instanceOfMeshParameterOptions(value: object): value is MeshParameterOptions {
    if (!('gridSize' in value) || value['gridSize'] === undefined) return false;
    return true;
}

export function MeshParameterOptionsFromJSON(json: any): MeshParameterOptions {
    return MeshParameterOptionsFromJSONTyped(json, false);
}

export function MeshParameterOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeshParameterOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'gridSize': OptionsFromJSON(json['grid_size']),
        'enabled': json['enabled'] == null ? undefined : OptionsFromJSON(json['enabled']),
        'gridType': json['grid_type'] == null ? undefined : OptionsFromJSON(json['grid_type']),
        'x': json['x'] == null ? undefined : OptionsFromJSON(json['x']),
        'y': json['y'] == null ? undefined : OptionsFromJSON(json['y']),
    };
}

export function MeshParameterOptionsToJSON(value?: MeshParameterOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'grid_size': OptionsToJSON(value['gridSize']),
        'enabled': OptionsToJSON(value['enabled']),
        'grid_type': OptionsToJSON(value['gridType']),
        'x': OptionsToJSON(value['x']),
        'y': OptionsToJSON(value['y']),
    };
}

