/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FloodType } from './FloodType';
import {
    FloodTypeFromJSON,
    FloodTypeFromJSONTyped,
    FloodTypeToJSON,
} from './FloodType';

/**
 * 
 * @export
 * @interface MeshResultSetOptionsInput
 */
export interface MeshResultSetOptionsInput {
    /**
     * 
     * @type {string}
     * @memberof MeshResultSetOptionsInput
     */
    dataVersion?: MeshResultSetOptionsInputDataVersionEnum | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeshResultSetOptionsInput
     */
    scenarios?: Array<MeshResultSetOptionsInputScenariosEnum> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof MeshResultSetOptionsInput
     */
    years?: Array<MeshResultSetOptionsInputYearsEnum> | null;
    /**
     * 
     * @type {Array<FloodType>}
     * @memberof MeshResultSetOptionsInput
     */
    perils?: Array<FloodType> | null;
    /**
     * 
     * @type {}
     * @memberof MeshResultSetOptionsInput
     */
    floodDefense?:  | null;
    /**
     * 
     * @type {boolean}
     * @memberof MeshResultSetOptionsInput
     */
    includeJqs?: boolean;
    /**
     * 
     * @type {}
     * @memberof MeshResultSetOptionsInput
     */
    mesh?:  | null;
    /**
     * 
     * @type {string}
     * @memberof MeshResultSetOptionsInput
     */
    type: MeshResultSetOptionsInputTypeEnum;
}


/**
 * @export
 */
export const MeshResultSetOptionsInputDataVersionEnum = {
    _2: '2',
    _26: '2.6',
    _262: '2.6.2',
    _3: '3',
    _30: '3.0',
    _300: '3.0.0',
    _31: '3.1',
    _310: '3.1.0',
    _32: '3.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type MeshResultSetOptionsInputDataVersionEnum = typeof MeshResultSetOptionsInputDataVersionEnum[keyof typeof MeshResultSetOptionsInputDataVersionEnum];

/**
 * @export
 */
export const MeshResultSetOptionsInputScenariosEnum = {
    baseline: 'baseline',
    ssp126: 'ssp126',
    ssp245: 'ssp245',
    ssp585: 'ssp585',
    unknownDefaultOpenApi: '11184809'
} as const;
export type MeshResultSetOptionsInputScenariosEnum = typeof MeshResultSetOptionsInputScenariosEnum[keyof typeof MeshResultSetOptionsInputScenariosEnum];

/**
 * @export
 */
export const MeshResultSetOptionsInputYearsEnum = {
    NUMBER_1995: 1995,
    NUMBER_2020: 2020,
    NUMBER_2025: 2025,
    NUMBER_2030: 2030,
    NUMBER_2035: 2035,
    NUMBER_2040: 2040,
    NUMBER_2045: 2045,
    NUMBER_2050: 2050,
    NUMBER_2055: 2055,
    NUMBER_2060: 2060,
    NUMBER_2065: 2065,
    NUMBER_2070: 2070,
    NUMBER_2075: 2075,
    NUMBER_2080: 2080,
    NUMBER_2085: 2085,
    NUMBER_2090: 2090,
    NUMBER_2095: 2095,
    NUMBER_2100: 2100,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type MeshResultSetOptionsInputYearsEnum = typeof MeshResultSetOptionsInputYearsEnum[keyof typeof MeshResultSetOptionsInputYearsEnum];

/**
 * @export
 */
export const MeshResultSetOptionsInputTypeEnum = {
    mesh: 'mesh',
    unknownDefaultOpenApi: '11184809'
} as const;
export type MeshResultSetOptionsInputTypeEnum = typeof MeshResultSetOptionsInputTypeEnum[keyof typeof MeshResultSetOptionsInputTypeEnum];


/**
 * Check if a given object implements the MeshResultSetOptionsInput interface.
 */
export function instanceOfMeshResultSetOptionsInput(value: object): value is MeshResultSetOptionsInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MeshResultSetOptionsInputFromJSON(json: any): MeshResultSetOptionsInput {
    return MeshResultSetOptionsInputFromJSONTyped(json, false);
}

export function MeshResultSetOptionsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeshResultSetOptionsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'scenarios': json['scenarios'] == null ? undefined : json['scenarios'],
        'years': json['years'] == null ? undefined : json['years'],
        'perils': json['perils'] == null ? undefined : ((json['perils'] as Array<any>).map(FloodTypeFromJSON)),
        'floodDefense': json['flood_defense'] == null ? undefined : FromJSON(json['flood_defense']),
        'includeJqs': json['include_jqs'] == null ? undefined : json['include_jqs'],
        'mesh': json['mesh'] == null ? undefined : FromJSON(json['mesh']),
        'type': json['type'],
    };
}

export function MeshResultSetOptionsInputToJSON(value?: MeshResultSetOptionsInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data_version': value['dataVersion'],
        'scenarios': value['scenarios'],
        'years': value['years'],
        'perils': value['perils'] == null ? undefined : ((value['perils'] as Array<any>).map(FloodTypeToJSON)),
        'flood_defense': ToJSON(value['floodDefense']),
        'include_jqs': value['includeJqs'],
        'mesh': ToJSON(value['mesh']),
        'type': value['type'],
    };
}

