/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FloodDefenseOutput } from './FloodDefenseOutput';
import {
    FloodDefenseOutputFromJSON,
    FloodDefenseOutputFromJSONTyped,
    FloodDefenseOutputToJSON,
} from './FloodDefenseOutput';
import type { PerilQueryOutputRecord } from './PerilQueryOutputRecord';
import {
    PerilQueryOutputRecordFromJSON,
    PerilQueryOutputRecordFromJSONTyped,
    PerilQueryOutputRecordToJSON,
} from './PerilQueryOutputRecord';

/**
 * 
 * @export
 * @interface MeshQueryOutputItem
 */
export interface MeshQueryOutputItem {
    /**
     * 
     * @type {number}
     * @memberof MeshQueryOutputItem
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof MeshQueryOutputItem
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof MeshQueryOutputItem
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof MeshQueryOutputItem
     */
    y?: number;
    /**
     * 
     * @type {string}
     * @memberof MeshQueryOutputItem
     */
    scenario: string;
    /**
     * 
     * @type {number}
     * @memberof MeshQueryOutputItem
     */
    year: number;
    /**
     * 
     * @type {FloodDefenseOutput}
     * @memberof MeshQueryOutputItem
     */
    floodDefense?: FloodDefenseOutput;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: PerilQueryOutputRecord; }; }}
     * @memberof MeshQueryOutputItem
     */
    metrics: { [key: string]: { [key: string]: PerilQueryOutputRecord; }; };
}

/**
 * Check if a given object implements the MeshQueryOutputItem interface.
 */
export function instanceOfMeshQueryOutputItem(value: object): value is MeshQueryOutputItem {
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('scenario' in value) || value['scenario'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    return true;
}

export function MeshQueryOutputItemFromJSON(json: any): MeshQueryOutputItem {
    return MeshQueryOutputItemFromJSONTyped(json, false);
}

export function MeshQueryOutputItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeshQueryOutputItem {
    if (json == null) {
        return json;
    }
    return {
        
        'longitude': json['longitude'],
        'latitude': json['latitude'],
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'scenario': json['scenario'],
        'year': json['year'],
        'floodDefense': json['flood_defense'] == null ? undefined : FloodDefenseOutputFromJSON(json['flood_defense']),
        'metrics': json['metrics'],
    };
}

export function MeshQueryOutputItemToJSON(value?: MeshQueryOutputItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'longitude': value['longitude'],
        'latitude': value['latitude'],
        'x': value['x'],
        'y': value['y'],
        'scenario': value['scenario'],
        'year': value['year'],
        'flood_defense': FloodDefenseOutputToJSON(value['floodDefense']),
        'metrics': value['metrics'],
    };
}

