/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinimizedMessageInner
 */
export interface MinimizedMessageInner {
    /**
     * 
     * @type {string}
     * @memberof MinimizedMessageInner
     */
    msg: string;
}

/**
 * Check if a given object implements the MinimizedMessageInner interface.
 */
export function instanceOfMinimizedMessageInner(value: object): value is MinimizedMessageInner {
    if (!('msg' in value) || value['msg'] === undefined) return false;
    return true;
}

export function MinimizedMessageInnerFromJSON(json: any): MinimizedMessageInner {
    return MinimizedMessageInnerFromJSONTyped(json, false);
}

export function MinimizedMessageInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimizedMessageInner {
    if (json == null) {
        return json;
    }
    return {
        
        'msg': json['msg'],
    };
}

export function MinimizedMessageInnerToJSON(value?: MinimizedMessageInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'msg': value['msg'],
    };
}

