/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a location that is not applicable for a strategy.
 * @export
 * @interface NotApplicableItem
 */
export interface NotApplicableItem {
    /**
     * 
     * @type {number}
     * @memberof NotApplicableItem
     */
    customerLocationIds: number[];
    /**
     * Why this strategy isn't applicable
     * @type {string}
     * @memberof NotApplicableItem
     */
    reason: string;
}

/**
 * Check if a given object implements the NotApplicableItem interface.
 */
export function instanceOfNotApplicableItem(value: object): value is NotApplicableItem {
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function NotApplicableItemFromJSON(json: any): NotApplicableItem {
    return NotApplicableItemFromJSONTyped(json, false);
}

export function NotApplicableItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotApplicableItem {
    if (json == null) {
        return json;
    }
    return {
        
        'customerLocationIds': json['customer_location_ids'],
        'reason': json['reason'],
    };
}

export function NotApplicableItemToJSON(value?: NotApplicableItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        'customer_location_ids': value['customerLocationIds'],
        'reason': value['reason'],
    };
}

