/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AdaptationResultSetOptionsInput } from './AdaptationResultSetOptionsInput';
import {
    instanceOfAdaptationResultSetOptionsInput,
    AdaptationResultSetOptionsInputFromJSON,
    AdaptationResultSetOptionsInputFromJSONTyped,
    AdaptationResultSetOptionsInputToJSON,
} from './AdaptationResultSetOptionsInput';
import type { DamagesResultSetOptions } from './DamagesResultSetOptions';
import {
    instanceOfDamagesResultSetOptions,
    DamagesResultSetOptionsFromJSON,
    DamagesResultSetOptionsFromJSONTyped,
    DamagesResultSetOptionsToJSON,
} from './DamagesResultSetOptions';
import type { DisclosureResultSetOptionsInput } from './DisclosureResultSetOptionsInput';
import {
    instanceOfDisclosureResultSetOptionsInput,
    DisclosureResultSetOptionsInputFromJSON,
    DisclosureResultSetOptionsInputFromJSONTyped,
    DisclosureResultSetOptionsInputToJSON,
} from './DisclosureResultSetOptionsInput';
import type { MeshResultSetOptions } from './MeshResultSetOptions';
import {
    instanceOfMeshResultSetOptions,
    MeshResultSetOptionsFromJSON,
    MeshResultSetOptionsFromJSONTyped,
    MeshResultSetOptionsToJSON,
} from './MeshResultSetOptions';
import type { PerilsResultSetOptions } from './PerilsResultSetOptions';
import {
    instanceOfPerilsResultSetOptions,
    PerilsResultSetOptionsFromJSON,
    PerilsResultSetOptionsFromJSONTyped,
    PerilsResultSetOptionsToJSON,
} from './PerilsResultSetOptions';
import type { PortfolioFinancialResultSetOptions } from './PortfolioFinancialResultSetOptions';
import {
    instanceOfPortfolioFinancialResultSetOptions,
    PortfolioFinancialResultSetOptionsFromJSON,
    PortfolioFinancialResultSetOptionsFromJSONTyped,
    PortfolioFinancialResultSetOptionsToJSON,
} from './PortfolioFinancialResultSetOptions';
import type { ScoresResultSetOptions } from './ScoresResultSetOptions';
import {
    instanceOfScoresResultSetOptions,
    ScoresResultSetOptionsFromJSON,
    ScoresResultSetOptionsFromJSONTyped,
    ScoresResultSetOptionsToJSON,
} from './ScoresResultSetOptions';

/**
 * @type Options3
 * 
 * @export
 */
export type Options3 = { type: 'adaptation' } & AdaptationResultSetOptionsInput | { type: 'damages' } & DamagesResultSetOptions | { type: 'disclosure' } & DisclosureResultSetOptionsInput | { type: 'mesh' } & MeshResultSetOptions | { type: 'perils' } & PerilsResultSetOptions | { type: 'portfolio_financial' } & PortfolioFinancialResultSetOptions | { type: 'scores' } & ScoresResultSetOptions | { type: 'AdaptationResultSetOptions-Input' } & AdaptationResultSetOptionsInput | { type: 'DamagesResultSetOptions' } & DamagesResultSetOptions | { type: 'DisclosureResultSetOptions-Input' } & DisclosureResultSetOptionsInput | { type: 'MeshResultSetOptions' } & MeshResultSetOptions | { type: 'PerilsResultSetOptions' } & PerilsResultSetOptions | { type: 'PortfolioFinancialResultSetOptions' } & PortfolioFinancialResultSetOptions | { type: 'ScoresResultSetOptions' } & ScoresResultSetOptions;

export function Options3FromJSON(json: any): Options3 {
    return Options3FromJSONTyped(json, false);
}

export function Options3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Options3 {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'adaptation':
            return Object.assign({}, AdaptationResultSetOptionsInputFromJSONTyped(json, true), { type: 'adaptation' } as const);
        case 'damages':
            return Object.assign({}, DamagesResultSetOptionsFromJSONTyped(json, true), { type: 'damages' } as const);
        case 'disclosure':
            return Object.assign({}, DisclosureResultSetOptionsInputFromJSONTyped(json, true), { type: 'disclosure' } as const);
        case 'mesh':
            return Object.assign({}, MeshResultSetOptionsFromJSONTyped(json, true), { type: 'mesh' } as const);
        case 'perils':
            return Object.assign({}, PerilsResultSetOptionsFromJSONTyped(json, true), { type: 'perils' } as const);
        case 'portfolio_financial':
            return Object.assign({}, PortfolioFinancialResultSetOptionsFromJSONTyped(json, true), { type: 'portfolio_financial' } as const);
        case 'scores':
            return Object.assign({}, ScoresResultSetOptionsFromJSONTyped(json, true), { type: 'scores' } as const);
        case 'AdaptationResultSetOptions-Input':
            return Object.assign({}, AdaptationResultSetOptionsInputFromJSONTyped(json, true), { type: 'AdaptationResultSetOptions-Input' } as const);
        case 'DamagesResultSetOptions':
            return Object.assign({}, DamagesResultSetOptionsFromJSONTyped(json, true), { type: 'DamagesResultSetOptions' } as const);
        case 'DisclosureResultSetOptions-Input':
            return Object.assign({}, DisclosureResultSetOptionsInputFromJSONTyped(json, true), { type: 'DisclosureResultSetOptions-Input' } as const);
        case 'MeshResultSetOptions':
            return Object.assign({}, MeshResultSetOptionsFromJSONTyped(json, true), { type: 'MeshResultSetOptions' } as const);
        case 'PerilsResultSetOptions':
            return Object.assign({}, PerilsResultSetOptionsFromJSONTyped(json, true), { type: 'PerilsResultSetOptions' } as const);
        case 'PortfolioFinancialResultSetOptions':
            return Object.assign({}, PortfolioFinancialResultSetOptionsFromJSONTyped(json, true), { type: 'PortfolioFinancialResultSetOptions' } as const);
        case 'ScoresResultSetOptions':
            return Object.assign({}, ScoresResultSetOptionsFromJSONTyped(json, true), { type: 'ScoresResultSetOptions' } as const);
        default:
            throw new Error(`No variant of Options3 exists with 'type=${json['type']}'`);
    }
}

export function Options3ToJSON(value?: Options3 | null): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'adaptation':
            return AdaptationResultSetOptionsInputToJSON(value);
        case 'damages':
            return DamagesResultSetOptionsToJSON(value);
        case 'disclosure':
            return DisclosureResultSetOptionsInputToJSON(value);
        case 'mesh':
            return MeshResultSetOptionsToJSON(value);
        case 'perils':
            return PerilsResultSetOptionsToJSON(value);
        case 'portfolio_financial':
            return PortfolioFinancialResultSetOptionsToJSON(value);
        case 'scores':
            return ScoresResultSetOptionsToJSON(value);
        case 'AdaptationResultSetOptions-Input':
            return AdaptationResultSetOptionsInputToJSON(value);
        case 'DamagesResultSetOptions':
            return DamagesResultSetOptionsToJSON(value);
        case 'DisclosureResultSetOptions-Input':
            return DisclosureResultSetOptionsInputToJSON(value);
        case 'MeshResultSetOptions':
            return MeshResultSetOptionsToJSON(value);
        case 'PerilsResultSetOptions':
            return PerilsResultSetOptionsToJSON(value);
        case 'PortfolioFinancialResultSetOptions':
            return PortfolioFinancialResultSetOptionsToJSON(value);
        case 'ScoresResultSetOptions':
            return ScoresResultSetOptionsToJSON(value);
        default:
            throw new Error(`No variant of Options3 exists with 'type=${value['type']}'`);
    }

}

