/* tslint:disable */
/* eslint-disable */ // @ts-nocheck // @ts-nocheck // @ts-nocheck // @ts-nocheck // @ts-nocheck // @ts-nocheck // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DamagesResultSetOptionsOutput } from './DamagesResultSetOptionsOutput';
import {
    instanceOfDamagesResultSetOptionsOutput,
    DamagesResultSetOptionsOutputFromJSON,
    DamagesResultSetOptionsOutputFromJSONTyped,
    DamagesResultSetOptionsOutputToJSON,
} from './DamagesResultSetOptionsOutput';
import type { DisclosureResultSetOptionsOutput } from './DisclosureResultSetOptionsOutput';
import {
    instanceOfDisclosureResultSetOptionsOutput,
    DisclosureResultSetOptionsOutputFromJSON,
    DisclosureResultSetOptionsOutputFromJSONTyped,
    DisclosureResultSetOptionsOutputToJSON,
} from './DisclosureResultSetOptionsOutput';
import type { MeshResultSetOptionsOutput } from './MeshResultSetOptionsOutput';
import {
    instanceOfMeshResultSetOptionsOutput,
    MeshResultSetOptionsOutputFromJSON,
    MeshResultSetOptionsOutputFromJSONTyped,
    MeshResultSetOptionsOutputToJSON,
} from './MeshResultSetOptionsOutput';
import type { PerilsResultSetOptionsOutput } from './PerilsResultSetOptionsOutput';
import {
    instanceOfPerilsResultSetOptionsOutput,
    PerilsResultSetOptionsOutputFromJSON,
    PerilsResultSetOptionsOutputFromJSONTyped,
    PerilsResultSetOptionsOutputToJSON,
} from './PerilsResultSetOptionsOutput';
import type { PortfolioFinancialResultSetOptionsOutput } from './PortfolioFinancialResultSetOptionsOutput';
import {
    instanceOfPortfolioFinancialResultSetOptionsOutput,
    PortfolioFinancialResultSetOptionsOutputFromJSON,
    PortfolioFinancialResultSetOptionsOutputFromJSONTyped,
    PortfolioFinancialResultSetOptionsOutputToJSON,
} from './PortfolioFinancialResultSetOptionsOutput';
import type { ScoresResultSetOptionsOutput } from './ScoresResultSetOptionsOutput';
import {
    instanceOfScoresResultSetOptionsOutput,
    ScoresResultSetOptionsOutputFromJSON,
    ScoresResultSetOptionsOutputFromJSONTyped,
    ScoresResultSetOptionsOutputToJSON,
} from './ScoresResultSetOptionsOutput';
import type { SupplementalResultSetOptions } from './SupplementalResultSetOptions';
import {
    instanceOfSupplementalResultSetOptions,
    SupplementalResultSetOptionsFromJSON,
    SupplementalResultSetOptionsFromJSONTyped,
    SupplementalResultSetOptionsToJSON,
} from './SupplementalResultSetOptions';

/**
 * @type Options4AnyOf
 * 
 * @export
 */
export type Options4AnyOf = { type: 'damages' } & DamagesResultSetOptionsOutput | { type: 'disclosure' } & DisclosureResultSetOptionsOutput | { type: 'mesh' } & MeshResultSetOptionsOutput | { type: 'perils' } & PerilsResultSetOptionsOutput | { type: 'portfolio_financial' } & PortfolioFinancialResultSetOptionsOutput | { type: 'scores' } & ScoresResultSetOptionsOutput | { type: 'supplemental' } & SupplementalResultSetOptions | { type: 'DamagesResultSetOptions-Output' } & DamagesResultSetOptionsOutput | { type: 'DisclosureResultSetOptions-Output' } & DisclosureResultSetOptionsOutput | { type: 'MeshResultSetOptions-Output' } & MeshResultSetOptionsOutput | { type: 'PerilsResultSetOptions-Output' } & PerilsResultSetOptionsOutput | { type: 'PortfolioFinancialResultSetOptions-Output' } & PortfolioFinancialResultSetOptionsOutput | { type: 'ScoresResultSetOptions-Output' } & ScoresResultSetOptionsOutput | { type: 'SupplementalResultSetOptions' } & SupplementalResultSetOptions;

export function Options4AnyOfFromJSON(json: any): Options4AnyOf {
    return Options4AnyOfFromJSONTyped(json, false);
}

export function Options4AnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options4AnyOf {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'damages':
            return Object.assign({}, DamagesResultSetOptionsOutputFromJSONTyped(json, true), { type: 'damages' } as const);
        case 'disclosure':
            return Object.assign({}, DisclosureResultSetOptionsOutputFromJSONTyped(json, true), { type: 'disclosure' } as const);
        case 'mesh':
            return Object.assign({}, MeshResultSetOptionsOutputFromJSONTyped(json, true), { type: 'mesh' } as const);
        case 'perils':
            return Object.assign({}, PerilsResultSetOptionsOutputFromJSONTyped(json, true), { type: 'perils' } as const);
        case 'portfolio_financial':
            return Object.assign({}, PortfolioFinancialResultSetOptionsOutputFromJSONTyped(json, true), { type: 'portfolio_financial' } as const);
        case 'scores':
            return Object.assign({}, ScoresResultSetOptionsOutputFromJSONTyped(json, true), { type: 'scores' } as const);
        case 'supplemental':
            return Object.assign({}, SupplementalResultSetOptionsFromJSONTyped(json, true), { type: 'supplemental' } as const);
        case 'DamagesResultSetOptions-Output':
            return Object.assign({}, DamagesResultSetOptionsOutputFromJSONTyped(json, true), { type: 'DamagesResultSetOptions-Output' } as const);
        case 'DisclosureResultSetOptions-Output':
            return Object.assign({}, DisclosureResultSetOptionsOutputFromJSONTyped(json, true), { type: 'DisclosureResultSetOptions-Output' } as const);
        case 'MeshResultSetOptions-Output':
            return Object.assign({}, MeshResultSetOptionsOutputFromJSONTyped(json, true), { type: 'MeshResultSetOptions-Output' } as const);
        case 'PerilsResultSetOptions-Output':
            return Object.assign({}, PerilsResultSetOptionsOutputFromJSONTyped(json, true), { type: 'PerilsResultSetOptions-Output' } as const);
        case 'PortfolioFinancialResultSetOptions-Output':
            return Object.assign({}, PortfolioFinancialResultSetOptionsOutputFromJSONTyped(json, true), { type: 'PortfolioFinancialResultSetOptions-Output' } as const);
        case 'ScoresResultSetOptions-Output':
            return Object.assign({}, ScoresResultSetOptionsOutputFromJSONTyped(json, true), { type: 'ScoresResultSetOptions-Output' } as const);
        case 'SupplementalResultSetOptions':
            return Object.assign({}, SupplementalResultSetOptionsFromJSONTyped(json, true), { type: 'SupplementalResultSetOptions' } as const);
        default:
            throw new Error(`No variant of Options4AnyOf exists with 'type=${json['type']}'`);
    }
}

export function Options4AnyOfToJSON(value?: Options4AnyOf | null): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'damages':
            return DamagesResultSetOptionsOutputToJSON(value);
        case 'disclosure':
            return DisclosureResultSetOptionsOutputToJSON(value);
        case 'mesh':
            return MeshResultSetOptionsOutputToJSON(value);
        case 'perils':
            return PerilsResultSetOptionsOutputToJSON(value);
        case 'portfolio_financial':
            return PortfolioFinancialResultSetOptionsOutputToJSON(value);
        case 'scores':
            return ScoresResultSetOptionsOutputToJSON(value);
        case 'supplemental':
            return SupplementalResultSetOptionsToJSON(value);
        case 'DamagesResultSetOptions-Output':
            return DamagesResultSetOptionsOutputToJSON(value);
        case 'DisclosureResultSetOptions-Output':
            return DisclosureResultSetOptionsOutputToJSON(value);
        case 'MeshResultSetOptions-Output':
            return MeshResultSetOptionsOutputToJSON(value);
        case 'PerilsResultSetOptions-Output':
            return PerilsResultSetOptionsOutputToJSON(value);
        case 'PortfolioFinancialResultSetOptions-Output':
            return PortfolioFinancialResultSetOptionsOutputToJSON(value);
        case 'ScoresResultSetOptions-Output':
            return ScoresResultSetOptionsOutputToJSON(value);
        case 'SupplementalResultSetOptions':
            return SupplementalResultSetOptionsToJSON(value);
        default:
            throw new Error(`No variant of Options4AnyOf exists with 'type=${value['type']}'`);
    }

}

