/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Options } from './Options';
import {
    OptionsFromJSON,
    OptionsFromJSONTyped,
    OptionsToJSON,
} from './Options';
import type { DamageAndLossParameterOptions } from './DamageAndLossParameterOptions';
import {
    DamageAndLossParameterOptionsFromJSON,
    DamageAndLossParameterOptionsFromJSONTyped,
    DamageAndLossParameterOptionsToJSON,
} from './DamageAndLossParameterOptions';
import type { BenchmarkingParameterOptions } from './BenchmarkingParameterOptions';
import {
    BenchmarkingParameterOptionsFromJSON,
    BenchmarkingParameterOptionsFromJSONTyped,
    BenchmarkingParameterOptionsToJSON,
} from './BenchmarkingParameterOptions';
import type { FloodDefenseParameterOptions } from './FloodDefenseParameterOptions';
import {
    FloodDefenseParameterOptionsFromJSON,
    FloodDefenseParameterOptionsFromJSONTyped,
    FloodDefenseParameterOptionsToJSON,
} from './FloodDefenseParameterOptions';
import type { MeshParameterOptions } from './MeshParameterOptions';
import {
    MeshParameterOptionsFromJSON,
    MeshParameterOptionsFromJSONTyped,
    MeshParameterOptionsToJSON,
} from './MeshParameterOptions';

/**
 * 
 * @export
 * @interface ParameterOptions
 */
export interface ParameterOptions {
    /**
     * 
     * @type {Options}
     * @memberof ParameterOptions
     */
    csgVersion?: Options;
    /**
     * 
     * @type {Options}
     * @memberof ParameterOptions
     */
    eiVersion?: Options;
    /**
     * 
     * @type {Options}
     * @memberof ParameterOptions
     */
    perils?: Options;
    /**
     * 
     * @type {Options}
     * @memberof ParameterOptions
     */
    scenarios?: Options;
    /**
     * 
     * @type {Options}
     * @memberof ParameterOptions
     */
    years?: Options;
    /**
     * 
     * @type {Options}
     * @memberof ParameterOptions
     */
    scores?: Options;
    /**
     * 
     * @type {Options}
     * @memberof ParameterOptions
     */
    eiModules?: Options;
    /**
     * 
     * @type {BenchmarkingParameterOptions}
     * @memberof ParameterOptions
     */
    benchmarking?: BenchmarkingParameterOptions;
    /**
     * 
     * @type {DamageAndLossParameterOptions}
     * @memberof ParameterOptions
     */
    damageAndLoss?: DamageAndLossParameterOptions;
    /**
     * 
     * @type {FloodDefenseParameterOptions}
     * @memberof ParameterOptions
     */
    floodDefense?: FloodDefenseParameterOptions;
    /**
     * 
     * @type {MeshParameterOptions}
     * @memberof ParameterOptions
     */
    mesh?: MeshParameterOptions;
}

/**
 * Check if a given object implements the ParameterOptions interface.
 */
export function instanceOfParameterOptions(value: object): value is ParameterOptions {
    return true;
}

export function ParameterOptionsFromJSON(json: any): ParameterOptions {
    return ParameterOptionsFromJSONTyped(json, false);
}

export function ParameterOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'csgVersion': json['csg_version'] == null ? undefined : OptionsFromJSON(json['csg_version']),
        'eiVersion': json['ei_version'] == null ? undefined : OptionsFromJSON(json['ei_version']),
        'perils': json['perils'] == null ? undefined : OptionsFromJSON(json['perils']),
        'scenarios': json['scenarios'] == null ? undefined : OptionsFromJSON(json['scenarios']),
        'years': json['years'] == null ? undefined : OptionsFromJSON(json['years']),
        'scores': json['scores'] == null ? undefined : OptionsFromJSON(json['scores']),
        'eiModules': json['ei_modules'] == null ? undefined : OptionsFromJSON(json['ei_modules']),
        'benchmarking': json['benchmarking'] == null ? undefined : BenchmarkingParameterOptionsFromJSON(json['benchmarking']),
        'damageAndLoss': json['damage_and_loss'] == null ? undefined : DamageAndLossParameterOptionsFromJSON(json['damage_and_loss']),
        'floodDefense': json['flood_defense'] == null ? undefined : FloodDefenseParameterOptionsFromJSON(json['flood_defense']),
        'mesh': json['mesh'] == null ? undefined : MeshParameterOptionsFromJSON(json['mesh']),
    };
}

export function ParameterOptionsToJSON(value?: ParameterOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'csg_version': OptionsToJSON(value['csgVersion']),
        'ei_version': OptionsToJSON(value['eiVersion']),
        'perils': OptionsToJSON(value['perils']),
        'scenarios': OptionsToJSON(value['scenarios']),
        'years': OptionsToJSON(value['years']),
        'scores': OptionsToJSON(value['scores']),
        'ei_modules': OptionsToJSON(value['eiModules']),
        'benchmarking': BenchmarkingParameterOptionsToJSON(value['benchmarking']),
        'damage_and_loss': DamageAndLossParameterOptionsToJSON(value['damageAndLoss']),
        'flood_defense': FloodDefenseParameterOptionsToJSON(value['floodDefense']),
        'mesh': MeshParameterOptionsToJSON(value['mesh']),
    };
}

