/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParameterBounds
 */
export interface ParameterBounds {
    /**
     * 
     * @type {number}
     * @memberof ParameterBounds
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof ParameterBounds
     */
    max?: number;
}

/**
 * Check if a given object implements the ParameterBounds interface.
 */
export function instanceOfParameterBounds(value: object): value is ParameterBounds {
    return true;
}

export function ParameterBoundsFromJSON(json: any): ParameterBounds {
    return ParameterBoundsFromJSONTyped(json, false);
}

export function ParameterBoundsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterBounds {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
    };
}

export function ParameterBoundsToJSON(value?: ParameterBounds | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'min': value['min'],
        'max': value['max'],
    };
}

