/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FloodDefenseOptions } from './FloodDefenseOptions';
import {
    FloodDefenseOptionsFromJSON,
    FloodDefenseOptionsFromJSONTyped,
    FloodDefenseOptionsToJSON,
} from './FloodDefenseOptions';

/**
 * 
 * @export
 * @interface PerilsOptionsOutput
 */
export interface PerilsOptionsOutput {
    /**
     * 
     * @type {string}
     * @memberof PerilsOptionsOutput
     */
    dataVersion?: PerilsOptionsOutputDataVersionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof PerilsOptionsOutput
     */
    scenarios?: Array<PerilsOptionsOutputScenariosEnum>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PerilsOptionsOutput
     */
    years?: Array<PerilsOptionsOutputYearsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PerilsOptionsOutput
     */
    perils?: Array<PerilsOptionsOutputPerilsEnum>;
    /**
     * 
     * @type {FloodDefenseOptions}
     * @memberof PerilsOptionsOutput
     */
    floodDefense?: FloodDefenseOptions;
}


/**
 * @export
 */
export const PerilsOptionsOutputDataVersionEnum = {
    _26: '2.6',
    _262: '2.6.2',
    _3: '3',
    _30: '3.0',
    _300: '3.0.0',
    _31: '3.1',
    _310: '3.1.0',
    _32: '3.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type PerilsOptionsOutputDataVersionEnum = typeof PerilsOptionsOutputDataVersionEnum[keyof typeof PerilsOptionsOutputDataVersionEnum];

/**
 * @export
 */
export const PerilsOptionsOutputScenariosEnum = {
    baseline: 'baseline',
    ssp126: 'ssp126',
    ssp245: 'ssp245',
    ssp585: 'ssp585',
    unknownDefaultOpenApi: '11184809'
} as const;
export type PerilsOptionsOutputScenariosEnum = typeof PerilsOptionsOutputScenariosEnum[keyof typeof PerilsOptionsOutputScenariosEnum];

/**
 * @export
 */
export const PerilsOptionsOutputYearsEnum = {
    NUMBER_1995: 1995,
    NUMBER_2020: 2020,
    NUMBER_2025: 2025,
    NUMBER_2030: 2030,
    NUMBER_2035: 2035,
    NUMBER_2040: 2040,
    NUMBER_2045: 2045,
    NUMBER_2050: 2050,
    NUMBER_2055: 2055,
    NUMBER_2060: 2060,
    NUMBER_2065: 2065,
    NUMBER_2070: 2070,
    NUMBER_2075: 2075,
    NUMBER_2080: 2080,
    NUMBER_2085: 2085,
    NUMBER_2090: 2090,
    NUMBER_2095: 2095,
    NUMBER_2100: 2100,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type PerilsOptionsOutputYearsEnum = typeof PerilsOptionsOutputYearsEnum[keyof typeof PerilsOptionsOutputYearsEnum];

/**
 * @export
 */
export const PerilsOptionsOutputPerilsEnum = {
    cold: 'cold',
    combinedFlood: 'combinedFlood',
    drought: 'drought',
    fire: 'fire',
    hail: 'hail',
    heat: 'heat',
    precip: 'precip',
    wind: 'wind',
    subsidence: 'subsidence',
    coastalFlood: 'coastalFlood',
    fluvialFlood: 'fluvialFlood',
    pluvialFlood: 'pluvialFlood',
    subsidence: 'subsidence',
    unknownDefaultOpenApi: '11184809'
} as const;
export type PerilsOptionsOutputPerilsEnum = typeof PerilsOptionsOutputPerilsEnum[keyof typeof PerilsOptionsOutputPerilsEnum];


/**
 * Check if a given object implements the PerilsOptionsOutput interface.
 */
export function instanceOfPerilsOptionsOutput(value: object): value is PerilsOptionsOutput {
    return true;
}

export function PerilsOptionsOutputFromJSON(json: any): PerilsOptionsOutput {
    return PerilsOptionsOutputFromJSONTyped(json, false);
}

export function PerilsOptionsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerilsOptionsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'scenarios': json['scenarios'] == null ? undefined : json['scenarios'],
        'years': json['years'] == null ? undefined : json['years'],
        'perils': json['perils'] == null ? undefined : json['perils'],
        'floodDefense': json['flood_defense'] == null ? undefined : FloodDefenseOptionsFromJSON(json['flood_defense']),
    };
}

export function PerilsOptionsOutputToJSON(value?: PerilsOptionsOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data_version': value['dataVersion'],
        'scenarios': value['scenarios'],
        'years': value['years'],
        'perils': value['perils'],
        'flood_defense': FloodDefenseOptionsToJSON(value['floodDefense']),
    };
}

