/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const PipelineErrorType = {
    fileValidationError: 'file_validation_error',
    internalError: 'internal_error',
    unknownDefaultOpenApi: '11184809'
} as const;
export type PipelineErrorType = typeof PipelineErrorType[keyof typeof PipelineErrorType];


export function instanceOfPipelineErrorType(value: any): boolean {
    for (const key in PipelineErrorType) {
        if (Object.prototype.hasOwnProperty.call(PipelineErrorType, key)) {
            if ((PipelineErrorType as Record<string, PipelineErrorType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PipelineErrorTypeFromJSON(json: any): PipelineErrorType {
    return PipelineErrorTypeFromJSONTyped(json, false);
}

export function PipelineErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineErrorType {
    return json as PipelineErrorType;
}

export function PipelineErrorTypeToJSON(value?: PipelineErrorType | null): any {
    return value as any;
}

