/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DamagesResultSetOptions } from './DamagesResultSetOptions';
import {
    DamagesResultSetOptionsFromJSON,
    DamagesResultSetOptionsFromJSONTyped,
    DamagesResultSetOptionsToJSON,
} from './DamagesResultSetOptions';
import type { PerilsResultSetOptions } from './PerilsResultSetOptions';
import {
    PerilsResultSetOptionsFromJSON,
    PerilsResultSetOptionsFromJSONTyped,
    PerilsResultSetOptionsToJSON,
} from './PerilsResultSetOptions';
import type { AdaptationResultSetOptionsOutput } from './AdaptationResultSetOptionsOutput';
import {
    AdaptationResultSetOptionsOutputFromJSON,
    AdaptationResultSetOptionsOutputFromJSONTyped,
    AdaptationResultSetOptionsOutputToJSON,
} from './AdaptationResultSetOptionsOutput';
import type { PipelineType } from './PipelineType';
import {
    PipelineTypeFromJSON,
    PipelineTypeFromJSONTyped,
    PipelineTypeToJSON,
} from './PipelineType';
import type { ScoresResultSetOptions } from './ScoresResultSetOptions';
import {
    ScoresResultSetOptionsFromJSON,
    ScoresResultSetOptionsFromJSONTyped,
    ScoresResultSetOptionsToJSON,
} from './ScoresResultSetOptions';
import type { DisclosureResultSetOptions } from './DisclosureResultSetOptions';
import {
    DisclosureResultSetOptionsFromJSON,
    DisclosureResultSetOptionsFromJSONTyped,
    DisclosureResultSetOptionsToJSON,
} from './DisclosureResultSetOptions';
import type { ExportOptionsMixin } from './ExportOptionsMixin';
import {
    ExportOptionsMixinFromJSON,
    ExportOptionsMixinFromJSONTyped,
    ExportOptionsMixinToJSON,
} from './ExportOptionsMixin';
import type { PipelineCreatePortfolioInput } from './PipelineCreatePortfolioInput';
import {
    PipelineCreatePortfolioInputFromJSON,
    PipelineCreatePortfolioInputFromJSONTyped,
    PipelineCreatePortfolioInputToJSON,
} from './PipelineCreatePortfolioInput';
import type { MeshResultSetOptions } from './MeshResultSetOptions';
import {
    MeshResultSetOptionsFromJSON,
    MeshResultSetOptionsFromJSONTyped,
    MeshResultSetOptionsToJSON,
} from './MeshResultSetOptions';

/**
 * 
 * @export
 * @interface PipelineOptions
 */
export interface PipelineOptions {
    /**
     * 
     * @type {boolean}
     * @memberof PipelineOptions
     */
    enableGeocodeStatus?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PipelineOptions
     */
    portfolioId?: string;
    /**
     * 
     * @type {PipelineType}
     * @memberof PipelineOptions
     */
    type?: PipelineType;
    /**
     * 
     * @type {PipelineCreatePortfolioInput}
     * @memberof PipelineOptions
     */
    createPortfolioOptions?: PipelineCreatePortfolioInput;
    /**
     * 
     * @type {ExportOptionsMixin}
     * @memberof PipelineOptions
     */
    portfolioExportOptions?: ExportOptionsMixin;
    /**
     * 
     * @type {PerilsResultSetOptions}
     * @memberof PipelineOptions
     */
    perilsResultSetOptions?: PerilsResultSetOptions;
    /**
     * 
     * @type {ExportOptionsMixin}
     * @memberof PipelineOptions
     */
    perilsExportOptions?: ExportOptionsMixin;
    /**
     * 
     * @type {DamagesResultSetOptions}
     * @memberof PipelineOptions
     */
    impactsResultSetOptions?: DamagesResultSetOptions;
    /**
     * 
     * @type {ExportOptionsMixin}
     * @memberof PipelineOptions
     */
    impactsExportOptions?: ExportOptionsMixin;
    /**
     * 
     * @type {boolean}
     * @memberof PipelineOptions
     */
    prplEnable?: boolean;
    /**
     * 
     * @type {ExportOptionsMixin}
     * @memberof PipelineOptions
     */
    prplExportOptions?: ExportOptionsMixin;
    /**
     * 
     * @type {ScoresResultSetOptions}
     * @memberof PipelineOptions
     */
    scoresResultSetOptions?: ScoresResultSetOptions;
    /**
     * 
     * @type {ExportOptionsMixin}
     * @memberof PipelineOptions
     */
    scoresExportOptions?: ExportOptionsMixin;
    /**
     * 
     * @type {MeshResultSetOptions}
     * @memberof PipelineOptions
     */
    meshResultSetOptions?: MeshResultSetOptions;
    /**
     * 
     * @type {DisclosureResultSetOptions}
     * @memberof PipelineOptions
     */
    disclosureResultSetOptions?: DisclosureResultSetOptions;
    /**
     * 
     * @type {AdaptationResultSetOptionsOutput}
     * @memberof PipelineOptions
     */
    adaptationResultSetOptions?: AdaptationResultSetOptionsOutput;
    /**
     * 
     * @type {ExportOptionsMixin}
     * @memberof PipelineOptions
     */
    adaptationExportOptions?: ExportOptionsMixin;
    /**
     * 
     * @type {ExportOptionsMixin}
     * @memberof PipelineOptions
     */
    meshExportOptions?: ExportOptionsMixin;
}

/**
 * Check if a given object implements the PipelineOptions interface.
 */
export function instanceOfPipelineOptions(value: object): value is PipelineOptions {
    return true;
}

export function PipelineOptionsFromJSON(json: any): PipelineOptions {
    return PipelineOptionsFromJSONTyped(json, false);
}

export function PipelineOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'enableGeocodeStatus': json['enable_geocode_status'] == null ? undefined : json['enable_geocode_status'],
        'portfolioId': json['portfolio_id'] == null ? undefined : json['portfolio_id'],
        'type': json['type'] == null ? undefined : PipelineTypeFromJSON(json['type']),
        'createPortfolioOptions': json['create_portfolio_options'] == null ? undefined : PipelineCreatePortfolioInputFromJSON(json['create_portfolio_options']),
        'portfolioExportOptions': json['portfolio_export_options'] == null ? undefined : ExportOptionsMixinFromJSON(json['portfolio_export_options']),
        'perilsResultSetOptions': json['perils_result_set_options'] == null ? undefined : PerilsResultSetOptionsFromJSON(json['perils_result_set_options']),
        'perilsExportOptions': json['perils_export_options'] == null ? undefined : ExportOptionsMixinFromJSON(json['perils_export_options']),
        'impactsResultSetOptions': json['impacts_result_set_options'] == null ? undefined : DamagesResultSetOptionsFromJSON(json['impacts_result_set_options']),
        'impactsExportOptions': json['impacts_export_options'] == null ? undefined : ExportOptionsMixinFromJSON(json['impacts_export_options']),
        'prplEnable': json['prpl_enable'] == null ? undefined : json['prpl_enable'],
        'prplExportOptions': json['prpl_export_options'] == null ? undefined : ExportOptionsMixinFromJSON(json['prpl_export_options']),
        'scoresResultSetOptions': json['scores_result_set_options'] == null ? undefined : ScoresResultSetOptionsFromJSON(json['scores_result_set_options']),
        'scoresExportOptions': json['scores_export_options'] == null ? undefined : ExportOptionsMixinFromJSON(json['scores_export_options']),
        'meshResultSetOptions': json['mesh_result_set_options'] == null ? undefined : MeshResultSetOptionsFromJSON(json['mesh_result_set_options']),
        'disclosureResultSetOptions': json['disclosure_result_set_options'] == null ? undefined : DisclosureResultSetOptionsFromJSON(json['disclosure_result_set_options']),
        'adaptationResultSetOptions': json['adaptation_result_set_options'] == null ? undefined : AdaptationResultSetOptionsOutputFromJSON(json['adaptation_result_set_options']),
        'adaptationExportOptions': json['adaptation_export_options'] == null ? undefined : ExportOptionsMixinFromJSON(json['adaptation_export_options']),
        'meshExportOptions': json['mesh_export_options'] == null ? undefined : ExportOptionsMixinFromJSON(json['mesh_export_options']),
    };
}

export function PipelineOptionsToJSON(value?: PipelineOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enable_geocode_status': value['enableGeocodeStatus'],
        'portfolio_id': value['portfolioId'],
        'type': PipelineTypeToJSON(value['type']),
        'create_portfolio_options': PipelineCreatePortfolioInputToJSON(value['createPortfolioOptions']),
        'portfolio_export_options': ExportOptionsMixinToJSON(value['portfolioExportOptions']),
        'perils_result_set_options': PerilsResultSetOptionsToJSON(value['perilsResultSetOptions']),
        'perils_export_options': ExportOptionsMixinToJSON(value['perilsExportOptions']),
        'impacts_result_set_options': DamagesResultSetOptionsToJSON(value['impactsResultSetOptions']),
        'impacts_export_options': ExportOptionsMixinToJSON(value['impactsExportOptions']),
        'prpl_enable': value['prplEnable'],
        'prpl_export_options': ExportOptionsMixinToJSON(value['prplExportOptions']),
        'scores_result_set_options': ScoresResultSetOptionsToJSON(value['scoresResultSetOptions']),
        'scores_export_options': ExportOptionsMixinToJSON(value['scoresExportOptions']),
        'mesh_result_set_options': MeshResultSetOptionsToJSON(value['meshResultSetOptions']),
        'disclosure_result_set_options': DisclosureResultSetOptionsToJSON(value['disclosureResultSetOptions']),
        'adaptation_result_set_options': AdaptationResultSetOptionsOutputToJSON(value['adaptationResultSetOptions']),
        'adaptation_export_options': ExportOptionsMixinToJSON(value['adaptationExportOptions']),
        'mesh_export_options': ExportOptionsMixinToJSON(value['meshExportOptions']),
    };
}

