/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const PipelineType = {
    webapp: 'webapp',
    cust1: 'cust1',
    cust3: 'cust3',
    cust5: 'cust5',
    unknownDefaultOpenApi: '11184809'
} as const;
export type PipelineType = typeof PipelineType[keyof typeof PipelineType];


export function instanceOfPipelineType(value: any): boolean {
    for (const key in PipelineType) {
        if (Object.prototype.hasOwnProperty.call(PipelineType, key)) {
            if ((PipelineType as Record<string, PipelineType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PipelineTypeFromJSON(json: any): PipelineType {
    return PipelineTypeFromJSONTyped(json, false);
}

export function PipelineTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineType {
    return json as PipelineType;
}

export function PipelineTypeToJSON(value?: PipelineType | null): any {
    return value as any;
}

