/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DamagesResultSetOptionsBase } from './DamagesResultSetOptionsBase';
import {
    DamagesResultSetOptionsBaseFromJSON,
    DamagesResultSetOptionsBaseFromJSONTyped,
    DamagesResultSetOptionsBaseToJSON,
} from './DamagesResultSetOptionsBase';

/**
 * 
 * @export
 * @interface PortfolioFinancialResultSetOptions
 */
export interface PortfolioFinancialResultSetOptions {
    /**
     * 
     * @type {string}
     * @memberof PortfolioFinancialResultSetOptions
     */
    type: PortfolioFinancialResultSetOptionsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PortfolioFinancialResultSetOptions
     */
    eiVersion: PortfolioFinancialResultSetOptionsEiVersionEnum;
    /**
     * 
     * @type {string}
     * @memberof PortfolioFinancialResultSetOptions
     */
    damagesResultSet: string;
    /**
     * Options used to create damages_result_set. These are always overwritten if included in the input.
     * @type {DamagesResultSetOptionsBase}
     * @memberof PortfolioFinancialResultSetOptions
     */
    damagesOptions?: DamagesResultSetOptionsBase;
}


/**
 * @export
 */
export const PortfolioFinancialResultSetOptionsTypeEnum = {
    portfolioFinancial: 'portfolio_financial',
    unknownDefaultOpenApi: '11184809'
} as const;
export type PortfolioFinancialResultSetOptionsTypeEnum = typeof PortfolioFinancialResultSetOptionsTypeEnum[keyof typeof PortfolioFinancialResultSetOptionsTypeEnum];

/**
 * @export
 */
export const PortfolioFinancialResultSetOptionsEiVersionEnum = {
    _10: '3.1.0',
    _11: '3.1.1',
    _12: '3.1.2',
    _20: '3.2.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type PortfolioFinancialResultSetOptionsEiVersionEnum = typeof PortfolioFinancialResultSetOptionsEiVersionEnum[keyof typeof PortfolioFinancialResultSetOptionsEiVersionEnum];


/**
 * Check if a given object implements the PortfolioFinancialResultSetOptions interface.
 */
export function instanceOfPortfolioFinancialResultSetOptions(value: object): value is PortfolioFinancialResultSetOptions {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('eiVersion' in value) || value['eiVersion'] === undefined) return false;
    if (!('damagesResultSet' in value) || value['damagesResultSet'] === undefined) return false;
    return true;
}

export function PortfolioFinancialResultSetOptionsFromJSON(json: any): PortfolioFinancialResultSetOptions {
    return PortfolioFinancialResultSetOptionsFromJSONTyped(json, false);
}

export function PortfolioFinancialResultSetOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioFinancialResultSetOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'eiVersion': json['ei_version'],
        'damagesResultSet': json['damages_result_set'],
        'damagesOptions': json['damages_options'] == null ? undefined : DamagesResultSetOptionsBaseFromJSON(json['damages_options']),
    };
}

export function PortfolioFinancialResultSetOptionsToJSON(value?: PortfolioFinancialResultSetOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'ei_version': value['eiVersion'],
        'damages_result_set': value['damagesResultSet'],
        'damages_options': DamagesResultSetOptionsBaseToJSON(value['damagesOptions']),
    };
}

