/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioSharingOutput
 */
export interface PortfolioSharingOutput {
    /**
     * 
     * @type {Array<string>}
     * @memberof PortfolioSharingOutput
     */
    succeeded: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PortfolioSharingOutput
     */
    failed: Array<string>;
}

/**
 * Check if a given object implements the PortfolioSharingOutput interface.
 */
export function instanceOfPortfolioSharingOutput(value: object): value is PortfolioSharingOutput {
    if (!('succeeded' in value) || value['succeeded'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function PortfolioSharingOutputFromJSON(json: any): PortfolioSharingOutput {
    return PortfolioSharingOutputFromJSONTyped(json, false);
}

export function PortfolioSharingOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioSharingOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'succeeded': json['succeeded'],
        'failed': json['failed'],
    };
}

export function PortfolioSharingOutputToJSON(value?: PortfolioSharingOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'succeeded': value['succeeded'],
        'failed': value['failed'],
    };
}

