/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineStatus } from './PipelineStatus';
import {
    PipelineStatusFromJSON,
    PipelineStatusFromJSONTyped,
    PipelineStatusToJSON,
} from './PipelineStatus';
import type { PipelineError } from './PipelineError';
import {
    PipelineErrorFromJSON,
    PipelineErrorFromJSONTyped,
    PipelineErrorToJSON,
} from './PipelineError';

/**
 * 
 * @export
 * @interface PortfolioPipelineResponse
 */
export interface PortfolioPipelineResponse {
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    id: string;
    /**
     * 
     * @type {PipelineStatus}
     * @memberof PortfolioPipelineResponse
     */
    status: PipelineStatus;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    dataVersion?: string;
    /**
     * 
     * @type {Array<PipelineError>}
     * @memberof PortfolioPipelineResponse
     */
    errors: Array<PipelineError>;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    portfolioId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    portfolioExportId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    perilsResultSetId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    perilsResultSetExportId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    impactsResultSetId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    impactsResultSetExportId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    prplResultSetId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    prplResultSetExportId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    scoresResultSetId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    scoresResultSetExportId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    meshResultSetId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    meshResultSetExportId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    disclosureResultSetId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    disclosureResultSetExportId?: string;
    /**
     *
     * @type {string}
     * @memberof PortfolioPipelineResponse
     */
    adaptationResultSetId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PortfolioPipelineResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PortfolioPipelineResponse interface.
 */
export function instanceOfPortfolioPipelineResponse(value: object): value is PortfolioPipelineResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PortfolioPipelineResponseFromJSON(json: any): PortfolioPipelineResponse {
    return PortfolioPipelineResponseFromJSONTyped(json, false);
}

export function PortfolioPipelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioPipelineResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': PipelineStatusFromJSON(json['status']),
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'errors': ((json['errors'] as Array<any>).map(PipelineErrorFromJSON)),
        'portfolioId': json['portfolio_id'] == null ? undefined : json['portfolio_id'],
        'portfolioExportId': json['portfolio_export_id'] == null ? undefined : json['portfolio_export_id'],
        'perilsResultSetId': json['perils_result_set_id'] == null ? undefined : json['perils_result_set_id'],
        'perilsResultSetExportId': json['perils_result_set_export_id'] == null ? undefined : json['perils_result_set_export_id'],
        'impactsResultSetId': json['impacts_result_set_id'] == null ? undefined : json['impacts_result_set_id'],
        'impactsResultSetExportId': json['impacts_result_set_export_id'] == null ? undefined : json['impacts_result_set_export_id'],
        'prplResultSetId': json['prpl_result_set_id'] == null ? undefined : json['prpl_result_set_id'],
        'prplResultSetExportId': json['prpl_result_set_export_id'] == null ? undefined : json['prpl_result_set_export_id'],
        'scoresResultSetId': json['scores_result_set_id'] == null ? undefined : json['scores_result_set_id'],
        'scoresResultSetExportId': json['scores_result_set_export_id'] == null ? undefined : json['scores_result_set_export_id'],
        'meshResultSetId': json['mesh_result_set_id'] == null ? undefined : json['mesh_result_set_id'],
        'meshResultSetExportId': json['mesh_result_set_export_id'] == null ? undefined : json['mesh_result_set_export_id'],
        'disclosureResultSetId': json['disclosure_result_set_id'] == null ? undefined : json['disclosure_result_set_id'],
        'adaptationResultSetId': json['adaptation_result_set_id'] == null ? undefined : json['adaptation_result_set_id'],
        'disclosureResultSetExportId': json['disclosure_result_set_export_id'] == null ? undefined : json['disclosure_result_set_export_id'],
        'createdAt': (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
    };
}

export function PortfolioPipelineResponseToJSON(value?: PortfolioPipelineResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'status': PipelineStatusToJSON(value['status']),
        'data_version': value['dataVersion'],
        'errors': ((value['errors'] as Array<any>).map(PipelineErrorToJSON)),
        'portfolio_id': value['portfolioId'],
        'portfolio_export_id': value['portfolioExportId'],
        'perils_result_set_id': value['perilsResultSetId'],
        'perils_result_set_export_id': value['perilsResultSetExportId'],
        'impacts_result_set_id': value['impactsResultSetId'],
        'impacts_result_set_export_id': value['impactsResultSetExportId'],
        'prpl_result_set_id': value['prplResultSetId'],
        'prpl_result_set_export_id': value['prplResultSetExportId'],
        'scores_result_set_id': value['scoresResultSetId'],
        'scores_result_set_export_id': value['scoresResultSetExportId'],
        'mesh_result_set_id': value['meshResultSetId'],
        'mesh_result_set_export_id': value['meshResultSetExportId'],
        'disclosure_result_set_id': value['disclosureResultSetId'],
        'disclosure_result_set_export_id': value['disclosureResultSetExportId'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

