/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultSetMetadataResponseMetadata } from './ResultSetMetadataResponseMetadata';
import {
    ResultSetMetadataResponseMetadataFromJSON,
    ResultSetMetadataResponseMetadataFromJSONTyped,
    ResultSetMetadataResponseMetadataToJSON,
} from './ResultSetMetadataResponseMetadata';

/**
 * 
 * @export
 * @interface ResultSetMetadataResponse
 */
export interface ResultSetMetadataResponse {
    /**
     * 
     * @type {ResultSetMetadataResponseMetadata}
     * @memberof ResultSetMetadataResponse
     */
    metadata: ResultSetMetadataResponseMetadata | null;
}

/**
 * Check if a given object implements the ResultSetMetadataResponse interface.
 */
export function instanceOfResultSetMetadataResponse(value: object): value is ResultSetMetadataResponse {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ResultSetMetadataResponseFromJSON(json: any): ResultSetMetadataResponse {
    return ResultSetMetadataResponseFromJSONTyped(json, false);
}

export function ResultSetMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSetMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': ResultSetMetadataResponseMetadataFromJSON(json['metadata']),
    };
}

export function ResultSetMetadataResponseToJSON(value?: ResultSetMetadataResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': ResultSetMetadataResponseMetadataToJSON(value['metadata']),
    };
}

