/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Options4 } from './Options4';
import {
    Options4FromJSON,
    Options4FromJSONTyped,
    Options4ToJSON,
} from './Options4';
import type { ResultSetStatistics } from './ResultSetStatistics';
import {
    ResultSetStatisticsFromJSON,
    ResultSetStatisticsFromJSONTyped,
    ResultSetStatisticsToJSON,
} from './ResultSetStatistics';
import type { ResultSetStatus } from './ResultSetStatus';
import {
    ResultSetStatusFromJSON,
    ResultSetStatusFromJSONTyped,
    ResultSetStatusToJSON,
} from './ResultSetStatus';

/**
 * 
 * @export
 * @interface ResultSetDataResponse
 */
export interface ResultSetDataResponse {
    /**
     * 
     * @type {Options4}
     * @memberof ResultSetDataResponse
     */
    options: Options4;
    /**
     * 
     * @type {string}
     * @memberof ResultSetDataResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResultSetDataResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultSetDataResponse
     */
    portfolio: string;
    /**
     * 
     * @type {ResultSetStatus}
     * @memberof ResultSetDataResponse
     */
    status: ResultSetStatus;
    /**
     * 
     * @type {Date}
     * @memberof ResultSetDataResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ResultSetDataResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ResultSetDataResponse
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof ResultSetDataResponse
     */
    updatedBy: string;
    /**
     * 
     * @type {ResultSetStatistics}
     * @memberof ResultSetDataResponse
     */
    statistics: ResultSetStatistics;
    /**
     * 
     * @type {any}
     * @memberof ResultSetDataResponse
     */
    data?: any | null;
}

/**
 * Check if a given object implements the ResultSetDataResponse interface.
 */
export function instanceOfResultSetDataResponse(value: object): value is ResultSetDataResponse {
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('statistics' in value) || value['statistics'] === undefined) return false;
    return true;
}

export function ResultSetDataResponseFromJSON(json: any): ResultSetDataResponse {
    return ResultSetDataResponseFromJSONTyped(json, false);
}

export function ResultSetDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSetDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'options': Options4FromJSON(json['options']),
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'portfolio': json['portfolio'],
        'status': ResultSetStatusFromJSON(json['status']),
        'createdAt': (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
        'updatedAt': (isNaN(json['updated_at']) ? (new Date(json['updated_at'])) : (new Date(1000 * json['updated_at']))),
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'statistics': ResultSetStatisticsFromJSON(json['statistics']),
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ResultSetDataResponseToJSON(value?: ResultSetDataResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'options': Options4ToJSON(value['options']),
        'id': value['id'],
        'name': value['name'],
        'portfolio': value['portfolio'],
        'status': ResultSetStatusToJSON(value['status']),
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
        'statistics': ResultSetStatisticsToJSON(value['statistics']),
        'data': value['data'],
    };
}

