/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultSetStatistics } from './ResultSetStatistics';
import {
    ResultSetStatisticsFromJSON,
    ResultSetStatisticsFromJSONTyped,
    ResultSetStatisticsToJSON,
} from './ResultSetStatistics';
import type { ResultSetStatus } from './ResultSetStatus';
import {
    ResultSetStatusFromJSON,
    ResultSetStatusFromJSONTyped,
    ResultSetStatusToJSON,
} from './ResultSetStatus';
import type { ResultSetDataSchema } from './ResultSetDataSchema';
import {
    ResultSetDataSchemaFromJSON,
    ResultSetDataSchemaFromJSONTyped,
    ResultSetDataSchemaToJSON,
} from './ResultSetDataSchema';
import type { Options6 } from './Options6';
import {
    Options6FromJSON,
    Options6FromJSONTyped,
    Options6ToJSON,
} from './Options6';

/**
 * 
 * @export
 * @interface ResultSetSchemaResponse
 */
export interface ResultSetSchemaResponse {
    /**
     * 
     * @type {Options6}
     * @memberof ResultSetSchemaResponse
     */
    options: Options6;
    /**
     * 
     * @type {string}
     * @memberof ResultSetSchemaResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResultSetSchemaResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultSetSchemaResponse
     */
    portfolio: string;
    /**
     * 
     * @type {ResultSetStatus}
     * @memberof ResultSetSchemaResponse
     */
    status: ResultSetStatus;
    /**
     * 
     * @type {Date}
     * @memberof ResultSetSchemaResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ResultSetSchemaResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ResultSetSchemaResponse
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof ResultSetSchemaResponse
     */
    updatedBy: string;
    /**
     * 
     * @type {ResultSetStatistics}
     * @memberof ResultSetSchemaResponse
     */
    statistics: ResultSetStatistics;
    /**
     * 
     * @type {Array<ResultSetDataSchema>}
     * @memberof ResultSetSchemaResponse
     */
    dataSchema: Array<ResultSetDataSchema>;
}

/**
 * Check if a given object implements the ResultSetSchemaResponse interface.
 */
export function instanceOfResultSetSchemaResponse(value: object): value is ResultSetSchemaResponse {
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('statistics' in value) || value['statistics'] === undefined) return false;
    if (!('dataSchema' in value) || value['dataSchema'] === undefined) return false;
    return true;
}

export function ResultSetSchemaResponseFromJSON(json: any): ResultSetSchemaResponse {
    return ResultSetSchemaResponseFromJSONTyped(json, false);
}

export function ResultSetSchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSetSchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'options': Options6FromJSON(json['options']),
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'portfolio': json['portfolio'],
        'status': ResultSetStatusFromJSON(json['status']),
        'createdAt': (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
        'updatedAt': (isNaN(json['updated_at']) ? (new Date(json['updated_at'])) : (new Date(1000 * json['updated_at']))),
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'statistics': ResultSetStatisticsFromJSON(json['statistics']),
        'dataSchema': ((json['data_schema'] as Array<any>).map(ResultSetDataSchemaFromJSON)),
    };
}

export function ResultSetSchemaResponseToJSON(value?: ResultSetSchemaResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'options': Options6ToJSON(value['options']),
        'id': value['id'],
        'name': value['name'],
        'portfolio': value['portfolio'],
        'status': ResultSetStatusToJSON(value['status']),
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
        'statistics': ResultSetStatisticsToJSON(value['statistics']),
        'data_schema': ((value['dataSchema'] as Array<any>).map(ResultSetDataSchemaToJSON)),
    };
}

