/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DisclosureMetadata } from './DisclosureMetadata';
import {
    instanceOfDisclosureMetadata,
    DisclosureMetadataFromJSON,
    DisclosureMetadataFromJSONTyped,
    DisclosureMetadataToJSON,
} from './DisclosureMetadata';

/**
 * @type ResultSetMetadataResponseMetadata
 * 
 * @export
 */
export type ResultSetMetadataResponseMetadata = { resultSetType: 'disclosure' } & DisclosureMetadata | { resultSetType: 'DisclosureMetadata' } & DisclosureMetadata;

export function ResultSetMetadataResponseMetadataFromJSON(json: any): ResultSetMetadataResponseMetadata {
    return ResultSetMetadataResponseMetadataFromJSONTyped(json, false);
}

export function ResultSetMetadataResponseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSetMetadataResponseMetadata {
    if (json == null) {
        return json;
    }
    switch (json['result_set_type']) {
        case 'disclosure':
            return Object.assign({}, DisclosureMetadataFromJSONTyped(json, true), { resultSetType: 'disclosure' } as const);
        case 'DisclosureMetadata':
            return Object.assign({}, DisclosureMetadataFromJSONTyped(json, true), { resultSetType: 'DisclosureMetadata' } as const);
        default:
            throw new Error(`No variant of ResultSetMetadataResponseMetadata exists with 'resultSetType=${json['resultSetType']}'`);
    }
}

export function ResultSetMetadataResponseMetadataToJSON(value?: ResultSetMetadataResponseMetadata | null): any {
    if (value == null) {
        return value;
    }
    switch (value['resultSetType']) {
        case 'disclosure':
            return DisclosureMetadataToJSON(value);
        case 'DisclosureMetadata':
            return DisclosureMetadataToJSON(value);
        default:
            throw new Error(`No variant of ResultSetMetadataResponseMetadata exists with 'resultSetType=${value['resultSetType']}'`);
    }

}

