/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JupiterApiEnumsBenchmarkingLevel } from './JupiterApiEnumsBenchmarkingLevel';
import {
    JupiterApiEnumsBenchmarkingLevelFromJSON,
    JupiterApiEnumsBenchmarkingLevelFromJSONTyped,
    JupiterApiEnumsBenchmarkingLevelToJSON,
} from './JupiterApiEnumsBenchmarkingLevel';

/**
 * 
 * @export
 * @interface ScoresOptionsOutput
 */
export interface ScoresOptionsOutput {
    /**
     * 
     * @type {string}
     * @memberof ScoresOptionsOutput
     */
    dataVersion?: ScoresOptionsOutputDataVersionEnum | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScoresOptionsOutput
     */
    includeBenchmarks?: boolean | null;
    /**
     * 
     * @type {Array<JupiterApiEnumsBenchmarkingLevel>}
     * @memberof ScoresOptionsOutput
     */
    benchmarkLevels?: Array<JupiterApiEnumsBenchmarkingLevel> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScoresOptionsOutput
     */
    perils?: Array<ScoresOptionsOutputPerilsEnum> | null;
}


/**
 * @export
 */
export const ScoresOptionsOutputDataVersionEnum = {
    _2: '2',
    _26: '2.6',
    _262: '2.6.2',
    _3: '3',
    _30: '3.0',
    _300: '3.0.0',
    _31: '3.1',
    _310: '3.1.0',
    _32: '3.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresOptionsOutputDataVersionEnum = typeof ScoresOptionsOutputDataVersionEnum[keyof typeof ScoresOptionsOutputDataVersionEnum];

/**
 * @export
 */
export const ScoresOptionsOutputPerilsEnum = {
    allPerils: 'allPerils',
    cold: 'cold',
    combinedFlood: 'combinedFlood',
    drought: 'drought',
    fire: 'fire',
    hail: 'hail',
    heat: 'heat',
    precip: 'precip',
    wind: 'wind',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresOptionsOutputPerilsEnum = typeof ScoresOptionsOutputPerilsEnum[keyof typeof ScoresOptionsOutputPerilsEnum];


/**
 * Check if a given object implements the ScoresOptionsOutput interface.
 */
export function instanceOfScoresOptionsOutput(value: object): value is ScoresOptionsOutput {
    return true;
}

export function ScoresOptionsOutputFromJSON(json: any): ScoresOptionsOutput {
    return ScoresOptionsOutputFromJSONTyped(json, false);
}

export function ScoresOptionsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoresOptionsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'includeBenchmarks': json['include_benchmarks'] == null ? undefined : json['include_benchmarks'],
        'benchmarkLevels': json['benchmark_levels'] == null ? undefined : ((json['benchmark_levels'] as Array<any>).map(JupiterApiEnumsBenchmarkingLevelFromJSON)),
        'perils': json['perils'] == null ? undefined : json['perils'],
    };
}

export function ScoresOptionsOutputToJSON(value?: ScoresOptionsOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data_version': value['dataVersion'],
        'include_benchmarks': value['includeBenchmarks'],
        'benchmark_levels': value['benchmarkLevels'] == null ? undefined : ((value['benchmarkLevels'] as Array<any>).map(JupiterApiEnumsBenchmarkingLevelToJSON)),
        'perils': value['perils'],
    };
}

