/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BenchmarkingLevelInput } from './BenchmarkingLevelInput';
import {
    BenchmarkingLevelInputFromJSON,
    BenchmarkingLevelInputFromJSONTyped,
    BenchmarkingLevelInputToJSON,
} from './BenchmarkingLevelInput';

/**
 * 
 * @export
 * @interface ScoresOptionsInput
 */
export interface ScoresOptionsInput {
    /**
     * 
     * @type {string}
     * @memberof ScoresOptionsInput
     */
    dataVersion?: ScoresOptionsInputDataVersionEnum | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScoresOptionsInput
     */
    includeBenchmarks?: boolean | null;
    /**
     * 
     * @type {Array<BenchmarkingLevelInput>}
     * @memberof ScoresOptionsInput
     */
    benchmarkLevels?: Array<BenchmarkingLevelInput> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScoresOptionsInput
     */
    perils?: Array<ScoresOptionsInputPerilsEnum> | null;
}


/**
 * @export
 */
export const ScoresOptionsInputDataVersionEnum = {
    _2: '2',
    _26: '2.6',
    _262: '2.6.2',
    _3: '3',
    _30: '3.0',
    _300: '3.0.0',
    _31: '3.1',
    _310: '3.1.0',
    _32: '3.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresOptionsInputDataVersionEnum = typeof ScoresOptionsInputDataVersionEnum[keyof typeof ScoresOptionsInputDataVersionEnum];

/**
 * @export
 */
export const ScoresOptionsInputPerilsEnum = {
    allPerils: 'allPerils',
    cold: 'cold',
    combinedFlood: 'combinedFlood',
    drought: 'drought',
    fire: 'fire',
    hail: 'hail',
    heat: 'heat',
    precip: 'precip',
    wind: 'wind',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresOptionsInputPerilsEnum = typeof ScoresOptionsInputPerilsEnum[keyof typeof ScoresOptionsInputPerilsEnum];


/**
 * Check if a given object implements the ScoresOptionsInput interface.
 */
export function instanceOfScoresOptionsInput(value: object): value is ScoresOptionsInput {
    return true;
}

export function ScoresOptionsInputFromJSON(json: any): ScoresOptionsInput {
    return ScoresOptionsInputFromJSONTyped(json, false);
}

export function ScoresOptionsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoresOptionsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'includeBenchmarks': json['include_benchmarks'] == null ? undefined : json['include_benchmarks'],
        'benchmarkLevels': json['benchmark_levels'] == null ? undefined : ((json['benchmark_levels'] as Array<any>).map(BenchmarkingLevelInputFromJSON)),
        'perils': json['perils'] == null ? undefined : json['perils'],
    };
}

export function ScoresOptionsInputToJSON(value?: ScoresOptionsInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data_version': value['dataVersion'],
        'include_benchmarks': value['includeBenchmarks'],
        'benchmark_levels': value['benchmarkLevels'] == null ? undefined : ((value['benchmarkLevels'] as Array<any>).map(BenchmarkingLevelInputToJSON)),
        'perils': value['perils'],
    };
}

