/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JupiterApiEnumsBenchmarkingLevel } from './JupiterApiEnumsBenchmarkingLevel';
import {
    JupiterApiEnumsBenchmarkingLevelFromJSON,
    JupiterApiEnumsBenchmarkingLevelFromJSONTyped,
    JupiterApiEnumsBenchmarkingLevelToJSON,
} from './JupiterApiEnumsBenchmarkingLevel';

/**
 * 
 * @export
 * @interface ScoresResultSetOptionsOutput
 */
export interface ScoresResultSetOptionsOutput {
    /**
     * 
     * @type {string}
     * @memberof ScoresResultSetOptionsOutput
     */
    dataVersion?: ScoresResultSetOptionsOutputDataVersionEnum | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScoresResultSetOptionsOutput
     */
    includeBenchmarks?: boolean | null;
    /**
     * 
     * @type {Array<JupiterApiEnumsBenchmarkingLevel>}
     * @memberof ScoresResultSetOptionsOutput
     */
    benchmarkLevels?: Array<JupiterApiEnumsBenchmarkingLevel> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScoresResultSetOptionsOutput
     */
    perils?: Array<ScoresResultSetOptionsOutputPerilsEnum> | null;
    /**
     * 
     * @type {string}
     * @memberof ScoresResultSetOptionsOutput
     */
    type: ScoresResultSetOptionsOutputTypeEnum;
}


/**
 * @export
 */
export const ScoresResultSetOptionsOutputDataVersionEnum = {
    _2: '2',
    _26: '2.6',
    _262: '2.6.2',
    _3: '3',
    _30: '3.0',
    _300: '3.0.0',
    _31: '3.1',
    _310: '3.1.0',
    _32: '3.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresResultSetOptionsOutputDataVersionEnum = typeof ScoresResultSetOptionsOutputDataVersionEnum[keyof typeof ScoresResultSetOptionsOutputDataVersionEnum];

/**
 * @export
 */
export const ScoresResultSetOptionsOutputPerilsEnum = {
    allPerils: 'allPerils',
    cold: 'cold',
    combinedFlood: 'combinedFlood',
    drought: 'drought',
    fire: 'fire',
    hail: 'hail',
    heat: 'heat',
    precip: 'precip',
    wind: 'wind',
    subsidence: 'subsidence',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresResultSetOptionsOutputPerilsEnum = typeof ScoresResultSetOptionsOutputPerilsEnum[keyof typeof ScoresResultSetOptionsOutputPerilsEnum];

/**
 * @export
 */
export const ScoresResultSetOptionsOutputTypeEnum = {
    scores: 'scores',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresResultSetOptionsOutputTypeEnum = typeof ScoresResultSetOptionsOutputTypeEnum[keyof typeof ScoresResultSetOptionsOutputTypeEnum];


/**
 * Check if a given object implements the ScoresResultSetOptionsOutput interface.
 */
export function instanceOfScoresResultSetOptionsOutput(value: object): value is ScoresResultSetOptionsOutput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ScoresResultSetOptionsOutputFromJSON(json: any): ScoresResultSetOptionsOutput {
    return ScoresResultSetOptionsOutputFromJSONTyped(json, false);
}

export function ScoresResultSetOptionsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoresResultSetOptionsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'includeBenchmarks': json['include_benchmarks'] == null ? undefined : json['include_benchmarks'],
        'benchmarkLevels': json['benchmark_levels'] == null ? undefined : ((json['benchmark_levels'] as Array<any>).map(JupiterApiEnumsBenchmarkingLevelFromJSON)),
        'perils': json['perils'] == null ? undefined : json['perils'],
        'type': json['type'],
    };
}

export function ScoresResultSetOptionsOutputToJSON(value?: ScoresResultSetOptionsOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data_version': value['dataVersion'],
        'include_benchmarks': value['includeBenchmarks'],
        'benchmark_levels': value['benchmarkLevels'] == null ? undefined : ((value['benchmarkLevels'] as Array<any>).map(JupiterApiEnumsBenchmarkingLevelToJSON)),
        'perils': value['perils'],
        'type': value['type'],
    };
}

