/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BenchmarkingLevelInput } from './BenchmarkingLevelInput';
import {
    BenchmarkingLevelInputFromJSON,
    BenchmarkingLevelInputFromJSONTyped,
    BenchmarkingLevelInputToJSON,
} from './BenchmarkingLevelInput';

/**
 * 
 * @export
 * @interface ScoresResultSetOptionsInput
 */
export interface ScoresResultSetOptionsInput {
    /**
     * 
     * @type {string}
     * @memberof ScoresResultSetOptionsInput
     */
    dataVersion?: ScoresResultSetOptionsInputDataVersionEnum | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScoresResultSetOptionsInput
     */
    includeBenchmarks?: boolean | null;
    /**
     * 
     * @type {Array<BenchmarkingLevelInput>}
     * @memberof ScoresResultSetOptionsInput
     */
    benchmarkLevels?: Array<BenchmarkingLevelInput> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScoresResultSetOptionsInput
     */
    perils?: Array<ScoresResultSetOptionsInputPerilsEnum> | null;
    /**
     * 
     * @type {string}
     * @memberof ScoresResultSetOptionsInput
     */
    type: ScoresResultSetOptionsInputTypeEnum;
}


/**
 * @export
 */
export const ScoresResultSetOptionsInputDataVersionEnum = {
    _2: '2',
    _26: '2.6',
    _262: '2.6.2',
    _3: '3',
    _30: '3.0',
    _300: '3.0.0',
    _31: '3.1',
    _310: '3.1.0',
    _32: '3.2',
    _320: '3.2.0',
    _330: '3.3.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresResultSetOptionsInputDataVersionEnum = typeof ScoresResultSetOptionsInputDataVersionEnum[keyof typeof ScoresResultSetOptionsInputDataVersionEnum];

/**
 * @export
 */
export const ScoresResultSetOptionsInputPerilsEnum = {
    allPerils: 'allPerils',
    cold: 'cold',
    combinedFlood: 'combinedFlood',
    drought: 'drought',
    fire: 'fire',
    hail: 'hail',
    heat: 'heat',
    precip: 'precip',
    wind: 'wind',
    subsidence: 'subsidence',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresResultSetOptionsInputPerilsEnum = typeof ScoresResultSetOptionsInputPerilsEnum[keyof typeof ScoresResultSetOptionsInputPerilsEnum];

/**
 * @export
 */
export const ScoresResultSetOptionsInputTypeEnum = {
    scores: 'scores',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ScoresResultSetOptionsInputTypeEnum = typeof ScoresResultSetOptionsInputTypeEnum[keyof typeof ScoresResultSetOptionsInputTypeEnum];


/**
 * Check if a given object implements the ScoresResultSetOptionsInput interface.
 */
export function instanceOfScoresResultSetOptionsInput(value: object): value is ScoresResultSetOptionsInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ScoresResultSetOptionsInputFromJSON(json: any): ScoresResultSetOptionsInput {
    return ScoresResultSetOptionsInputFromJSONTyped(json, false);
}

export function ScoresResultSetOptionsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoresResultSetOptionsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'includeBenchmarks': json['include_benchmarks'] == null ? undefined : json['include_benchmarks'],
        'benchmarkLevels': json['benchmark_levels'] == null ? undefined : ((json['benchmark_levels'] as Array<any>).map(BenchmarkingLevelInputFromJSON)),
        'perils': json['perils'] == null ? undefined : json['perils'],
        'type': json['type'],
    };
}

export function ScoresResultSetOptionsInputToJSON(value?: ScoresResultSetOptionsInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data_version': value['dataVersion'],
        'include_benchmarks': value['includeBenchmarks'],
        'benchmark_levels': value['benchmarkLevels'] == null ? undefined : ((value['benchmarkLevels'] as Array<any>).map(BenchmarkingLevelInputToJSON)),
        'perils': value['perils'],
        'type': value['type'],
    };
}

