/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A stateless SLR file produced by the stateless SLR workflow.
 * @export
 * @interface StatelessSingleLocationReportFile
 */
export interface StatelessSingleLocationReportFile {
    /**
     * 
     * @type {string}
     * @memberof StatelessSingleLocationReportFile
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof StatelessSingleLocationReportFile
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof StatelessSingleLocationReportFile
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof StatelessSingleLocationReportFile
     */
    sizeBytes: number;
    /**
     * 
     * @type {number}
     * @memberof StatelessSingleLocationReportFile
     */
    locationId: number;
}

/**
 * Check if a given object implements the StatelessSingleLocationReportFile interface.
 */
export function instanceOfStatelessSingleLocationReportFile(value: object): value is StatelessSingleLocationReportFile {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    return true;
}

export function StatelessSingleLocationReportFileFromJSON(json: any): StatelessSingleLocationReportFile {
    return StatelessSingleLocationReportFileFromJSONTyped(json, false);
}

export function StatelessSingleLocationReportFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatelessSingleLocationReportFile {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'fileId': json['file_id'],
        'url': json['url'],
        'sizeBytes': json['size_bytes'],
        'locationId': json['location_id'],
    };
}

export function StatelessSingleLocationReportFileToJSON(value?: StatelessSingleLocationReportFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filename': value['filename'],
        'file_id': value['fileId'],
        'url': value['url'],
        'size_bytes': value['sizeBytes'],
        'location_id': value['locationId'],
    };
}

