/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter API
 * Welcome to Jupiter\'s ClimateScore Global API
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Customer-facing supplemental result set options. For simplicity's sake these are specified
 * in a similar manner to perils: customers can't pick and choose per-peril metrics, scenarios,
 * and years but specify them on the result set level instead.
 * @export
 * @interface SupplementalResultSetOptions
 */
export interface SupplementalResultSetOptions {
    /**
     * 
     * @type {string}
     * @memberof SupplementalResultSetOptions
     */
    type?: SupplementalResultSetOptionsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SupplementalResultSetOptions
     */
    dataVersion?: SupplementalResultSetOptionsDataVersionEnum | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SupplementalResultSetOptions
     */
    hazards?: Array<SupplementalResultSetOptionsHazardsEnum> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SupplementalResultSetOptions
     */
    scenarios?: Array<SupplementalResultSetOptionsScenariosEnum> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SupplementalResultSetOptions
     */
    years?: Array<SupplementalResultSetOptionsYearsEnum> | null;
}


/**
 * @export
 */
export const SupplementalResultSetOptionsTypeEnum = {
    supplemental: 'supplemental',
    unknownDefaultOpenApi: '11184809'
} as const;
export type SupplementalResultSetOptionsTypeEnum = typeof SupplementalResultSetOptionsTypeEnum[keyof typeof SupplementalResultSetOptionsTypeEnum];

/**
 * @export
 */
export const SupplementalResultSetOptionsDataVersionEnum = {
    _010: '0.1.0',
    unknownDefaultOpenApi: '11184809'
} as const;
export type SupplementalResultSetOptionsDataVersionEnum = typeof SupplementalResultSetOptionsDataVersionEnum[keyof typeof SupplementalResultSetOptionsDataVersionEnum];

/**
 * @export
 */
export const SupplementalResultSetOptionsHazardsEnum = {
    blizzards: 'blizzards',
    coastalErosion: 'coastalErosion',
    freshWater: 'freshWater',
    landslides: 'landslides',
    marineWater: 'marineWater',
    permafrost: 'permafrost',
    soilErosion: 'soilErosion',
    subsidence: 'subsidence',
    tornadoes: 'tornadoes',
    unknownDefaultOpenApi: '11184809'
} as const;
export type SupplementalResultSetOptionsHazardsEnum = typeof SupplementalResultSetOptionsHazardsEnum[keyof typeof SupplementalResultSetOptionsHazardsEnum];

/**
 * @export
 */
export const SupplementalResultSetOptionsScenariosEnum = {
    baseline: 'baseline',
    ssp126: 'ssp126',
    ssp245: 'ssp245',
    ssp585: 'ssp585',
    unknownDefaultOpenApi: '11184809'
} as const;
export type SupplementalResultSetOptionsScenariosEnum = typeof SupplementalResultSetOptionsScenariosEnum[keyof typeof SupplementalResultSetOptionsScenariosEnum];

/**
 * @export
 */
export const SupplementalResultSetOptionsYearsEnum = {
    NUMBER_1995: 1995,
    NUMBER_2005: 2005,
    NUMBER_2010: 2010,
    NUMBER_2020: 2020,
    NUMBER_2025: 2025,
    NUMBER_2030: 2030,
    NUMBER_2035: 2035,
    NUMBER_2040: 2040,
    NUMBER_2045: 2045,
    NUMBER_2050: 2050,
    NUMBER_2055: 2055,
    NUMBER_2060: 2060,
    NUMBER_2065: 2065,
    NUMBER_2070: 2070,
    NUMBER_2075: 2075,
    NUMBER_2080: 2080,
    NUMBER_2085: 2085,
    NUMBER_2090: 2090,
    NUMBER_2095: 2095,
    NUMBER_2100: 2100,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type SupplementalResultSetOptionsYearsEnum = typeof SupplementalResultSetOptionsYearsEnum[keyof typeof SupplementalResultSetOptionsYearsEnum];


/**
 * Check if a given object implements the SupplementalResultSetOptions interface.
 */
export function instanceOfSupplementalResultSetOptions(value: object): value is SupplementalResultSetOptions {
    return true;
}

export function SupplementalResultSetOptionsFromJSON(json: any): SupplementalResultSetOptions {
    return SupplementalResultSetOptionsFromJSONTyped(json, false);
}

export function SupplementalResultSetOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplementalResultSetOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'dataVersion': json['data_version'] == null ? undefined : json['data_version'],
        'hazards': json['hazards'] == null ? undefined : json['hazards'],
        'scenarios': json['scenarios'] == null ? undefined : json['scenarios'],
        'years': json['years'] == null ? undefined : json['years'],
    };
}

export function SupplementalResultSetOptionsToJSON(value?: SupplementalResultSetOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'data_version': value['dataVersion'],
        'hazards': value['hazards'],
        'scenarios': value['scenarios'],
        'years': value['years'],
    };
}

