/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamespacedClaims } from './NamespacedClaims';
import {
    NamespacedClaimsFromJSON,
    NamespacedClaimsFromJSONTyped,
    NamespacedClaimsToJSON,
} from './NamespacedClaims';

/**
 * 
 * @export
 * @interface Claims
 */
export interface Claims {
    /**
     * 
     * @type {Array<string>}
     * @memberof Claims
     */
    customjupiterRoles: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Claims
     */
    customjupiterTenantDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof Claims
     */
    customjupiterTenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Claims
     */
    customjupiterTenantName: string;
    /**
     * 
     * @type {string}
     * @memberof Claims
     */
    customjupiterUserId: string;
    /**
     * 
     * @type {string}
     * @memberof Claims
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Claims
     */
    givenName?: string;
    /**
     * 
     * @type {NamespacedClaims}
     * @memberof Claims
     */
    namespaced: NamespacedClaims;
}

/**
 * Check if a given object implements the Claims interface.
 */
export function instanceOfClaims(value: object): value is Claims {
    if (!('customjupiterRoles' in value) || value['customjupiterRoles'] === undefined) return false;
    if (!('customjupiterTenantDisplayName' in value) || value['customjupiterTenantDisplayName'] === undefined) return false;
    if (!('customjupiterTenantId' in value) || value['customjupiterTenantId'] === undefined) return false;
    if (!('customjupiterTenantName' in value) || value['customjupiterTenantName'] === undefined) return false;
    if (!('customjupiterUserId' in value) || value['customjupiterUserId'] === undefined) return false;
    if (!('namespaced' in value) || value['namespaced'] === undefined) return false;
    return true;
}

export function ClaimsFromJSON(json: any): Claims {
    return ClaimsFromJSONTyped(json, false);
}

export function ClaimsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Claims {
    if (json == null) {
        return json;
    }
    return {
        
        'customjupiterRoles': json['custom:jupiter-roles'],
        'customjupiterTenantDisplayName': json['custom:jupiter-tenant-display-name'],
        'customjupiterTenantId': json['custom:jupiter-tenant-id'],
        'customjupiterTenantName': json['custom:jupiter-tenant-name'],
        'customjupiterUserId': json['custom:jupiter-user-id'],
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'namespaced': NamespacedClaimsFromJSON(json['namespaced']),
    };
}

export function ClaimsToJSON(value?: Claims | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'custom:jupiter-roles': value['customjupiterRoles'],
        'custom:jupiter-tenant-display-name': value['customjupiterTenantDisplayName'],
        'custom:jupiter-tenant-id': value['customjupiterTenantId'],
        'custom:jupiter-tenant-name': value['customjupiterTenantName'],
        'custom:jupiter-user-id': value['customjupiterUserId'],
        'family_name': value['familyName'],
        'given_name': value['givenName'],
        'namespaced': NamespacedClaimsToJSON(value['namespaced']),
    };
}

