/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateClientInputBody
 */
export interface CreateClientInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreateClientInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClientInputBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClientInputBody
     */
    machineUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClientInputBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClientInputBody
     */
    userId?: string;
}

/**
 * Check if a given object implements the CreateClientInputBody interface.
 */
export function instanceOfCreateClientInputBody(value: object): value is CreateClientInputBody {
    return true;
}

export function CreateClientInputBodyFromJSON(json: any): CreateClientInputBody {
    return CreateClientInputBodyFromJSONTyped(json, false);
}

export function CreateClientInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClientInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'description': json['description'] == null ? undefined : json['description'],
        'machineUserId': json['machine_user_id'] == null ? undefined : json['machine_user_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function CreateClientInputBodyToJSON(value?: Omit<CreateClientInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'machine_user_id': value['machineUserId'],
        'name': value['name'],
        'user_id': value['userId'],
    };
}

