/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { M2MClient } from './M2MClient';
import {
    M2MClientFromJSON,
    M2MClientFromJSONTyped,
    M2MClientToJSON,
} from './M2MClient';

/**
 * 
 * @export
 * @interface CreateClientOutputBody
 */
export interface CreateClientOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreateClientOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {M2MClient}
     * @memberof CreateClientOutputBody
     */
    client: M2MClient;
    /**
     * 
     * @type {string}
     * @memberof CreateClientOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the CreateClientOutputBody interface.
 */
export function instanceOfCreateClientOutputBody(value: object): value is CreateClientOutputBody {
    if (!('client' in value) || value['client'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateClientOutputBodyFromJSON(json: any): CreateClientOutputBody {
    return CreateClientOutputBodyFromJSONTyped(json, false);
}

export function CreateClientOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClientOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'client': M2MClientFromJSON(json['client']),
        'message': json['message'],
    };
}

export function CreateClientOutputBodyToJSON(value?: Omit<CreateClientOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client': M2MClientToJSON(value['client']),
        'message': value['message'],
    };
}

