/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TsOrg } from './TsOrg';
import {
    TsOrgFromJSON,
    TsOrgFromJSONTyped,
    TsOrgToJSON,
} from './TsOrg';
import type { TsUser } from './TsUser';
import {
    TsUserFromJSON,
    TsUserFromJSONTyped,
    TsUserToJSON,
} from './TsUser';

/**
 * 
 * @export
 * @interface CustomTokenResponse
 */
export interface CustomTokenResponse {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CustomTokenResponse
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomTokenResponse
     */
    creationTimeInMillis: number;
    /**
     * 
     * @type {number}
     * @memberof CustomTokenResponse
     */
    expirationTimeInMillis: number;
    /**
     * 
     * @type {string}
     * @memberof CustomTokenResponse
     */
    id: string;
    /**
     * 
     * @type {TsOrg}
     * @memberof CustomTokenResponse
     */
    org: TsOrg;
    /**
     * 
     * @type {string}
     * @memberof CustomTokenResponse
     */
    token: string;
    /**
     * 
     * @type {TsUser}
     * @memberof CustomTokenResponse
     */
    user: TsUser;
}

/**
 * Check if a given object implements the CustomTokenResponse interface.
 */
export function instanceOfCustomTokenResponse(value: object): value is CustomTokenResponse {
    if (!('creationTimeInMillis' in value) || value['creationTimeInMillis'] === undefined) return false;
    if (!('expirationTimeInMillis' in value) || value['expirationTimeInMillis'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('org' in value) || value['org'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function CustomTokenResponseFromJSON(json: any): CustomTokenResponse {
    return CustomTokenResponseFromJSONTyped(json, false);
}

export function CustomTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'creationTimeInMillis': json['creation_time_in_millis'],
        'expirationTimeInMillis': json['expiration_time_in_millis'],
        'id': json['id'],
        'org': TsOrgFromJSON(json['org']),
        'token': json['token'],
        'user': TsUserFromJSON(json['user']),
    };
}

export function CustomTokenResponseToJSON(value?: Omit<CustomTokenResponse, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'creation_time_in_millis': value['creationTimeInMillis'],
        'expiration_time_in_millis': value['expirationTimeInMillis'],
        'id': value['id'],
        'org': TsOrgToJSON(value['org']),
        'token': value['token'],
        'user': TsUserToJSON(value['user']),
    };
}

