/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineUser } from './MachineUser';
import {
    MachineUserFromJSON,
    MachineUserFromJSONTyped,
    MachineUserToJSON,
} from './MachineUser';

/**
 * 
 * @export
 * @interface DeleteMachineUserOutputBody
 */
export interface DeleteMachineUserOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DeleteMachineUserOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {MachineUser}
     * @memberof DeleteMachineUserOutputBody
     */
    machineUser: MachineUser;
    /**
     * 
     * @type {string}
     * @memberof DeleteMachineUserOutputBody
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteMachineUserOutputBody
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteMachineUserOutputBody
     */
    workflowId: string;
}

/**
 * Check if a given object implements the DeleteMachineUserOutputBody interface.
 */
export function instanceOfDeleteMachineUserOutputBody(value: object): value is DeleteMachineUserOutputBody {
    if (!('machineUser' in value) || value['machineUser'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('workflowId' in value) || value['workflowId'] === undefined) return false;
    return true;
}

export function DeleteMachineUserOutputBodyFromJSON(json: any): DeleteMachineUserOutputBody {
    return DeleteMachineUserOutputBodyFromJSONTyped(json, false);
}

export function DeleteMachineUserOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMachineUserOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'machineUser': MachineUserFromJSON(json['machine_user']),
        'message': json['message'],
        'runId': json['run_id'],
        'workflowId': json['workflow_id'],
    };
}

export function DeleteMachineUserOutputBodyToJSON(value?: Omit<DeleteMachineUserOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'machine_user': MachineUserToJSON(value['machineUser']),
        'message': value['message'],
        'run_id': value['runId'],
        'workflow_id': value['workflowId'],
    };
}

