/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tenant } from './Tenant';
import {
    TenantFromJSON,
    TenantFromJSONTyped,
    TenantToJSON,
} from './Tenant';

/**
 * 
 * @export
 * @interface DeleteTenantOutputBody
 */
export interface DeleteTenantOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DeleteTenantOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteTenantOutputBody
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteTenantOutputBody
     */
    runId: string;
    /**
     * 
     * @type {Tenant}
     * @memberof DeleteTenantOutputBody
     */
    tenant: Tenant;
    /**
     * 
     * @type {string}
     * @memberof DeleteTenantOutputBody
     */
    workflowId: string;
}

/**
 * Check if a given object implements the DeleteTenantOutputBody interface.
 */
export function instanceOfDeleteTenantOutputBody(value: object): value is DeleteTenantOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('workflowId' in value) || value['workflowId'] === undefined) return false;
    return true;
}

export function DeleteTenantOutputBodyFromJSON(json: any): DeleteTenantOutputBody {
    return DeleteTenantOutputBodyFromJSONTyped(json, false);
}

export function DeleteTenantOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTenantOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'runId': json['run_id'],
        'tenant': TenantFromJSON(json['tenant']),
        'workflowId': json['workflow_id'],
    };
}

export function DeleteTenantOutputBodyToJSON(value?: Omit<DeleteTenantOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'run_id': value['runId'],
        'tenant': TenantToJSON(value['tenant']),
        'workflow_id': value['workflowId'],
    };
}

