/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDoc360TokenOutputBody
 */
export interface GetDoc360TokenOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetDoc360TokenOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDoc360TokenOutputBody
     */
    token: string;
}

/**
 * Check if a given object implements the GetDoc360TokenOutputBody interface.
 */
export function instanceOfGetDoc360TokenOutputBody(value: object): value is GetDoc360TokenOutputBody {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function GetDoc360TokenOutputBodyFromJSON(json: any): GetDoc360TokenOutputBody {
    return GetDoc360TokenOutputBodyFromJSONTyped(json, false);
}

export function GetDoc360TokenOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDoc360TokenOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'token': json['token'],
    };
}

export function GetDoc360TokenOutputBodyToJSON(value?: Omit<GetDoc360TokenOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

