/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetThoughtSpotTokenInputBody
 */
export interface GetThoughtSpotTokenInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetThoughtSpotTokenInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetThoughtSpotTokenInputBody
     */
    pipelineIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetThoughtSpotTokenInputBody
     */
    portfolioIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetThoughtSpotTokenInputBody
     */
    resultSetIds?: Array<string>;
}

/**
 * Check if a given object implements the GetThoughtSpotTokenInputBody interface.
 */
export function instanceOfGetThoughtSpotTokenInputBody(value: object): value is GetThoughtSpotTokenInputBody {
    return true;
}

export function GetThoughtSpotTokenInputBodyFromJSON(json: any): GetThoughtSpotTokenInputBody {
    return GetThoughtSpotTokenInputBodyFromJSONTyped(json, false);
}

export function GetThoughtSpotTokenInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetThoughtSpotTokenInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'pipelineIds': json['pipeline_ids'] == null ? undefined : json['pipeline_ids'],
        'portfolioIds': json['portfolio_ids'] == null ? undefined : json['portfolio_ids'],
        'resultSetIds': json['result_set_ids'] == null ? undefined : json['result_set_ids'],
    };
}

export function GetThoughtSpotTokenInputBodyToJSON(value?: Omit<GetThoughtSpotTokenInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pipeline_ids': value['pipelineIds'],
        'portfolio_ids': value['portfolioIds'],
        'result_set_ids': value['resultSetIds'],
    };
}

