/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * 
     * @type {Date}
     * @memberof Group
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    zedToken?: string;
}

/**
 * Check if a given object implements the Group interface.
 */
export function instanceOfGroup(value: object): value is Group {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function GroupFromJSON(json: any): Group {
    return GroupFromJSONTyped(json, false);
}

export function GroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Group {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tenantId': json['tenant_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'zedToken': json['zed_token'] == null ? undefined : json['zed_token'],
    };
}

export function GroupToJSON(value?: Group | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'created_by': value['createdBy'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'tenant_id': value['tenantId'],
        'updated_at': value['updatedAt'],
        'updated_by': value['updatedBy'],
        'zed_token': value['zedToken'],
    };
}

