/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantResponse } from './TenantResponse';
import {
    TenantResponseFromJSON,
    TenantResponseFromJSONTyped,
    TenantResponseToJSON,
} from './TenantResponse';

/**
 * 
 * @export
 * @interface HandleTenantResponseOutputBody
 */
export interface HandleTenantResponseOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof HandleTenantResponseOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof HandleTenantResponseOutputBody
     */
    message: string;
    /**
     * 
     * @type {TenantResponse}
     * @memberof HandleTenantResponseOutputBody
     */
    tenant: TenantResponse;
}

/**
 * Check if a given object implements the HandleTenantResponseOutputBody interface.
 */
export function instanceOfHandleTenantResponseOutputBody(value: object): value is HandleTenantResponseOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    return true;
}

export function HandleTenantResponseOutputBodyFromJSON(json: any): HandleTenantResponseOutputBody {
    return HandleTenantResponseOutputBodyFromJSONTyped(json, false);
}

export function HandleTenantResponseOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleTenantResponseOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'tenant': TenantResponseFromJSON(json['tenant']),
    };
}

export function HandleTenantResponseOutputBodyToJSON(value?: Omit<HandleTenantResponseOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'tenant': TenantResponseToJSON(value['tenant']),
    };
}

