/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface HandleUserOutputBody
 */
export interface HandleUserOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof HandleUserOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof HandleUserOutputBody
     */
    message: string;
    /**
     * 
     * @type {User}
     * @memberof HandleUserOutputBody
     */
    user: User;
}

/**
 * Check if a given object implements the HandleUserOutputBody interface.
 */
export function instanceOfHandleUserOutputBody(value: object): value is HandleUserOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function HandleUserOutputBodyFromJSON(json: any): HandleUserOutputBody {
    return HandleUserOutputBodyFromJSONTyped(json, false);
}

export function HandleUserOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleUserOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'user': UserFromJSON(json['user']),
    };
}

export function HandleUserOutputBodyToJSON(value?: Omit<HandleUserOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'user': UserToJSON(value['user']),
    };
}

