/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineUser } from './MachineUser';
import {
    MachineUserFromJSON,
    MachineUserFromJSONTyped,
    MachineUserToJSON,
} from './MachineUser';

/**
 * 
 * @export
 * @interface HandleMachineUserOutputBody
 */
export interface HandleMachineUserOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof HandleMachineUserOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {MachineUser}
     * @memberof HandleMachineUserOutputBody
     */
    machineUser: MachineUser;
    /**
     * 
     * @type {string}
     * @memberof HandleMachineUserOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the HandleMachineUserOutputBody interface.
 */
export function instanceOfHandleMachineUserOutputBody(value: object): value is HandleMachineUserOutputBody {
    if (!('machineUser' in value) || value['machineUser'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function HandleMachineUserOutputBodyFromJSON(json: any): HandleMachineUserOutputBody {
    return HandleMachineUserOutputBodyFromJSONTyped(json, false);
}

export function HandleMachineUserOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleMachineUserOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'machineUser': MachineUserFromJSON(json['machine_user']),
        'message': json['message'],
    };
}

export function HandleMachineUserOutputBodyToJSON(value?: Omit<HandleMachineUserOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'machine_user': MachineUserToJSON(value['machineUser']),
        'message': value['message'],
    };
}

