/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InputClient
 */
export interface InputClient {
    /**
     * 
     * @type {string}
     * @memberof InputClient
     */
    clientId?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof InputClient
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof InputClient
     */
    name?: string;
}

/**
 * Check if a given object implements the InputClient interface.
 */
export function instanceOfInputClient(value: object): value is InputClient {
    return true;
}

export function InputClientFromJSON(json: any): InputClient {
    return InputClientFromJSONTyped(json, false);
}

export function InputClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputClient {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function InputClientToJSON(value?: InputClient | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_id': value['clientId'],
        'metadata': value['metadata'],
        'name': value['name'],
    };
}

