/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InputOrganization
 */
export interface InputOrganization {
    /**
     * 
     * @type {string}
     * @memberof InputOrganization
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof InputOrganization
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof InputOrganization
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof InputOrganization
     */
    name?: string;
}

/**
 * Check if a given object implements the InputOrganization interface.
 */
export function instanceOfInputOrganization(value: object): value is InputOrganization {
    return true;
}

export function InputOrganizationFromJSON(json: any): InputOrganization {
    return InputOrganizationFromJSONTyped(json, false);
}

export function InputOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'id': json['id'] == null ? undefined : json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function InputOrganizationToJSON(value?: InputOrganization | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'display_name': value['displayName'],
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
    };
}

