/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListOptions
 */
export interface ListOptions {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ListOptions
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof ListOptions
     */
    cursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListOptions
     */
    deleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListOptions
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ListOptions
     */
    sortOrder?: ListOptionsSortOrderEnum;
    /**
     * 
     * @type {string}
     * @memberof ListOptions
     */
    status?: ListOptionsStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ListOptions
     */
    type?: ListOptionsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ListOptions
     */
    zedToken?: string;
}


/**
 * @export
 */
export const ListOptionsSortOrderEnum = {
    asc: 'asc',
    desc: 'desc',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListOptionsSortOrderEnum = typeof ListOptionsSortOrderEnum[keyof typeof ListOptionsSortOrderEnum];

/**
 * @export
 */
export const ListOptionsStatusEnum = {
    pending: 'pending',
    failed: 'failed',
    ready: 'ready',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListOptionsStatusEnum = typeof ListOptionsStatusEnum[keyof typeof ListOptionsStatusEnum];

/**
 * @export
 */
export const ListOptionsTypeEnum = {
    app: 'app',
    trial: 'trial',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListOptionsTypeEnum = typeof ListOptionsTypeEnum[keyof typeof ListOptionsTypeEnum];


/**
 * Check if a given object implements the ListOptions interface.
 */
export function instanceOfListOptions(value: object): value is ListOptions {
    return true;
}

export function ListOptionsFromJSON(json: any): ListOptions {
    return ListOptionsFromJSONTyped(json, false);
}

export function ListOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOptions {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
        'zedToken': json['zed_token'] == null ? undefined : json['zed_token'],
    };
}

export function ListOptionsToJSON(value?: Omit<ListOptions, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cursor': value['cursor'],
        'deleted': value['deleted'],
        'page_size': value['pageSize'],
        'sort_order': value['sortOrder'],
        'status': value['status'],
        'type': value['type'],
        'zed_token': value['zedToken'],
    };
}

