/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListM2MClientOptions
 */
export interface ListM2MClientOptions {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ListM2MClientOptions
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof ListM2MClientOptions
     */
    cursor?: string;
    /**
     * 
     * @type {number}
     * @memberof ListM2MClientOptions
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ListM2MClientOptions
     */
    sortOrder?: ListM2MClientOptionsSortOrderEnum;
    /**
     * 
     * @type {string}
     * @memberof ListM2MClientOptions
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListM2MClientOptions
     */
    zedToken?: string;
}


/**
 * @export
 */
export const ListM2MClientOptionsSortOrderEnum = {
    asc: 'asc',
    desc: 'desc',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListM2MClientOptionsSortOrderEnum = typeof ListM2MClientOptionsSortOrderEnum[keyof typeof ListM2MClientOptionsSortOrderEnum];


/**
 * Check if a given object implements the ListM2MClientOptions interface.
 */
export function instanceOfListM2MClientOptions(value: object): value is ListM2MClientOptions {
    return true;
}

export function ListM2MClientOptionsFromJSON(json: any): ListM2MClientOptions {
    return ListM2MClientOptionsFromJSONTyped(json, false);
}

export function ListM2MClientOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListM2MClientOptions {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'zedToken': json['zed_token'] == null ? undefined : json['zed_token'],
    };
}

export function ListM2MClientOptionsToJSON(value?: Omit<ListM2MClientOptions, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cursor': value['cursor'],
        'page_size': value['pageSize'],
        'sort_order': value['sortOrder'],
        'user_id': value['userId'],
        'zed_token': value['zedToken'],
    };
}

