/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListUserOptions
 */
export interface ListUserOptions {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ListUserOptions
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof ListUserOptions
     */
    cursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListUserOptions
     */
    deleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListUserOptions
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ListUserOptions
     */
    sortOrder?: ListUserOptionsSortOrderEnum;
    /**
     * 
     * @type {string}
     * @memberof ListUserOptions
     */
    status?: ListUserOptionsStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ListUserOptions
     */
    tenant?: string;
    /**
     * 
     * @type {string}
     * @memberof ListUserOptions
     */
    zedToken?: string;
}


/**
 * @export
 */
export const ListUserOptionsSortOrderEnum = {
    asc: 'asc',
    desc: 'desc',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListUserOptionsSortOrderEnum = typeof ListUserOptionsSortOrderEnum[keyof typeof ListUserOptionsSortOrderEnum];

/**
 * @export
 */
export const ListUserOptionsStatusEnum = {
    pending: 'pending',
    failed: 'failed',
    ready: 'ready',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListUserOptionsStatusEnum = typeof ListUserOptionsStatusEnum[keyof typeof ListUserOptionsStatusEnum];


/**
 * Check if a given object implements the ListUserOptions interface.
 */
export function instanceOfListUserOptions(value: object): value is ListUserOptions {
    return true;
}

export function ListUserOptionsFromJSON(json: any): ListUserOptions {
    return ListUserOptionsFromJSONTyped(json, false);
}

export function ListUserOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUserOptions {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'status': json['status'] == null ? undefined : json['status'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'zedToken': json['zed_token'] == null ? undefined : json['zed_token'],
    };
}

export function ListUserOptionsToJSON(value?: Omit<ListUserOptions, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cursor': value['cursor'],
        'deleted': value['deleted'],
        'page_size': value['pageSize'],
        'sort_order': value['sortOrder'],
        'status': value['status'],
        'tenant': value['tenant'],
        'zed_token': value['zedToken'],
    };
}

