/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Claims } from './Claims';
import {
    ClaimsFromJSON,
    ClaimsFromJSONTyped,
    ClaimsToJSON,
} from './Claims';

/**
 * 
 * @export
 * @interface LoginFlowOutputBody
 */
export interface LoginFlowOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LoginFlowOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Claims}
     * @memberof LoginFlowOutputBody
     */
    claims: Claims;
}

/**
 * Check if a given object implements the LoginFlowOutputBody interface.
 */
export function instanceOfLoginFlowOutputBody(value: object): value is LoginFlowOutputBody {
    if (!('claims' in value) || value['claims'] === undefined) return false;
    return true;
}

export function LoginFlowOutputBodyFromJSON(json: any): LoginFlowOutputBody {
    return LoginFlowOutputBodyFromJSONTyped(json, false);
}

export function LoginFlowOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginFlowOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'claims': ClaimsFromJSON(json['claims']),
    };
}

export function LoginFlowOutputBodyToJSON(value?: Omit<LoginFlowOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'claims': ClaimsToJSON(value['claims']),
    };
}

