/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputOrganization } from './InputOrganization';
import {
    InputOrganizationFromJSON,
    InputOrganizationFromJSONTyped,
    InputOrganizationToJSON,
} from './InputOrganization';
import type { InputUser } from './InputUser';
import {
    InputUserFromJSON,
    InputUserFromJSONTyped,
    InputUserToJSON,
} from './InputUser';
import type { InputClient } from './InputClient';
import {
    InputClientFromJSON,
    InputClientFromJSONTyped,
    InputClientToJSON,
} from './InputClient';

/**
 * 
 * @export
 * @interface LoginFlowInputBody
 */
export interface LoginFlowInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LoginFlowInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {InputClient}
     * @memberof LoginFlowInputBody
     */
    client?: InputClient;
    /**
     * 
     * @type {InputOrganization}
     * @memberof LoginFlowInputBody
     */
    organization?: InputOrganization;
    /**
     * 
     * @type {InputUser}
     * @memberof LoginFlowInputBody
     */
    user: InputUser;
}

/**
 * Check if a given object implements the LoginFlowInputBody interface.
 */
export function instanceOfLoginFlowInputBody(value: object): value is LoginFlowInputBody {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function LoginFlowInputBodyFromJSON(json: any): LoginFlowInputBody {
    return LoginFlowInputBodyFromJSONTyped(json, false);
}

export function LoginFlowInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginFlowInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'client': json['client'] == null ? undefined : InputClientFromJSON(json['client']),
        'organization': json['organization'] == null ? undefined : InputOrganizationFromJSON(json['organization']),
        'user': InputUserFromJSON(json['user']),
    };
}

export function LoginFlowInputBodyToJSON(value?: Omit<LoginFlowInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client': InputClientToJSON(value['client']),
        'organization': InputOrganizationToJSON(value['organization']),
        'user': InputUserToJSON(value['user']),
    };
}

