/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface M2MClient
 */
export interface M2MClient {
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    auth0Id?: string;
    /**
     * 
     * @type {Date}
     * @memberof M2MClient
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    machineUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof M2MClient
     */
    zedToken?: string;
}

/**
 * Check if a given object implements the M2MClient interface.
 */
export function instanceOfM2MClient(value: object): value is M2MClient {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function M2MClientFromJSON(json: any): M2MClient {
    return M2MClientFromJSONTyped(json, false);
}

export function M2MClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): M2MClient {
    if (json == null) {
        return json;
    }
    return {
        
        'auth0Id': json['auth0_id'] == null ? undefined : json['auth0_id'],
        'createdAt': (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'machineUserId': json['machine_user_id'] == null ? undefined : json['machine_user_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tenantId': json['tenant_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'zedToken': json['zed_token'] == null ? undefined : json['zed_token'],
    };
}

export function M2MClientToJSON(value?: M2MClient | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'auth0_id': value['auth0Id'],
        'created_at': ((value['createdAt']).toISOString()),
        'created_by': value['createdBy'],
        'description': value['description'],
        'id': value['id'],
        'machine_user_id': value['machineUserId'],
        'name': value['name'],
        'tenant_id': value['tenantId'],
        'updated_at': value['updatedAt'],
        'updated_by': value['updatedBy'],
        'user_id': value['userId'],
        'zed_token': value['zedToken'],
    };
}

