/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface M2MFlowInputClient
 */
export interface M2MFlowInputClient {
    /**
     * 
     * @type {string}
     * @memberof M2MFlowInputClient
     */
    clientId: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof M2MFlowInputClient
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof M2MFlowInputClient
     */
    name?: string;
}

/**
 * Check if a given object implements the M2MFlowInputClient interface.
 */
export function instanceOfM2MFlowInputClient(value: object): value is M2MFlowInputClient {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    return true;
}

export function M2MFlowInputClientFromJSON(json: any): M2MFlowInputClient {
    return M2MFlowInputClientFromJSONTyped(json, false);
}

export function M2MFlowInputClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): M2MFlowInputClient {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function M2MFlowInputClientToJSON(value?: M2MFlowInputClient | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_id': value['clientId'],
        'metadata': value['metadata'],
        'name': value['name'],
    };
}

