/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineUser
 */
export interface MachineUser {
    /**
     * 
     * @type {Date}
     * @memberof MachineUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    deletedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    deletedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof MachineUser
     */
    lastActivity: Date;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MachineUser
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineUser
     */
    zedToken?: string;
}

/**
 * Check if a given object implements the MachineUser interface.
 */
export function instanceOfMachineUser(value: object): value is MachineUser {
    if (!('lastActivity' in value) || value['lastActivity'] === undefined) return false;
    return true;
}

export function MachineUserFromJSON(json: any): MachineUser {
    return MachineUserFromJSONTyped(json, false);
}

export function MachineUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineUser {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (isNaN(json['created_at']) ? (new Date(json['created_at'])) : (new Date(1000 * json['created_at']))),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : json['deleted_at'],
        'deletedBy': json['deleted_by'] == null ? undefined : json['deleted_by'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastActivity': (new Date(json['last_activity'])),
        'name': json['name'] == null ? undefined : json['name'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'status': json['status'] == null ? undefined : json['status'],
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'zedToken': json['zed_token'] == null ? undefined : json['zed_token'],
    };
}

export function MachineUserToJSON(value?: MachineUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'created_by': value['createdBy'],
        'deleted_at': value['deletedAt'],
        'deleted_by': value['deletedBy'],
        'description': value['description'],
        'id': value['id'],
        'last_activity': ((value['lastActivity']).toISOString()),
        'name': value['name'],
        'roles': value['roles'],
        'status': value['status'],
        'tenant_id': value['tenantId'],
        'updated_at': value['updatedAt'],
        'updated_by': value['updatedBy'],
        'zed_token': value['zedToken'],
    };
}

