/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputBody
 */
export interface OutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof OutputBody
     */
    readonly $schema?: string;
    /**
     * Health Check
     * @type {string}
     * @memberof OutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the OutputBody interface.
 */
export function instanceOfOutputBody(value: object): value is OutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function OutputBodyFromJSON(json: any): OutputBody {
    return OutputBodyFromJSONTyped(json, false);
}

export function OutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
    };
}

export function OutputBodyToJSON(value?: Omit<OutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

