/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantResponse } from './TenantResponse';
import {
    TenantResponseFromJSON,
    TenantResponseFromJSONTyped,
    TenantResponseToJSON,
} from './TenantResponse';

/**
 * 
 * @export
 * @interface PaginatedTenantResultResponse
 */
export interface PaginatedTenantResultResponse {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PaginatedTenantResultResponse
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedTenantResultResponse
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {Array<TenantResponse>}
     * @memberof PaginatedTenantResultResponse
     */
    items: Array<TenantResponse>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTenantResultResponse
     */
    nextCursor: string;
}

/**
 * Check if a given object implements the PaginatedTenantResultResponse interface.
 */
export function instanceOfPaginatedTenantResultResponse(value: object): value is PaginatedTenantResultResponse {
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function PaginatedTenantResultResponseFromJSON(json: any): PaginatedTenantResultResponse {
    return PaginatedTenantResultResponseFromJSONTyped(json, false);
}

export function PaginatedTenantResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTenantResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'hasNextPage': json['has_next_page'],
        'items': ((json['items'] as Array<any>).map(TenantResponseFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function PaginatedTenantResultResponseToJSON(value?: Omit<PaginatedTenantResultResponse, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_next_page': value['hasNextPage'],
        'items': ((value['items'] as Array<any>).map(TenantResponseToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

