/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupResponse } from './GroupResponse';
import {
    GroupResponseFromJSON,
    GroupResponseFromJSONTyped,
    GroupResponseToJSON,
} from './GroupResponse';

/**
 * 
 * @export
 * @interface PaginatedGroupResultResponse
 */
export interface PaginatedGroupResultResponse {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PaginatedGroupResultResponse
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedGroupResultResponse
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {Array<GroupResponse>}
     * @memberof PaginatedGroupResultResponse
     */
    items: Array<GroupResponse>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGroupResultResponse
     */
    nextCursor: string;
}

/**
 * Check if a given object implements the PaginatedGroupResultResponse interface.
 */
export function instanceOfPaginatedGroupResultResponse(value: object): value is PaginatedGroupResultResponse {
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function PaginatedGroupResultResponseFromJSON(json: any): PaginatedGroupResultResponse {
    return PaginatedGroupResultResponseFromJSONTyped(json, false);
}

export function PaginatedGroupResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGroupResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'hasNextPage': json['has_next_page'],
        'items': ((json['items'] as Array<any>).map(GroupResponseFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function PaginatedGroupResultResponseToJSON(value?: Omit<PaginatedGroupResultResponse, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_next_page': value['hasNextPage'],
        'items': ((value['items'] as Array<any>).map(GroupResponseToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

