/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { M2MClient } from './M2MClient';
import {
    M2MClientFromJSON,
    M2MClientFromJSONTyped,
    M2MClientToJSON,
} from './M2MClient';

/**
 * 
 * @export
 * @interface PaginatedClientResult
 */
export interface PaginatedClientResult {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PaginatedClientResult
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedClientResult
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {Array<M2MClient>}
     * @memberof PaginatedClientResult
     */
    items: Array<M2MClient>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedClientResult
     */
    nextCursor: string;
}

/**
 * Check if a given object implements the PaginatedClientResult interface.
 */
export function instanceOfPaginatedClientResult(value: object): value is PaginatedClientResult {
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function PaginatedClientResultFromJSON(json: any): PaginatedClientResult {
    return PaginatedClientResultFromJSONTyped(json, false);
}

export function PaginatedClientResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedClientResult {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'hasNextPage': json['has_next_page'],
        'items': ((json['items'] as Array<any>).map(M2MClientFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function PaginatedClientResultToJSON(value?: Omit<PaginatedClientResult, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'has_next_page': value['hasNextPage'],
        'items': ((value['items'] as Array<any>).map(M2MClientToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

