/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreUserRegistrationFlowInputUser
 */
export interface PreUserRegistrationFlowInputUser {
    /**
     * 
     * @type {string}
     * @memberof PreUserRegistrationFlowInputUser
     */
    email: string;
}

/**
 * Check if a given object implements the PreUserRegistrationFlowInputUser interface.
 */
export function instanceOfPreUserRegistrationFlowInputUser(value: object): value is PreUserRegistrationFlowInputUser {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function PreUserRegistrationFlowInputUserFromJSON(json: any): PreUserRegistrationFlowInputUser {
    return PreUserRegistrationFlowInputUserFromJSONTyped(json, false);
}

export function PreUserRegistrationFlowInputUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreUserRegistrationFlowInputUser {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function PreUserRegistrationFlowInputUserToJSON(value?: PreUserRegistrationFlowInputUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

