/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreUserRegistrationFlowOutputBody
 */
export interface PreUserRegistrationFlowOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PreUserRegistrationFlowOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof PreUserRegistrationFlowOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the PreUserRegistrationFlowOutputBody interface.
 */
export function instanceOfPreUserRegistrationFlowOutputBody(value: object): value is PreUserRegistrationFlowOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PreUserRegistrationFlowOutputBodyFromJSON(json: any): PreUserRegistrationFlowOutputBody {
    return PreUserRegistrationFlowOutputBodyFromJSONTyped(json, false);
}

export function PreUserRegistrationFlowOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreUserRegistrationFlowOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
    };
}

export function PreUserRegistrationFlowOutputBodyToJSON(value?: Omit<PreUserRegistrationFlowOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

