/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRoleRelationsInputBody
 */
export interface UpdateRoleRelationsInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateRoleRelationsInputBody
     */
    readonly $schema?: string;
    /**
     * List of user IDs to assign to this role. Must contain unique items.
     * @type {Set<string>}
     * @memberof UpdateRoleRelationsInputBody
     */
    addMembers?: Set<string>;
    /**
     * List of new permissions and capabilities to grant to this role. Must contain unique items.
     * @type {Set<string>}
     * @memberof UpdateRoleRelationsInputBody
     */
    addRelations?: Set<string>;
    /**
     * List of user IDs to unassign from this role. Must contain unique items.
     * @type {Set<string>}
     * @memberof UpdateRoleRelationsInputBody
     */
    removeMembers?: Set<string>;
    /**
     * List of existing permissions and capabilities to revoke from this role. Must contain unique items.
     * @type {Set<string>}
     * @memberof UpdateRoleRelationsInputBody
     */
    removeRelations?: Set<string>;
}

/**
 * Check if a given object implements the UpdateRoleRelationsInputBody interface.
 */
export function instanceOfUpdateRoleRelationsInputBody(value: object): value is UpdateRoleRelationsInputBody {
    return true;
}

export function UpdateRoleRelationsInputBodyFromJSON(json: any): UpdateRoleRelationsInputBody {
    return UpdateRoleRelationsInputBodyFromJSONTyped(json, false);
}

export function UpdateRoleRelationsInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoleRelationsInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'addMembers': json['add_members'] == null ? undefined : json['add_members'],
        'addRelations': json['add_relations'] == null ? undefined : json['add_relations'],
        'removeMembers': json['remove_members'] == null ? undefined : json['remove_members'],
        'removeRelations': json['remove_relations'] == null ? undefined : json['remove_relations'],
    };
}

export function UpdateRoleRelationsInputBodyToJSON(value?: Omit<UpdateRoleRelationsInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'add_members': value['addMembers'] == null ? undefined : Array.from(value['addMembers'] as Set<any>),
        'add_relations': value['addRelations'] == null ? undefined : Array.from(value['addRelations'] as Set<any>),
        'remove_members': value['removeMembers'] == null ? undefined : Array.from(value['removeMembers'] as Set<any>),
        'remove_relations': value['removeRelations'] == null ? undefined : Array.from(value['removeRelations'] as Set<any>),
    };
}

