/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTenantInputBody
 */
export interface UpdateTenantInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateTenantInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTenantInputBody
     */
    deleteProtected?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantInputBody
     */
    displayName?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof UpdateTenantInputBody
     */
    domains?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof UpdateTenantInputBody
     */
    roles?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantInputBody
     */
    type?: UpdateTenantInputBodyTypeEnum;
}


/**
 * @export
 */
export const UpdateTenantInputBodyTypeEnum = {
    app: 'app',
    trial: 'trial',
    unknownDefaultOpenApi: '11184809'
} as const;
export type UpdateTenantInputBodyTypeEnum = typeof UpdateTenantInputBodyTypeEnum[keyof typeof UpdateTenantInputBodyTypeEnum];


/**
 * Check if a given object implements the UpdateTenantInputBody interface.
 */
export function instanceOfUpdateTenantInputBody(value: object): value is UpdateTenantInputBody {
    return true;
}

export function UpdateTenantInputBodyFromJSON(json: any): UpdateTenantInputBody {
    return UpdateTenantInputBodyFromJSONTyped(json, false);
}

export function UpdateTenantInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTenantInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'deleteProtected': json['delete_protected'] == null ? undefined : json['delete_protected'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'domains': json['domains'] == null ? undefined : json['domains'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function UpdateTenantInputBodyToJSON(value?: Omit<UpdateTenantInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'delete_protected': value['deleteProtected'],
        'display_name': value['displayName'],
        'domains': value['domains'] == null ? undefined : Array.from(value['domains'] as Set<any>),
        'roles': value['roles'] == null ? undefined : Array.from(value['roles'] as Set<any>),
        'type': value['type'],
    };
}

