/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMachineUserInputBody
 */
export interface UpdateMachineUserInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateMachineUserInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMachineUserInputBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMachineUserInputBody
     */
    name?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof UpdateMachineUserInputBody
     */
    roles?: Set<string>;
}

/**
 * Check if a given object implements the UpdateMachineUserInputBody interface.
 */
export function instanceOfUpdateMachineUserInputBody(value: object): value is UpdateMachineUserInputBody {
    return true;
}

export function UpdateMachineUserInputBodyFromJSON(json: any): UpdateMachineUserInputBody {
    return UpdateMachineUserInputBodyFromJSONTyped(json, false);
}

export function UpdateMachineUserInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMachineUserInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'roles': json['roles'] == null ? undefined : json['roles'],
    };
}

export function UpdateMachineUserInputBodyToJSON(value?: Omit<UpdateMachineUserInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
        'roles': value['roles'] == null ? undefined : Array.from(value['roles'] as Set<any>),
    };
}

