/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePlatformRelationInput
 */
export interface UpdatePlatformRelationInput {
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatePlatformRelationInput
     */
    addMembers?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlatformRelationInput
     */
    relation: UpdatePlatformRelationInputRelationEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatePlatformRelationInput
     */
    removeMembers?: Array<string>;
}


/**
 * @export
 */
export const UpdatePlatformRelationInputRelationEnum = {
    admin: 'admin',
    manager: 'manager',
    reader: 'reader',
    unknownDefaultOpenApi: '11184809'
} as const;
export type UpdatePlatformRelationInputRelationEnum = typeof UpdatePlatformRelationInputRelationEnum[keyof typeof UpdatePlatformRelationInputRelationEnum];


/**
 * Check if a given object implements the UpdatePlatformRelationInput interface.
 */
export function instanceOfUpdatePlatformRelationInput(value: object): value is UpdatePlatformRelationInput {
    if (!('relation' in value) || value['relation'] === undefined) return false;
    return true;
}

export function UpdatePlatformRelationInputFromJSON(json: any): UpdatePlatformRelationInput {
    return UpdatePlatformRelationInputFromJSONTyped(json, false);
}

export function UpdatePlatformRelationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePlatformRelationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'addMembers': json['add_members'] == null ? undefined : json['add_members'],
        'relation': json['relation'],
        'removeMembers': json['remove_members'] == null ? undefined : json['remove_members'],
    };
}

export function UpdatePlatformRelationInputToJSON(value?: UpdatePlatformRelationInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'add_members': value['addMembers'],
        'relation': value['relation'],
        'remove_members': value['removeMembers'],
    };
}

