/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageSummaryMetrics
 */
export interface UsageSummaryMetrics {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UsageSummaryMetrics
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageSummaryMetrics
     */
    categoryName?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageSummaryMetrics
     */
    dateRange: string;
    /**
     * 
     * @type {string}
     * @memberof UsageSummaryMetrics
     */
    tenantId?: string;
    /**
     * 
     * @type {number}
     * @memberof UsageSummaryMetrics
     */
    totalExecutions: number;
    /**
     * 
     * @type {number}
     * @memberof UsageSummaryMetrics
     */
    totalPortfolios: number;
    /**
     * 
     * @type {number}
     * @memberof UsageSummaryMetrics
     */
    totalResultSets: number;
    /**
     * 
     * @type {number}
     * @memberof UsageSummaryMetrics
     */
    totalUniqueLocations: number;
    /**
     * 
     * @type {number}
     * @memberof UsageSummaryMetrics
     */
    totalUniqueUsers: number;
    /**
     * 
     * @type {string}
     * @memberof UsageSummaryMetrics
     */
    userId?: string;
}

/**
 * Check if a given object implements the UsageSummaryMetrics interface.
 */
export function instanceOfUsageSummaryMetrics(value: object): value is UsageSummaryMetrics {
    if (!('dateRange' in value) || value['dateRange'] === undefined) return false;
    if (!('totalExecutions' in value) || value['totalExecutions'] === undefined) return false;
    if (!('totalPortfolios' in value) || value['totalPortfolios'] === undefined) return false;
    if (!('totalResultSets' in value) || value['totalResultSets'] === undefined) return false;
    if (!('totalUniqueLocations' in value) || value['totalUniqueLocations'] === undefined) return false;
    if (!('totalUniqueUsers' in value) || value['totalUniqueUsers'] === undefined) return false;
    return true;
}

export function UsageSummaryMetricsFromJSON(json: any): UsageSummaryMetrics {
    return UsageSummaryMetricsFromJSONTyped(json, false);
}

export function UsageSummaryMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageSummaryMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'categoryName': json['category_name'] == null ? undefined : json['category_name'],
        'dateRange': json['date_range'],
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'totalExecutions': json['total_executions'],
        'totalPortfolios': json['total_portfolios'],
        'totalResultSets': json['total_result_sets'],
        'totalUniqueLocations': json['total_unique_locations'],
        'totalUniqueUsers': json['total_unique_users'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function UsageSummaryMetricsToJSON(value?: Omit<UsageSummaryMetrics, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'category_name': value['categoryName'],
        'date_range': value['dateRange'],
        'tenant_id': value['tenantId'],
        'total_executions': value['totalExecutions'],
        'total_portfolios': value['totalPortfolios'],
        'total_result_sets': value['totalResultSets'],
        'total_unique_locations': value['totalUniqueLocations'],
        'total_unique_users': value['totalUniqueUsers'],
        'user_id': value['userId'],
    };
}

