export enum LocationFinancialMetric {
    NetOperatingIncome = 'NetOperatingIncome',
    TechnicalPremium = 'TechnicalPremium',
    BenchmarkAssetValue = 'BenchmarkAssetValue',
    ClimateAdjustedAssetValue = 'ClimateAdjustedAssetValue',
    TotalClimateRiskAdjustment = 'TotalClimateRiskAdjustment',
    OperationalExpenses = 'OperationalExpenses',
    OperationalRevenue = 'OperationalRevenue',
    CapitalExpenditures = 'CapitalExpenditures',
    CostOfOwnership = 'CostOfOwnership',
    AverageAnnualLoss = 'AverageAnnualLoss',
    AverageAnnualLossFlood = 'AverageAnnualLossFlood',
    AverageAnnualLossWind = 'AverageAnnualLossWind',
    AverageAnnualLossHeat = 'AverageAnnualLossHeat',
    AverageAnnualLossWildfire = 'AverageAnnualLossWildfire',
    AverageAnnualLossDrought = 'AverageAnnualLossDrought',
    ProbabilityValueAtRiskWith20YearsReturnPeriod = 'ProbabilityValueAtRiskWith20YearsReturnPeriod',
    ProbabilityValueAtRiskWith100YearsReturnPeriod = 'ProbabilityValueAtRiskWith100YearsReturnPeriod',
}
