/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGroupInputBody,
  ErrorModel,
  GetGroupOutputBody,
  HandleGroupOutputBody,
  PaginatedGroupResultResponse,
  UpdateGroupInputBody,
  UpdateGroupRelationsInputBody,
} from '../models/index';
import {
    CreateGroupInputBodyFromJSON,
    CreateGroupInputBodyToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetGroupOutputBodyFromJSON,
    GetGroupOutputBodyToJSON,
    HandleGroupOutputBodyFromJSON,
    HandleGroupOutputBodyToJSON,
    PaginatedGroupResultResponseFromJSON,
    PaginatedGroupResultResponseToJSON,
    UpdateGroupInputBodyFromJSON,
    UpdateGroupInputBodyToJSON,
    UpdateGroupRelationsInputBodyFromJSON,
    UpdateGroupRelationsInputBodyToJSON,
} from '../models/index';

export interface CreateGroupRequest {
    createGroupInputBody: Omit<CreateGroupInputBody, '$schema'>;
}

export interface DeleteGroupRequest {
    id: string;
}

export interface GetGroupRequest {
    id: string;
}

export interface ListGroupsRequest {
    zedToken?: string;
    tenantId?: string;
    cursor?: string;
    pageSize?: number;
    sortOrder?: ListGroupsSortOrderEnum;
}

export interface UpdateGroupRequest {
    id: string;
    updateGroupInputBody: Omit<UpdateGroupInputBody, '$schema'>;
}

export interface UpdateGroupRelationsRequest {
    id: string;
    updateGroupRelationsInputBody: Omit<UpdateGroupRelationsInputBody, '$schema'>;
}

/**
 * 
 */
export class GroupApi extends runtime.BaseAPI {

    /**
     * Creates a new group
     * Create Group
     */
    async createGroupRaw(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleGroupOutputBody>> {
        if (requestParameters['createGroupInputBody'] == null) {
            throw new runtime.RequiredError(
                'createGroupInputBody',
                'Required parameter "createGroupInputBody" was null or undefined when calling createGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/groups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGroupInputBodyToJSON(requestParameters['createGroupInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleGroupOutputBodyFromJSON(jsonValue));
    }

    /**
     * Creates a new group
     * Create Group
     */
    async createGroup(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleGroupOutputBody> {
        const response = await this.createGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a Group
     * Delete Group
     */
    async deleteGroupRaw(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a Group
     * Delete Group
     */
    async deleteGroup(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteGroupRaw(requestParameters, initOverrides);
    }

    /**
     * Gets a Group
     * Get a Group
     */
    async getGroupRaw(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGroupOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGroupOutputBodyFromJSON(jsonValue));
    }

    /**
     * Gets a Group
     * Get a Group
     */
    async getGroup(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGroupOutputBody> {
        const response = await this.getGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists Groups
     * List Groups
     */
    async listGroupsRaw(requestParameters: ListGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedGroupResultResponse>> {
        const queryParameters: any = {};

        if (requestParameters['zedToken'] != null) {
            queryParameters['zed_token'] = requestParameters['zedToken'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenant_id'] = requestParameters['tenantId'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sort_order'] = requestParameters['sortOrder'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/groups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedGroupResultResponseFromJSON(jsonValue));
    }

    /**
     * Lists Groups
     * List Groups
     */
    async listGroups(requestParameters: ListGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedGroupResultResponse> {
        const response = await this.listGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a Group
     * Update Group
     */
    async updateGroupRaw(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleGroupOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateGroup().'
            );
        }

        if (requestParameters['updateGroupInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateGroupInputBody',
                'Required parameter "updateGroupInputBody" was null or undefined when calling updateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGroupInputBodyToJSON(requestParameters['updateGroupInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleGroupOutputBodyFromJSON(jsonValue));
    }

    /**
     * Updates a Group
     * Update Group
     */
    async updateGroup(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleGroupOutputBody> {
        const response = await this.updateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a group\'s relations
     * Update Group Relations
     */
    async updateGroupRelationsRaw(requestParameters: UpdateGroupRelationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleGroupOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateGroupRelations().'
            );
        }

        if (requestParameters['updateGroupRelationsInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateGroupRelationsInputBody',
                'Required parameter "updateGroupRelationsInputBody" was null or undefined when calling updateGroupRelations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/groups/{id}/relations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGroupRelationsInputBodyToJSON(requestParameters['updateGroupRelationsInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleGroupOutputBodyFromJSON(jsonValue));
    }

    /**
     * Updates a group\'s relations
     * Update Group Relations
     */
    async updateGroupRelations(requestParameters: UpdateGroupRelationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleGroupOutputBody> {
        const response = await this.updateGroupRelationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListGroupsSortOrderEnum = {
    asc: 'asc',
    desc: 'desc',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListGroupsSortOrderEnum = typeof ListGroupsSortOrderEnum[keyof typeof ListGroupsSortOrderEnum];
