/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMachineUserInputBody,
  DeleteMachineUserOutputBody,
  ErrorModel,
  GetMachineUserOutputBody,
  GetMachineUserPermissionsOutputBody,
  HandleMachineUserOutputBody,
  PaginatedMachineUserResult,
  UpdateMachineUserInputBody,
} from '../models/index';
import {
    CreateMachineUserInputBodyFromJSON,
    CreateMachineUserInputBodyToJSON,
    DeleteMachineUserOutputBodyFromJSON,
    DeleteMachineUserOutputBodyToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetMachineUserOutputBodyFromJSON,
    GetMachineUserOutputBodyToJSON,
    GetMachineUserPermissionsOutputBodyFromJSON,
    GetMachineUserPermissionsOutputBodyToJSON,
    HandleMachineUserOutputBodyFromJSON,
    HandleMachineUserOutputBodyToJSON,
    PaginatedMachineUserResultFromJSON,
    PaginatedMachineUserResultToJSON,
    UpdateMachineUserInputBodyFromJSON,
    UpdateMachineUserInputBodyToJSON,
} from '../models/index';

export interface CreateMachineUserRequest {
    createMachineUserInputBody: Omit<CreateMachineUserInputBody, '$schema'>;
}

export interface DeleteMachineUserRequest {
    id: string;
}

export interface DisableMachineUserRequest {
    id: string;
}

export interface EnableMachineUserRequest {
    id: string;
}

export interface GetMachineMachineUserRequest {
    id: string;
    deleted?: boolean;
}

export interface GetMachineUserPermissionsRequest {
    id: string;
    deleted?: boolean;
}

export interface ListMachineUsersRequest {
    deleted?: boolean;
    tenantId?: string;
    zedToken?: string;
    cursor?: string;
    pageSize?: number;
    sortOrder?: ListMachineUsersSortOrderEnum;
}

export interface UpdateMachineUserRequest {
    id: string;
    updateMachineUserInputBody: Omit<UpdateMachineUserInputBody, '$schema'>;
}

/**
 * 
 */
export class MachineUserApi extends runtime.BaseAPI {

    /**
     * Creates a new machine user
     * Create Machine User
     */
    async createMachineUserRaw(requestParameters: CreateMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleMachineUserOutputBody>> {
        if (requestParameters['createMachineUserInputBody'] == null) {
            throw new runtime.RequiredError(
                'createMachineUserInputBody',
                'Required parameter "createMachineUserInputBody" was null or undefined when calling createMachineUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMachineUserInputBodyToJSON(requestParameters['createMachineUserInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleMachineUserOutputBodyFromJSON(jsonValue));
    }

    /**
     * Creates a new machine user
     * Create Machine User
     */
    async createMachineUser(requestParameters: CreateMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleMachineUserOutputBody> {
        const response = await this.createMachineUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a Machine User
     * Delete Machine User
     */
    async deleteMachineUserRaw(requestParameters: DeleteMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteMachineUserOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteMachineUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteMachineUserOutputBodyFromJSON(jsonValue));
    }

    /**
     * Deletes a Machine User
     * Delete Machine User
     */
    async deleteMachineUser(requestParameters: DeleteMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteMachineUserOutputBody> {
        const response = await this.deleteMachineUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Disables a Machine User
     * Disable Machine User
     */
    async disableMachineUserRaw(requestParameters: DisableMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleMachineUserOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling disableMachineUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users/{id}/disable`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleMachineUserOutputBodyFromJSON(jsonValue));
    }

    /**
     * Disables a Machine User
     * Disable Machine User
     */
    async disableMachineUser(requestParameters: DisableMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleMachineUserOutputBody> {
        const response = await this.disableMachineUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enables a Machine User
     * Enable Machine User
     */
    async enableMachineUserRaw(requestParameters: EnableMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleMachineUserOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enableMachineUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users/{id}/enable`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleMachineUserOutputBodyFromJSON(jsonValue));
    }

    /**
     * Enables a Machine User
     * Enable Machine User
     */
    async enableMachineUser(requestParameters: EnableMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleMachineUserOutputBody> {
        const response = await this.enableMachineUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets a Machine User
     * Get a Machine User
     */
    async getMachineMachineUserRaw(requestParameters: GetMachineMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMachineUserOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMachineMachineUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deleted'] != null) {
            queryParameters['deleted'] = requestParameters['deleted'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMachineUserOutputBodyFromJSON(jsonValue));
    }

    /**
     * Gets a Machine User
     * Get a Machine User
     */
    async getMachineMachineUser(requestParameters: GetMachineMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMachineUserOutputBody> {
        const response = await this.getMachineMachineUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets a Machine User\'s Permissions
     * Get a Machine User\'s Permissions
     */
    async getMachineUserPermissionsRaw(requestParameters: GetMachineUserPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMachineUserPermissionsOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMachineUserPermissions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deleted'] != null) {
            queryParameters['deleted'] = requestParameters['deleted'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users/{id}/permissions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMachineUserPermissionsOutputBodyFromJSON(jsonValue));
    }

    /**
     * Gets a Machine User\'s Permissions
     * Get a Machine User\'s Permissions
     */
    async getMachineUserPermissions(requestParameters: GetMachineUserPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMachineUserPermissionsOutputBody> {
        const response = await this.getMachineUserPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists Machine Users
     * List Machine User
     */
    async listMachineUsersRaw(requestParameters: ListMachineUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedMachineUserResult>> {
        const queryParameters: any = {};

        if (requestParameters['deleted'] != null) {
            queryParameters['deleted'] = requestParameters['deleted'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenant_id'] = requestParameters['tenantId'];
        }

        if (requestParameters['zedToken'] != null) {
            queryParameters['zed_token'] = requestParameters['zedToken'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sort_order'] = requestParameters['sortOrder'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedMachineUserResultFromJSON(jsonValue));
    }

    /**
     * Lists Machine Users
     * List Machine User
     */
    async listMachineUsers(requestParameters: ListMachineUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedMachineUserResult> {
        const response = await this.listMachineUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a Machine User
     * Update Machine User
     */
    async updateMachineUserRaw(requestParameters: UpdateMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleMachineUserOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateMachineUser().'
            );
        }

        if (requestParameters['updateMachineUserInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateMachineUserInputBody',
                'Required parameter "updateMachineUserInputBody" was null or undefined when calling updateMachineUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/machine_users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMachineUserInputBodyToJSON(requestParameters['updateMachineUserInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleMachineUserOutputBodyFromJSON(jsonValue));
    }

    /**
     * Updates a Machine User
     * Update Machine User
     */
    async updateMachineUser(requestParameters: UpdateMachineUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleMachineUserOutputBody> {
        const response = await this.updateMachineUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListMachineUsersSortOrderEnum = {
    asc: 'asc',
    desc: 'desc',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ListMachineUsersSortOrderEnum = typeof ListMachineUsersSortOrderEnum[keyof typeof ListMachineUsersSortOrderEnum];
