/* tslint:disable */
/* eslint-disable */ // @ts-nocheck
/**
 * Jupiter Admin Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index';

export interface GetAllCategoriesSummaryCSVRequest {
    startTime?: Date;
    endTime?: Date;
}

export interface GetAllTenantsDailyUsageCSVRequest {
    startTime?: Date;
    endTime?: Date;
}

export interface GetAllTenantsUsageSummaryCSVRequest {
    startTime?: Date;
    endTime?: Date;
}

export interface GetTenantCategoriesDailyUsageCSVRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
}

export interface GetTenantCategoriesSummaryCSVRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
}

export interface GetTenantDailyUsageCSVRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
}

export interface GetTenantUsageSummaryCSVRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
}

export interface GetTenantUsersSummaryCSVRequest {
    id: string;
    startTime?: Date;
    endTime?: Date;
}

export interface GetUserDailyUsageCSVRequest {
    tenantId: string;
    userId: string;
    startTime?: Date;
    endTime?: Date;
}

export interface GetUserUsageSummaryCSVRequest {
    tenantId: string;
    userId: string;
    startTime?: Date;
    endTime?: Date;
}

/**
 * 
 */
export class UsageExportApi extends runtime.BaseAPI {

    /**
     * Export aggregated usage summary metrics for all categories across all tenants as CSV file (admin only)
     * Get Summary CSV for All Categories Across All Tenants
     */
    async getAllCategoriesSummaryCSVRaw(requestParameters: GetAllCategoriesSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/categories/summary/csv`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export aggregated usage summary metrics for all categories across all tenants as CSV file (admin only)
     * Get Summary CSV for All Categories Across All Tenants
     */
    async getAllCategoriesSummaryCSV(requestParameters: GetAllCategoriesSummaryCSVRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAllCategoriesSummaryCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export all tenants daily usage as CSV file (admin only)
     * Get All Tenants Daily Usage CSV
     */
    async getAllTenantsDailyUsageCSVRaw(requestParameters: GetAllTenantsDailyUsageCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/daily/csv`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export all tenants daily usage as CSV file (admin only)
     * Get All Tenants Daily Usage CSV
     */
    async getAllTenantsDailyUsageCSV(requestParameters: GetAllTenantsDailyUsageCSVRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAllTenantsDailyUsageCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export all tenants usage summary as CSV file (admin only)
     * Get All Tenants Usage Summary CSV
     */
    async getAllTenantsUsageSummaryCSVRaw(requestParameters: GetAllTenantsUsageSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/summary/csv`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export all tenants usage summary as CSV file (admin only)
     * Get All Tenants Usage Summary CSV
     */
    async getAllTenantsUsageSummaryCSV(requestParameters: GetAllTenantsUsageSummaryCSVRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAllTenantsUsageSummaryCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export tenant categories daily usage as CSV file
     * Get Tenant Categories Daily Usage CSV
     */
    async getTenantCategoriesDailyUsageCSVRaw(requestParameters: GetTenantCategoriesDailyUsageCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTenantCategoriesDailyUsageCSV().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/{id}/categories/daily/csv`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export tenant categories daily usage as CSV file
     * Get Tenant Categories Daily Usage CSV
     */
    async getTenantCategoriesDailyUsageCSV(requestParameters: GetTenantCategoriesDailyUsageCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getTenantCategoriesDailyUsageCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export tenant categories summary as CSV file
     * Get Tenant Categories Summary CSV
     */
    async getTenantCategoriesSummaryCSVRaw(requestParameters: GetTenantCategoriesSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTenantCategoriesSummaryCSV().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/{id}/categories/summary/csv`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export tenant categories summary as CSV file
     * Get Tenant Categories Summary CSV
     */
    async getTenantCategoriesSummaryCSV(requestParameters: GetTenantCategoriesSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getTenantCategoriesSummaryCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export tenant daily usage as CSV file
     * Get Tenant Daily Usage CSV
     */
    async getTenantDailyUsageCSVRaw(requestParameters: GetTenantDailyUsageCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTenantDailyUsageCSV().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/{id}/daily/csv`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export tenant daily usage as CSV file
     * Get Tenant Daily Usage CSV
     */
    async getTenantDailyUsageCSV(requestParameters: GetTenantDailyUsageCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getTenantDailyUsageCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export tenant usage summary as CSV file
     * Get Tenant Usage Summary CSV
     */
    async getTenantUsageSummaryCSVRaw(requestParameters: GetTenantUsageSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTenantUsageSummaryCSV().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/{id}/summary/csv`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export tenant usage summary as CSV file
     * Get Tenant Usage Summary CSV
     */
    async getTenantUsageSummaryCSV(requestParameters: GetTenantUsageSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getTenantUsageSummaryCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export aggregated usage summary metrics for all users within a specific tenant as CSV file
     * Get Tenant Users Summary CSV
     */
    async getTenantUsersSummaryCSVRaw(requestParameters: GetTenantUsersSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTenantUsersSummaryCSV().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/{id}/users/summary/csv`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export aggregated usage summary metrics for all users within a specific tenant as CSV file
     * Get Tenant Users Summary CSV
     */
    async getTenantUsersSummaryCSV(requestParameters: GetTenantUsersSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getTenantUsersSummaryCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export user daily usage as CSV file
     * Get User Daily Usage CSV
     */
    async getUserDailyUsageCSVRaw(requestParameters: GetUserDailyUsageCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling getUserDailyUsageCSV().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserDailyUsageCSV().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/{tenant_id}/users/{user_id}/daily/csv`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export user daily usage as CSV file
     * Get User Daily Usage CSV
     */
    async getUserDailyUsageCSV(requestParameters: GetUserDailyUsageCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getUserDailyUsageCSVRaw(requestParameters, initOverrides);
    }

    /**
     * Export user usage summary as CSV file
     * Get User Usage Summary CSV
     */
    async getUserUsageSummaryCSVRaw(requestParameters: GetUserUsageSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling getUserUsageSummaryCSV().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserUsageSummaryCSV().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("jwt", []);
        }

        const response = await this.request({
            path: `/api/v1/usage/tenants/{tenant_id}/users/{user_id}/summary/csv`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export user usage summary as CSV file
     * Get User Usage Summary CSV
     */
    async getUserUsageSummaryCSV(requestParameters: GetUserUsageSummaryCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getUserUsageSummaryCSVRaw(requestParameters, initOverrides);
    }

}
